# Manipulación de datos (5) - Filtrado y transformación

Se han visto muchas aplicaciones de Pandas para manipular datos, sin embargo, aún nos quedan ver algunas funciones/aplicaciones interesantes por ver.

*******

Importamos NumPy y Pandas:

In [1]:
import pandas as pd
import numpy as np

Configuramos algunas opciones de Pandas:

In [2]:
pd.options.display.max_columns = None
pd.options.display.precision = 5

*******

*******

## 1. Función `assign()`

La función assign() es útil cuando se desea agregar una o varias columnas calculadas a partir de columnas existentes o agregar columnas que dependen de los datos actuales del DataFrame.

In [3]:
df = pd.DataFrame({'A': [1, 2, 3, 4, 5],
                   'B': [10, 20, 30, 40, 50]})

df_nuevo = df.assign(C=df['A'] + df['B'],  # C es la suma de A y B
                     D=df['A'] * df['B'])  # D es el producto de A y B


df_nuevo

   A   B   C    D
0  1  10  11   10
1  2  20  22   40
2  3  30  33   90
3  4  40  44  160
4  5  50  55  250

Aunque simplemente se puede hacer lo siguiente:

In [ ]:
df["C"] = df['A'] + df['B']
df["D"] = df['A'] * df['B']
df

   A   B   C    D
0  1  10  11   10
1  2  20  22   40
2  3  30  33   90
3  4  40  44  160
4  5  50  55  250

******

******

## 2. Manipulación y filtrado con Regex

Conjunto de datos:

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/JorgeRincon-PY/datasets/main/jamones.csv")
df.columns = ["Texto"]
df

                                                 Texto
0    100 JAMON DE BELLOTA 100% IBERICO CON CAJA PRE...
1    100 JAMON DE BELLOTA 100% IBERICO SIN CAJA PRE...
2         106 JAMON DE BELLOTA IBERICO 50%   27,50€/KG
3    107 JAMON DE BELLOTA IBERICO 50% DESHUESADO   ...
4    150 TAQUITOS DE JAMON DE BELLOTA IBERICO 50% R...
..                                                 ...
176          301 QUESO FILLOY OVEJA ENTEROS  16,25€/KG
177       301 QUESO FILLOY OVEJA EN MITADES  16,56€/KG
178                  305 QUESO MEZCLA MINI   14,70€/KG
179  700 ACEITE BENITO 0.5 L BOTELLA PLÁSTICO   4,1...
180        702 ACEITE BENITO 5 LITROS   41,88€/BOTELLA

[181 rows x 1 columns]

Primer registro:

In [5]:
df.loc[0, "Texto"]

'100 JAMON DE BELLOTA 100% IBERICO CON CAJA PREMIUM  42,50€/KG'

### 2.1. Manipulación utilizando regex

La función `.str.extract()`. Para utilizar esta función, debemos definir grupos utilizando paréntesis dentro del patrón. La función extrae las coincidencias y devuelve los grupos como columnas en un dataframe.

- Si se quisiera conseguir el número de producto:

In [6]:
patron = r"^(.{0,3})"

df = df.assign(n_producto = df["Texto"].str.extract(patron))
df

                                                 Texto n_producto
0    100 JAMON DE BELLOTA 100% IBERICO CON CAJA PRE...        100
1    100 JAMON DE BELLOTA 100% IBERICO SIN CAJA PRE...        100
2         106 JAMON DE BELLOTA IBERICO 50%   27,50€/KG        106
3    107 JAMON DE BELLOTA IBERICO 50% DESHUESADO   ...        107
4    150 TAQUITOS DE JAMON DE BELLOTA IBERICO 50% R...        150
..                                                 ...        ...
176          301 QUESO FILLOY OVEJA ENTEROS  16,25€/KG        301
177       301 QUESO FILLOY OVEJA EN MITADES  16,56€/KG        301
178                  305 QUESO MEZCLA MINI   14,70€/KG        305
179  700 ACEITE BENITO 0.5 L BOTELLA PLÁSTICO   4,1...        700
180        702 ACEITE BENITO 5 LITROS   41,88€/BOTELLA        702

[181 rows x 2 columns]

- O el precio de cada producto:

In [7]:
patron = r"(\d*,\d\d€/[a-zA-Z]+)"

df = df.assign(precio = df["Texto"].str.extract(patron))
df

,Texto,n_producto,precio
0,100 JAMON DE BELLOTA 100% IBERICO CON CAJA PRE...,100,"42,50€/KG"
1,100 JAMON DE BELLOTA 100% IBERICO SIN CAJA PRE...,100,"38,75€/KG"
2,"106 JAMON DE BELLOTA IBERICO 50% 27,50€/KG",106,"27,50€/KG"
3,107 JAMON DE BELLOTA IBERICO 50% DESHUESADO ...,107,"53,75€/KG"
4,150 TAQUITOS DE JAMON DE BELLOTA IBERICO 50% R...,150,"8,19€/SOBRE"
...,...,...,...
176,"301 QUESO FILLOY OVEJA ENTEROS 16,25€/KG",301,"16,25€/KG"
177,"301 QUESO FILLOY OVEJA EN MITADES 16,56€/KG",301,"16,56€/KG"
178,"305 QUESO MEZCLA MINI 14,70€/KG",305,"14,70€/KG"
179,"700 ACEITE BENITO 0.5 L BOTELLA PLÁSTICO 4,1...",700,"4,19€/BOTELLA"
180,"702 ACEITE BENITO 5 LITROS 41,88€/BOTELLA",702,"41,88€/BOTELLA"

La función `.replace()`. Esta función sustituye las coincidencias por el string propuesto.

- Si se quiere remplazar una expresión por otra:

In [8]:
patron = r"^(.{0,3})|(\d*,\d\d€/[a-zA-Z]+)"

df = df.assign(producto= df["Texto"].str.replace(patron, "", regex=True))
df

,Texto,n_producto,precio,producto
0,100 JAMON DE BELLOTA 100% IBERICO CON CAJA PRE...,100,"42,50€/KG",JAMON DE BELLOTA 100% IBERICO CON CAJA PREMIUM
1,100 JAMON DE BELLOTA 100% IBERICO SIN CAJA PRE...,100,"38,75€/KG",JAMON DE BELLOTA 100% IBERICO SIN CAJA PREMIUM
2,"106 JAMON DE BELLOTA IBERICO 50% 27,50€/KG",106,"27,50€/KG",JAMON DE BELLOTA IBERICO 50%
3,107 JAMON DE BELLOTA IBERICO 50% DESHUESADO ...,107,"53,75€/KG",JAMON DE BELLOTA IBERICO 50% DESHUESADO
4,150 TAQUITOS DE JAMON DE BELLOTA IBERICO 50% R...,150,"8,19€/SOBRE",TAQUITOS DE JAMON DE BELLOTA IBERICO 50% RI 1...
...,...,...,...,...
176,"301 QUESO FILLOY OVEJA ENTEROS 16,25€/KG",301,"16,25€/KG",QUESO FILLOY OVEJA ENTEROS
177,"301 QUESO FILLOY OVEJA EN MITADES 16,56€/KG",301,"16,56€/KG",QUESO FILLOY OVEJA EN MITADES
178,"305 QUESO MEZCLA MINI 14,70€/KG",305,"14,70€/KG",QUESO MEZCLA MINI
179,"700 ACEITE BENITO 0.5 L BOTELLA PLÁSTICO 4,1...",700,"4,19€/BOTELLA",ACEITE BENITO 0.5 L BOTELLA PLÁSTICO
180,"702 ACEITE BENITO 5 LITROS 41,88€/BOTELLA",702,"41,88€/BOTELLA",ACEITE BENITO 5 LITROS

## 2.2. Filtrado con Regex

La función `.contains()`. Esta función comprueba un patrón en una columna (Serie) para devolver valores True y False cuando el patrón coincide.

In [9]:
patron = r"100%.*iberico|iberico.*100%"

df[df["Texto"].str.lower().str.contains(patron)]

,Texto,n_producto,precio,producto
0,100 JAMON DE BELLOTA 100% IBERICO CON CAJA PRE...,100,"42,50€/KG",JAMON DE BELLOTA 100% IBERICO CON CAJA PREMIUM
1,100 JAMON DE BELLOTA 100% IBERICO SIN CAJA PRE...,100,"38,75€/KG",JAMON DE BELLOTA 100% IBERICO SIN CAJA PREMIUM
52,102 JAMON DE BELLOTA 100% IBERICO C/CUCHILLO 1...,102,"9,88€/SOBRE",JAMON DE BELLOTA 100% IBERICO C/CUCHILLO 100G...
53,103 JAMON DE BELLOTA 100% IBERICO C/CUCHILLO 1...,103,"10,13€/SOBRE",JAMON DE BELLOTA 100% IBERICO C/CUCHILLO 100G...
126,"401 LOMO DE BELLOTA 100% IBERICO ENTEROS 43,7...",401,"43,75€/KG",LOMO DE BELLOTA 100% IBERICO ENTEROS
127,401 LOMO DE BELLOTA 100% IBERICO EN MITADES 4...,401,"44,05€/KG",LOMO DE BELLOTA 100% IBERICO EN MITADES

******

******

## 3. Manipular y filtrar fechas

Conjunto de datos:

In [10]:
df = pd.DataFrame({'nombre': ['Ana', 'Ana', 'Ana', 'Antonio', 'Antonio'],
                   'destino': ['Japon', 'Corea del Sur', 'Suiza', 'EEUU', 'Suiza'],
                   'fecha_salida': ['2023-02-02', '2023-01-01', '2023-01-11', '2023-05-05', '2023-01-11'],
                   'duracion': [7, 9, 14, 10, 14]})

df.fecha_salida = pd.to_datetime(df.fecha_salida)
df.duracion = pd.to_timedelta(df.duracion, 'D')
df

    nombre        destino fecha_salida duracion
0      Ana          Japon   2023-02-02   7 days
1      Ana  Corea del Sur   2023-01-01   9 days
2      Ana          Suiza   2023-01-11  14 days
3  Antonio           EEUU   2023-05-05  10 days
4  Antonio          Suiza   2023-01-11  14 days

Es importante mencionar que para reordenar las columnas se puede aplicar lo siguiente:

In [11]:
df = df[["fecha_salida", "nombre", "destino", "duracion"]]
df

  fecha_salida   nombre        destino duracion
0   2023-02-02      Ana          Japon   7 days
1   2023-01-01      Ana  Corea del Sur   9 days
2   2023-01-11      Ana          Suiza  14 days
3   2023-05-05  Antonio           EEUU  10 days
4   2023-01-11  Antonio          Suiza  14 days

****

### 3.1. Diferencia entre fechas

Se puede crear un TimeStamp con Pandas al igual que lo hicimos con datetime:

In [ ]:
pd.to_datetime('today')

Timestamp('2024-01-18 19:39:05.440452')

Recordar que cualquier diferencia entre fechas será un timedelta:

In [ ]:
pd.to_datetime('today') - pd.to_datetime('01-01-2024')

Timedelta('17 days 19:39:23.478736')

In [ ]:
df = df.assign(fecha_llegada = df.fecha_salida + df.duracion)
df

  fecha_salida   nombre        destino duracion fecha_llegada
0   2023-02-02      Ana          Japon   7 days    2023-02-09
1   2023-01-01      Ana  Corea del Sur   9 days    2023-01-10
2   2023-01-11      Ana          Suiza  14 days    2023-01-25
3   2023-05-05  Antonio           EEUU  10 days    2023-05-15
4   2023-01-11  Antonio          Suiza  14 days    2023-01-25

****

### 3.2. Filtrado de fechas

Para filtrar las fechas, es interesante utilizar `.query()`

In [12]:
df.query("fecha_salida.dt.day == 1")

  fecha_salida nombre        destino duracion
1   2023-01-01    Ana  Corea del Sur   9 days

Se puede incluir una variable sin la necesidad de tener que utilizar f-strings

In [13]:
mes = 1
df.query("fecha_salida.dt.month == @mes")

  fecha_salida   nombre        destino duracion
1   2023-01-01      Ana  Corea del Sur   9 days
2   2023-01-11      Ana          Suiza  14 days
4   2023-01-11  Antonio          Suiza  14 days

La función `between()` ayuda a filtrar en un rango:

In [14]:
df[df.fecha_salida.dt.day.between(2, 5)]

  fecha_salida   nombre destino duracion
0   2023-02-02      Ana   Japon   7 days
3   2023-05-05  Antonio    EEUU  10 days

*****

### 3.3. `resample()`

Pandas consigue tambien agregar o contraer información cuando se trata de una fecha. Para ello es necesario tener el indice como fecha y utilizar .resample():

In [ ]:
df.set_index("fecha_salida").query("nombre == 'Ana'")

             nombre        destino duracion fecha_llegada
fecha_salida
2023-02-02      Ana          Japon   7 days    2023-02-09
2023-01-01      Ana  Corea del Sur   9 days    2023-01-10
2023-01-11      Ana          Suiza  14 days    2023-01-25

In [ ]:
df.set_index("fecha_salida").query("nombre == 'Ana'").resample("D").sum()

<ipython-input-24-64ac1fd877a9>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.set_index("fecha_salida").query("nombre == 'Ana'").resample("D").sum()

             nombre        destino duracion
fecha_salida
2023-01-01      Ana  Corea del Sur   9 days
2023-01-02        0              0   0 days
2023-01-03        0              0   0 days
2023-01-04        0              0   0 days
2023-01-05        0              0   0 days
2023-01-06        0              0   0 days
2023-01-07        0              0   0 days
2023-01-08        0              0   0 days
2023-01-09        0              0   0 days
2023-01-10        0              0   0 days
2023-01-11      Ana          Suiza  14 days
2023-01-12        0              0   0 days
2023-01-13        0              0   0 days
2023-01-14        0              0   0 days
2023-01-15        0              0   0 days
2023-01-16        0              0   0 days
2023-01-17        0              0   0 days
2023-01-18        0              0   0 days
2023-01-19        0              0   0 days
2023-01-20        0              0   0 days
2023-01-21        0              0   0 days
2023-01-22        0              0   0 days
2023-01-23        0              0   0 days
2023-01-24        0              0   0 days
2023-01-25        0              0   0 days
2023-01-26        0              0   0 days
2023-01-27        0              0   0 days
2023-01-28        0              0   0 days
2023-01-29        0              0   0 days
2023-01-30        0              0   0 days
2023-01-31        0              0   0 days
2023-02-01        0              0   0 days
2023-02-02      Ana          Japon   7 days

Las reglas según la documentación de Pandas:

- B:         business day frequency
- C:         custom business day frequency
- D:         calendar day frequency
- W:         weekly frequency
- M:         month end frequency
- SM:        semi-month end frequency (15th and end of month)
- BM:        business month end frequency
- CBM:       custom business month end frequency
- MS:        month start frequency
- SMS:       semi-month start frequency (1st and 15th)
- BMS:       business month start frequency
- CBMS:      custom business month start frequency
- Q:         quarter end frequency
- BQ:        business quarter endfrequency
- QS:        quarter start frequency
- BQS:       business quarter start frequency
- A:         year end frequency
- BA, BY:    business year end frequency
- AS, YS:    year start frequency
- BAS, BYS:  business year start frequency
- BH:        business hour frequency
- H:         hourly frequency
- T, min:    minutely frequency
- S:         secondly frequency
- L, ms:     milliseconds
- U, us:     microseconds
- N:         nanoseconds

******

### 3.4. Otras funciones interesantes

Obtener un rango de fechas:
- `date_range()`

Aunque son menos conocidas, las funciones siguientes se suelen ayudar cuando nuesto index es datetime:
- `between_time()`
- `at_time()`

Podemos hacer sumas moviles/medias moviles con la función `rolling()`

*****

*****

In [ ]:
df

  fecha_salida   nombre        destino duracion fecha_llegada
0   2023-02-02      Ana          Japon   7 days    2023-02-09
1   2023-01-01      Ana  Corea del Sur   9 days    2023-01-10
2   2023-01-11      Ana          Suiza  14 days    2023-01-25
3   2023-05-05  Antonio           EEUU  10 days    2023-05-15
4   2023-01-11  Antonio          Suiza  14 days    2023-01-25

## 4. Conversión de estructuras de datos a columnas

La función `literal_eval` nos permite convertir un string a una estructura de datos:

In [ ]:
from ast import literal_eval

a = "[1,2,3]"
print(type(a))

b = literal_eval(a)
print(type(b))

<class 'str'>
<class 'list'>

Conjunto de datos:

In [ ]:
df = pd.DataFrame({'pelicula': ["It's a Wonderful Life", "Duck Soup", "His Girl Friday", "The Three Stooges", "Red River"],
                   'generos': ["['drama', 'family', 'fantasy', 'romance', 'comedy']",
                               "['comedy', 'war']",
                               "['drama', 'romance', 'comedy']",
                               "['comedy', 'family']",
                               "['western', 'drama', 'romance', 'action']"],
                   'puntuacion': [8.6, 7.8, 7.8, 8.5, 7.8],
                   'otra_informacion': [{"Tipo": "MOVIE",
                                         "Votos": 467766,
                                         "Certificacion": "PG",
                                         "Duracion": 130,
                                         "Pais": "US"},
                                        {"Tipo": "MOVIE",
                                         "Votos": 60933,
                                         "Duracion": 69,
                                         "Pais": "US"},
                                        {"Tipo": "MOVIE",
                                         "Votos": 60244,
                                         "Duracion": 92,
                                         "Pais": "US"},
                                        {"Tipo": "SHOW",
                                         "Temporada": 26,
                                         "Votos": 1149,
                                         "Certificacion": "TV-PG",
                                         "Duracion": 19,
                                         "Pais": "US"},
                                        {"Tipo": "MOVIE",
                                         "Votos": 32210,
                                         "Duracion": 133,
                                         "Pais": "US"}] })
df

,pelicula,generos,puntuacion,otra_informacion
0,It's a Wonderful Life,"['drama', 'family', 'fantasy', 'romance', 'com...",8.6,"{'Tipo': 'MOVIE', 'Votos': 467766, 'Certificac..."
1,Duck Soup,"['comedy', 'war']",7.8,"{'Tipo': 'MOVIE', 'Votos': 60933, 'Duracion': ..."
2,His Girl Friday,"['drama', 'romance', 'comedy']",7.8,"{'Tipo': 'MOVIE', 'Votos': 60244, 'Duracion': ..."
3,The Three Stooges,"['comedy', 'family']",8.5,"{'Tipo': 'SHOW', 'Temporada': 26, 'Votos': 114..."
4,Red River,"['western', 'drama', 'romance', 'action']",7.8,"{'Tipo': 'MOVIE', 'Votos': 32210, 'Duracion': ..."

Si se aplica la función literal_eval, los elementos ya no serán strings, sino que serán estructuras de datos:

In [ ]:
from ast import literal_eval

df.generos = df.generos.apply(literal_eval)

ValueError: malformed node or string: ['drama', 'family', 'fantasy', 'romance', 'comedy']

In [ ]:
df

,pelicula,generos,puntuacion,otra_informacion
0,It's a Wonderful Life,"[drama, family, fantasy, romance, comedy]",8.6,"{'Tipo': 'MOVIE', 'Votos': 467766, 'Certificac..."
1,Duck Soup,"[comedy, war]",7.8,"{'Tipo': 'MOVIE', 'Votos': 60933, 'Duracion': ..."
2,His Girl Friday,"[drama, romance, comedy]",7.8,"{'Tipo': 'MOVIE', 'Votos': 60244, 'Duracion': ..."
3,The Three Stooges,"[comedy, family]",8.5,"{'Tipo': 'SHOW', 'Temporada': 26, 'Votos': 114..."
4,Red River,"[western, drama, romance, action]",7.8,"{'Tipo': 'MOVIE', 'Votos': 32210, 'Duracion': ..."

### 4.1. Manipulación de las estructuras de datos

- `.explode()` permite expandir una lista, teniendo como resultado un conjunto de datos diferente:

In [ ]:
len(df.explode("generos"))

16

In [ ]:
df.explode("generos")

,pelicula,generos,puntuacion,otra_informacion
0,It's a Wonderful Life,drama,8.6,"{'Tipo': 'MOVIE', 'Votos': 467766, 'Certificac..."
0,It's a Wonderful Life,family,8.6,"{'Tipo': 'MOVIE', 'Votos': 467766, 'Certificac..."
0,It's a Wonderful Life,fantasy,8.6,"{'Tipo': 'MOVIE', 'Votos': 467766, 'Certificac..."
0,It's a Wonderful Life,romance,8.6,"{'Tipo': 'MOVIE', 'Votos': 467766, 'Certificac..."
0,It's a Wonderful Life,comedy,8.6,"{'Tipo': 'MOVIE', 'Votos': 467766, 'Certificac..."
1,Duck Soup,comedy,7.8,"{'Tipo': 'MOVIE', 'Votos': 60933, 'Duracion': ..."
1,Duck Soup,war,7.8,"{'Tipo': 'MOVIE', 'Votos': 60933, 'Duracion': ..."
2,His Girl Friday,drama,7.8,"{'Tipo': 'MOVIE', 'Votos': 60244, 'Duracion': ..."
2,His Girl Friday,romance,7.8,"{'Tipo': 'MOVIE', 'Votos': 60244, 'Duracion': ..."
2,His Girl Friday,comedy,7.8,"{'Tipo': 'MOVIE', 'Votos': 60244, 'Duracion': ..."
3,The Three Stooges,comedy,8.5,"{'Tipo': 'SHOW', 'Temporada': 26, 'Votos': 114..."
3,The Three Stooges,family,8.5,"{'Tipo': 'SHOW', 'Temporada': 26, 'Votos': 114..."
4,Red River,western,7.8,"{'Tipo': 'MOVIE', 'Votos': 32210, 'Duracion': ..."
4,Red River,drama,7.8,"{'Tipo': 'MOVIE', 'Votos': 32210, 'Duracion': ..."
4,Red River,romance,7.8,"{'Tipo': 'MOVIE', 'Votos': 32210, 'Duracion': ..."
4,Red River,action,7.8,"{'Tipo': 'MOVIE', 'Votos': 32210, 'Duracion': ..."

- `pd.Series` nos permite desglosar en columnas los diferentes ítems:

In [ ]:
df.generos.apply(pd.Series) # Aplicado a generos

         0        1        2        3       4
0    drama   family  fantasy  romance  comedy
1   comedy      war      NaN      NaN     NaN
2    drama  romance   comedy      NaN     NaN
3   comedy   family      NaN      NaN     NaN
4  western    drama  romance   action     NaN

In [ ]:
df.otra_informacion.apply(pd.Series) # Aplicado a otra_informacion

    Tipo   Votos Certificacion  Duracion Pais  Temporada
0  MOVIE  467766            PG       130   US        NaN
1  MOVIE   60933           NaN        69   US        NaN
2  MOVIE   60244           NaN        92   US        NaN
3   SHOW    1149         TV-PG        19   US       26.0
4  MOVIE   32210           NaN       133   US        NaN

Se puede hacer efectivo el cambio de la siguiente forma:

In [ ]:
df.assign(**df.otra_informacion.apply(pd.Series))

,pelicula,generos,puntuacion,otra_informacion,Tipo,Votos,Certificacion,Duracion,Pais,Temporada
0,It's a Wonderful Life,"[drama, family, fantasy, romance, comedy]",8.6,"{'Tipo': 'MOVIE', 'Votos': 467766, 'Certificac...",MOVIE,467766,PG,130,US,NaN
1,Duck Soup,"[comedy, war]",7.8,"{'Tipo': 'MOVIE', 'Votos': 60933, 'Duracion': ...",MOVIE,60933,NaN,69,US,NaN
2,His Girl Friday,"[drama, romance, comedy]",7.8,"{'Tipo': 'MOVIE', 'Votos': 60244, 'Duracion': ...",MOVIE,60244,NaN,92,US,NaN
3,The Three Stooges,"[comedy, family]",8.5,"{'Tipo': 'SHOW', 'Temporada': 26, 'Votos': 114...",SHOW,1149,TV-PG,19,US,26.0
4,Red River,"[western, drama, romance, action]",7.8,"{'Tipo': 'MOVIE', 'Votos': 32210, 'Duracion': ...",MOVIE,32210,NaN,133,US,NaN

E incluso añadir un prefijo/sufijo si así se desea:

In [ ]:
df.assign(**df.otra_informacion.apply(pd.Series).add_prefix('otra_informacion_'))

,pelicula,generos,puntuacion,otra_informacion,otra_informacion_Tipo,otra_informacion_Votos,otra_informacion_Certificacion,otra_informacion_Duracion,otra_informacion_Pais,otra_informacion_Temporada
0,It's a Wonderful Life,"[drama, family, fantasy, romance, comedy]",8.6,"{'Tipo': 'MOVIE', 'Votos': 467766, 'Certificac...",MOVIE,467766,PG,130,US,NaN
1,Duck Soup,"[comedy, war]",7.8,"{'Tipo': 'MOVIE', 'Votos': 60933, 'Duracion': ...",MOVIE,60933,NaN,69,US,NaN
2,His Girl Friday,"[drama, romance, comedy]",7.8,"{'Tipo': 'MOVIE', 'Votos': 60244, 'Duracion': ...",MOVIE,60244,NaN,92,US,NaN
3,The Three Stooges,"[comedy, family]",8.5,"{'Tipo': 'SHOW', 'Temporada': 26, 'Votos': 114...",SHOW,1149,TV-PG,19,US,26.0
4,Red River,"[western, drama, romance, action]",7.8,"{'Tipo': 'MOVIE', 'Votos': 32210, 'Duracion': ...",MOVIE,32210,NaN,133,US,NaN

*****

### 4.2. Dividir strings en varias columnas

Conjunto de datos:

In [ ]:
df = pd.DataFrame({'profesor': ["Salvador Fernandez", "Jose Novo", "Jorge Rincon"],
                   'puntuacion': [8.6, 9.8, 7.8]})

df

             profesor  puntuacion
0  Salvador Fernandez         8.6
1           Jose Novo         9.8
2        Jorge Rincon         7.8

Se puede usar la función `split()` para poder realizar esto:

In [ ]:
df[["Nombre", "Apellido"]] = df.profesor.str.strip().str.split(" ", expand=True)
df

             profesor  puntuacion    Nombre   Apellido
0  Salvador Fernandez         8.6  Salvador  Fernandez
1           Jose Novo         9.8      Jose       Novo
2        Jorge Rincon         7.8     Jorge     Rincon

*****

*****

## 5. Mejora de sintaxis

### 5.1. `pipe()`

La función pipe() en Pandas permite aplicar una función (o secuencia de funciones) a un DataFrame o Serie de una manera más limpia y legible. pipe() es especialmente útil cuando se encadenan múltiples operaciones en un solo comando. La idea es que pipe() toma una función y sus argumentos y aplica la función al objeto Pandas (DataFrame o Serie) en cuestión.

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/JorgeRincon-PY/datasets/main/Titanic.csv")
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

- Para todo el dateframe:

In [ ]:
def borrar_NAs(df):
    limite = len(df) * 0.6
    df.dropna(axis=1, thresh=limite, inplace=True)
    return df

df.pipe(borrar_NAs)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

- Para una columna:

In [ ]:
def outliers(df, columna):
    Q1 = df[columna].quantile(0.25)
    Q3 = df[columna].quantile(0.75)
    IQR = Q3 - Q1
    filt1 = Q1 - 1.5 * IQR
    filt2 = Q3 + 1.5 * IQR
    return df[df[columna].between(filt1, filt2)].copy()

df.pipe(outliers, "Fare")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,Q
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

- Para múltiples columnas:

In [ ]:
def borrar(df, columnas):
    for columna in columnas:
        df.drop(columna, axis=1, inplace=True)
    return df

columnas = ["Name", "Embarked"]

df.pipe(borrar, columnas)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare
0,1,0,3,male,22.0,1,0,A/5 21171,7.2500
1,2,1,1,female,38.0,1,0,PC 17599,71.2833
2,3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250
3,4,1,1,female,35.0,1,0,113803,53.1000
4,5,0,3,male,35.0,0,0,373450,8.0500
...,...,...,...,...,...,...,...,...,...
886,887,0,2,male,27.0,0,0,211536,13.0000
887,888,1,1,female,19.0,0,0,112053,30.0000
888,889,0,3,female,NaN,1,2,W./C. 6607,23.4500
889,890,1,1,male,26.0,0,0,111369,30.0000
890,891,0,3,male,32.0,0,0,370376,7.7500

Usar pipe() puede mejorar la legibilidad del código, especialmente cuando se encadenan múltiples operaciones en un solo comando. También facilita la reutilización de funciones personalizadas en diferentes partes de tu código.

*****

### 5.2. Chaining (encadenamiento)

Se dice que el encadenamiento es más eficiente que los pasos separados, ya que las operaciones pueden ejecutarse consecutivamente sin crear marcos de datos intermedios que aumenten el uso de memoria de Pandas:

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/JorgeRincon-PY/datasets/main/Titanic.csv")

def borrar_NAs(df):
    limite = len(df) * 0.6
    df.dropna(axis=1, thresh=limite, inplace=True)
    return df

def outliers(df, columna):
    Q1 = df[columna].quantile(0.25)
    Q3 = df[columna].quantile(0.75)
    IQR = Q3 - Q1
    filt1 = Q1 - 1.5 * IQR
    filt2 = Q3 + 1.5 * IQR
    return df[df[columna].between(filt1, filt2)].copy()

def borrar(df, columnas):
    for columna in columnas:
        df.drop(columna, axis=1, inplace=True)
    return df

In [ ]:
(
    df.pipe(borrar_NAs)
      .pipe(outliers, "Fare")
      .pipe(borrar, ["Name", "Embarked"])
)

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare
0,1,0,3,male,22.0,1,0,A/5 21171,7.2500
2,3,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250
3,4,1,1,female,35.0,1,0,113803,53.1000
4,5,0,3,male,35.0,0,0,373450,8.0500
5,6,0,3,male,NaN,0,0,330877,8.4583
...,...,...,...,...,...,...,...,...,...
886,887,0,2,male,27.0,0,0,211536,13.0000
887,888,1,1,female,19.0,0,0,112053,30.0000
888,889,0,3,female,NaN,1,2,W./C. 6607,23.4500
889,890,1,1,male,26.0,0,0,111369,30.0000
890,891,0,3,male,32.0,0,0,370376,7.7500

In [ ]:
(
    df.pipe(borrar_NAs)
      .pipe(outliers, "Fare")
      .pipe(borrar, ["Name", "Embarked"])
      .groupby("Sex")["Fare"]
      .agg(["min", "max", "median"])
)

         min      max    median
Sex
female  6.75  65.0000  15.74585
male    0.00  63.3583   9.50000

****