# Ejercicios - Adquisición de datos

*****

## 1. Archivos y BBDD

#### 1.1. En un nuevo notebook, llama a la BBDD que se uso en módulos anteriores llamada `classicmodels`. Tras esto, realiza una consulta SQL para consultar cuanto stock hay según la linea de producto.

In [1]:
!pip install sqlalchemy
!pip install pymysql

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.10/dist-packages (2.0.34)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from sqlalchemy) (3.1.0)
Collecting pymysql
  Downloading PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 1.9 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1

In [5]:
import sqlalchemy as sa
import pandas as pd

dialect = "mysql"
driver = "pymysql"
username = "usuario1"
password = "C0d35p4ce."
host = "database-1.cjyy8w6ya3fr.eu-north-1.rds.amazonaws.com"
port = "3306"
database = "classicmodels"

connection_string = f"{dialect}+{driver}://{username}:{password}@{host}:{port}/{database}"
engine = sa.create_engine(connection_string)
conn = engine.connect()

sql_query_text = """
SELECT productLine AS Linea_Producto,
       SUM(quantityInStock) AS Suma_Cantidad_Stock
FROM products
GROUP BY productLine
ORDER BY Suma_Cantidad_Stock DESC
"""

sql_query = sa.text(sql_query_text)

query_df = pd.read_sql(sql_query, con=conn)
query_df

     Linea_Producto  Suma_Cantidad_Stock
0      Classic Cars             219183.0
1      Vintage Cars             124880.0
2       Motorcycles              69401.0
3            Planes              62287.0
4  Trucks and Buses              35851.0
5             Ships              26833.0
6            Trains              16696.0

#### 1.2. Realiza lo mismo, pero con las funciones de Pandas, es decir, extrae la tabla completa y realiza la agrupación con las funciones de Pandas.

In [3]:
table_df = pd.read_sql_table("products", con=conn)
table_df.groupby("productLine", as_index=False)["quantityInStock"].sum().sort_values("quantityInStock", ascending=False)

        productLine  quantityInStock
0      Classic Cars           219183
6      Vintage Cars           124880
1       Motorcycles            69401
2            Planes            62287
5  Trucks and Buses            35851
3             Ships            26833
4            Trains            16696

*****

## 2. APIs

#### Utilizando la API de este [sitio web](https://www.thecocktaildb.com/):


#### 2.1. Haz un request y utiliza los parametros del request para obtener las bebidas que empiecen por la letra a. Después filtra por las bebidas que tengan alcohol ¿Cuantos resultados aparecen?

In [6]:
# No se puede obtener un listado de bebidas que empiecen con la letra a y que contengan alcohol. La API no lo permite.
# Tenemos que primero que obtener los cócteles que empiecen por la letra a y luego filtrar los que contengan alcohol.

import requests
import json
import pandas as pd

url = "https://www.thecocktaildb.com/api/json/v1/1/search.php?"
querystring = {"f": "a"}

response = requests.get(url, params=querystring)

df = pd.DataFrame(json.loads(response.content))

df_original = df.copy()

df

                                               drinks
0   {'idDrink': '17222', 'strDrink': 'A1', 'strDri...
1   {'idDrink': '13501', 'strDrink': 'ABC', 'strDr...
2   {'idDrink': '17225', 'strDrink': 'Ace', 'strDr...
3   {'idDrink': '14610', 'strDrink': 'ACID', 'strD...
4   {'idDrink': '13938', 'strDrink': 'AT&T', 'strD...
5   {'idDrink': '17837', 'strDrink': 'Adam', 'strD...
6   {'idDrink': '17833', 'strDrink': 'A. J.', 'str...
7   {'idDrink': '17839', 'strDrink': 'Affair', 'st...
8   {'idDrink': '15266', 'strDrink': 'Avalon', 'st...
9   {'idDrink': '15106', 'strDrink': 'Apello', 'st...
10  {'idDrink': '11023', 'strDrink': 'Almeria', 's...
11  {'idDrink': '17835', 'strDrink': 'Abilene', 's...
12  {'idDrink': '17228', 'strDrink': 'Addison', 's...
13  {'idDrink': '17180', 'strDrink': 'Aviation', '...
14  {'idDrink': '11046', 'strDrink': 'Applecar', '...
15  {'idDrink': '17840', 'strDrink': 'Affinity', '...
16  {'idDrink': '17836', 'strDrink': 'Acapulco', '...
17  {'idDrink': '11014', 'strDrink': 'Alexander', ...
18  {'idDrink': '16419', 'strDrink': 'Avalanche', ...
19  {'idDrink': '11021', 'strDrink': 'Allegheny', ...
20  {'idDrink': '15941', 'strDrink': 'Americano', ...
21  {'idDrink': '11020', 'strDrink': 'Algonquin', ...
22  {'idDrink': '11055', 'strDrink': 'Artillery', ...
23  {'idDrink': '12560', 'strDrink': 'Afterglow', ...
24  {'idDrink': '17227', 'strDrink': 'Addington', ...

In [7]:
df_original.drinks.apply(pd.Series)

,idDrink,strDrink,strDrinkAlternate,strTags,strVideo,strCategory,strIBA,strAlcoholic,strGlass,strInstructions,...,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strImageSource,strImageAttribution,strCreativeCommonsConfirmed,dateModified
0,17222,A1,None,None,None,Cocktail,None,Alcoholic,Cocktail glass,"Pour all ingredients into a cocktail shaker, m...",...,None,None,None,None,None,None,None,None,No,2017-09-07 21:42:09
1,13501,ABC,None,None,None,Shot,None,Alcoholic,Shot glass,Layered in a shot glass.,...,None,None,None,None,None,None,None,None,No,2016-08-31 19:32:08
2,17225,Ace,None,None,None,Cocktail,None,Alcoholic,Martini Glass,Shake all the ingredients in a cocktail shaker...,...,None,None,None,None,None,None,None,None,No,2017-09-07 22:05:06
3,14610,ACID,None,None,None,Shot,None,Alcoholic,Shot glass,Poor in the 151 first followed by the 101 serv...,...,None,None,None,None,None,None,None,None,No,2016-11-15 11:28:37
4,13938,AT&T,None,None,None,Ordinary Drink,None,Alcoholic,Highball Glass,"Pour Vodka and Gin over ice, add Tonic and Stir",...,None,None,None,None,None,None,None,None,No,2017-04-24 22:00:19
5,17837,Adam,None,"Alcoholic,Holiday",None,Ordinary Drink,None,Alcoholic,Cocktail glass,"In a shaker half-filled with ice cubes, combin...",...,None,None,None,None,None,None,None,None,Yes,2016-09-02 11:29:29
6,17833,A. J.,None,None,None,Ordinary Drink,None,Alcoholic,Cocktail glass,"Shake ingredients with ice, strain into a cock...",...,None,None,None,None,None,None,None,None,Yes,2016-09-02 11:16:58
7,17839,Affair,None,None,None,Ordinary Drink,None,Alcoholic,Highball glass,"Pour schnapps, orange juice, and cranberry jui...",...,None,None,None,None,None,None,None,None,Yes,2016-09-01 10:05:34
8,15266,Avalon,None,None,None,Ordinary Drink,None,Alcoholic,Highball glass,Fill a tall glass with ice. Layer the Finlandi...,...,None,None,None,None,None,None,None,None,No,2017-04-24 22:22:11
9,15106,Apello,None,None,None,Other / Unknown,None,Non alcoholic,Collins Glass,Stirr. Grnish with maraschino cherry.,...,None,None,None,None,None,None,None,None,No,2016-07-18 22:13:35
10,11023,Almeria,None,None,None,Ordinary Drink,None,Alcoholic,Cocktail glass,"In a shaker half-filled with ice cubes, combin...",...,None,None,None,None,None,None,None,None,No,2017-01-02 20:16:21
11,17835,Abilene,None,None,None,Ordinary Drink,None,Alcoholic,Highball glass,Pour all of the ingredients into a highball gl...,...,None,None,None,None,None,None,None,None,Yes,2016-04-29 09:44:25
12,17228,Addison,None,None,None,Cocktail,None,Alcoholic,Martini Glass,Shake together all the ingredients and strain ...,...,None,None,None,None,None,None,None,None,No,2017-09-07 22:38:20
13,17180,Aviation,None,"IBA,Classic",https://www.youtube.com/watch?v=oOHH0GGglyM,Cocktail,Unforgettables,Alcoholic,Cocktail glass,Add all ingredients into cocktail shaker fille...,...,None,None,None,None,None,None,https://www.flickr.com/photos/mstyne/278593630...,Michael Styne https://www.flickr.com/photos/ms...,Yes,2016-11-04 09:55:28
14,11046,Applecar,None,None,None,Ordinary Drink,None,Alcoholic,Cocktail glass,"Shake all ingredients with ice, strain into a ...",...,None,None,None,None,None,None,None,None,No,2017-09-02 23:02:44
15,17840,Affinity,None,None,None,Ordinary Drink,None,Alcoholic,Cocktail glass,"In a mixing glass half-filled with ice cubes, ...",...,None,None,None,None,None,None,None,None,Yes,2017-09-07 21:44:05
16,17836,Acapulco,None,None,None,Ordinary Drink,None,Alcoholic,Old-fashioned glass,Combine and shake all ingredients (except mint...,...,None,None,None,None,None,None,None,None,Yes,2016-09-02 11:26:16
17,11014,Alexander,None,"IBA,Classic,Dairy",https://www.youtube.com/watch?v=qEhRK_v2w2g,Ordinary Drink,Unforgettables,Alcoholic,Cocktail glass,Shake all ingredients with ice and strain cont...,...,None,None,None,None,None,None,https://www.pxfuel.com/en/free-photo-expqp,pxfuel.com,Yes,2016-11-04 09:50:39
18,16419,Avalanche,None,None,None,Shake,None,Alcoholic,Highball glass,"Mix in highball glass over ice, shake well.",...,None,None,None,None,None,None,None,None,No,2016-09-01 09:56:05
19,11021,Allegheny,None,None,None,Ordinary Drink,None,Alcoholic,Cocktail glass,Shake all ingredients (except lemon peel) with...,...,None,None,None,None,None,None,None,None,No,2017-01-02 20:12:14
20,15941,Americano,None,"IBA,Classic",https://www.youtube.com/watch?v=TmeUJ2g3ogM,Ordinary Drink,Unforgettables,Alcoholic,Collins glass,Pour the Campari and vermouth over ice into gl...,...,None,None,None,None,None,None,https://commons.wikimedia.org/wiki/File:Martin...,Author - Cher37 https://commons.wikimedia.org/...,Yes,2016-11-04 09:52:06
21,11020,Algonquin,None,None,None,Ordinary Drink,None,Alcoholic,Cocktail glass,"Combine and shake all ingredients with ice, st...",...,None,None,None,None,None,None,None,None,No,2017-01-02 20:11:13
22,11055,Artillery,None,None,None,Ordinary Drink,None,Alcoholic,Cocktail glass,"Stir all ingredients with ice, strain into a c...",...,None,None,None,None,None,None,None,None,No,2017-04-24 22:02:27
23,12560,Afterglow,None,None,None,Cocktail,None,Non alcoholic,Highball Glass,Mix. Serve over ice.,...,None,None,None,None,None,None,None,None,No,2016-07-18 22:07:32
24,17227,Addington,None,None,None,Cocktail,None,Alcoholic,Cocktail glass,Mix both the vermouth's in a shaker and strain...,...,None,None,None,None,None,None,None,None,No,2017-09-07 22:15:25

In [8]:
df = df.drinks.apply(pd.Series)
df

,idDrink,strDrink,strDrinkAlternate,strTags,strVideo,strCategory,strIBA,strAlcoholic,strGlass,strInstructions,...,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strImageSource,strImageAttribution,strCreativeCommonsConfirmed,dateModified
0,17222,A1,None,None,None,Cocktail,None,Alcoholic,Cocktail glass,"Pour all ingredients into a cocktail shaker, m...",...,None,None,None,None,None,None,None,None,No,2017-09-07 21:42:09
1,13501,ABC,None,None,None,Shot,None,Alcoholic,Shot glass,Layered in a shot glass.,...,None,None,None,None,None,None,None,None,No,2016-08-31 19:32:08
2,17225,Ace,None,None,None,Cocktail,None,Alcoholic,Martini Glass,Shake all the ingredients in a cocktail shaker...,...,None,None,None,None,None,None,None,None,No,2017-09-07 22:05:06
3,14610,ACID,None,None,None,Shot,None,Alcoholic,Shot glass,Poor in the 151 first followed by the 101 serv...,...,None,None,None,None,None,None,None,None,No,2016-11-15 11:28:37
4,13938,AT&T,None,None,None,Ordinary Drink,None,Alcoholic,Highball Glass,"Pour Vodka and Gin over ice, add Tonic and Stir",...,None,None,None,None,None,None,None,None,No,2017-04-24 22:00:19
5,17837,Adam,None,"Alcoholic,Holiday",None,Ordinary Drink,None,Alcoholic,Cocktail glass,"In a shaker half-filled with ice cubes, combin...",...,None,None,None,None,None,None,None,None,Yes,2016-09-02 11:29:29
6,17833,A. J.,None,None,None,Ordinary Drink,None,Alcoholic,Cocktail glass,"Shake ingredients with ice, strain into a cock...",...,None,None,None,None,None,None,None,None,Yes,2016-09-02 11:16:58
7,17839,Affair,None,None,None,Ordinary Drink,None,Alcoholic,Highball glass,"Pour schnapps, orange juice, and cranberry jui...",...,None,None,None,None,None,None,None,None,Yes,2016-09-01 10:05:34
8,15266,Avalon,None,None,None,Ordinary Drink,None,Alcoholic,Highball glass,Fill a tall glass with ice. Layer the Finlandi...,...,None,None,None,None,None,None,None,None,No,2017-04-24 22:22:11
9,15106,Apello,None,None,None,Other / Unknown,None,Non alcoholic,Collins Glass,Stirr. Grnish with maraschino cherry.,...,None,None,None,None,None,None,None,None,No,2016-07-18 22:13:35
10,11023,Almeria,None,None,None,Ordinary Drink,None,Alcoholic,Cocktail glass,"In a shaker half-filled with ice cubes, combin...",...,None,None,None,None,None,None,None,None,No,2017-01-02 20:16:21
11,17835,Abilene,None,None,None,Ordinary Drink,None,Alcoholic,Highball glass,Pour all of the ingredients into a highball gl...,...,None,None,None,None,None,None,None,None,Yes,2016-04-29 09:44:25
12,17228,Addison,None,None,None,Cocktail,None,Alcoholic,Martini Glass,Shake together all the ingredients and strain ...,...,None,None,None,None,None,None,None,None,No,2017-09-07 22:38:20
13,17180,Aviation,None,"IBA,Classic",https://www.youtube.com/watch?v=oOHH0GGglyM,Cocktail,Unforgettables,Alcoholic,Cocktail glass,Add all ingredients into cocktail shaker fille...,...,None,None,None,None,None,None,https://www.flickr.com/photos/mstyne/278593630...,Michael Styne https://www.flickr.com/photos/ms...,Yes,2016-11-04 09:55:28
14,11046,Applecar,None,None,None,Ordinary Drink,None,Alcoholic,Cocktail glass,"Shake all ingredients with ice, strain into a ...",...,None,None,None,None,None,None,None,None,No,2017-09-02 23:02:44
15,17840,Affinity,None,None,None,Ordinary Drink,None,Alcoholic,Cocktail glass,"In a mixing glass half-filled with ice cubes, ...",...,None,None,None,None,None,None,None,None,Yes,2017-09-07 21:44:05
16,17836,Acapulco,None,None,None,Ordinary Drink,None,Alcoholic,Old-fashioned glass,Combine and shake all ingredients (except mint...,...,None,None,None,None,None,None,None,None,Yes,2016-09-02 11:26:16
17,11014,Alexander,None,"IBA,Classic,Dairy",https://www.youtube.com/watch?v=qEhRK_v2w2g,Ordinary Drink,Unforgettables,Alcoholic,Cocktail glass,Shake all ingredients with ice and strain cont...,...,None,None,None,None,None,None,https://www.pxfuel.com/en/free-photo-expqp,pxfuel.com,Yes,2016-11-04 09:50:39
18,16419,Avalanche,None,None,None,Shake,None,Alcoholic,Highball glass,"Mix in highball glass over ice, shake well.",...,None,None,None,None,None,None,None,None,No,2016-09-01 09:56:05
19,11021,Allegheny,None,None,None,Ordinary Drink,None,Alcoholic,Cocktail glass,Shake all ingredients (except lemon peel) with...,...,None,None,None,None,None,None,None,None,No,2017-01-02 20:12:14
20,15941,Americano,None,"IBA,Classic",https://www.youtube.com/watch?v=TmeUJ2g3ogM,Ordinary Drink,Unforgettables,Alcoholic,Collins glass,Pour the Campari and vermouth over ice into gl...,...,None,None,None,None,None,None,https://commons.wikimedia.org/wiki/File:Martin...,Author - Cher37 https://commons.wikimedia.org/...,Yes,2016-11-04 09:52:06
21,11020,Algonquin,None,None,None,Ordinary Drink,None,Alcoholic,Cocktail glass,"Combine and shake all ingredients with ice, st...",...,None,None,None,None,None,None,None,None,No,2017-01-02 20:11:13
22,11055,Artillery,None,None,None,Ordinary Drink,None,Alcoholic,Cocktail glass,"Stir all ingredients with ice, strain into a c...",...,None,None,None,None,None,None,None,None,No,2017-04-24 22:02:27
23,12560,Afterglow,None,None,None,Cocktail,None,Non alcoholic,Highball Glass,Mix. Serve over ice.,...,None,None,None,None,None,None,None,None,No,2016-07-18 22:07:32
24,17227,Addington,None,None,None,Cocktail,None,Alcoholic,Cocktail glass,Mix both the vermouth's in a shaker and strain...,...,None,None,None,None,None,None,None,None,No,2017-09-07 22:15:25

In [9]:
df = df.query("strAlcoholic == 'Alcoholic'").copy()
df

,idDrink,strDrink,strDrinkAlternate,strTags,strVideo,strCategory,strIBA,strAlcoholic,strGlass,strInstructions,...,strMeasure10,strMeasure11,strMeasure12,strMeasure13,strMeasure14,strMeasure15,strImageSource,strImageAttribution,strCreativeCommonsConfirmed,dateModified
0,17222,A1,None,None,None,Cocktail,None,Alcoholic,Cocktail glass,"Pour all ingredients into a cocktail shaker, m...",...,None,None,None,None,None,None,None,None,No,2017-09-07 21:42:09
1,13501,ABC,None,None,None,Shot,None,Alcoholic,Shot glass,Layered in a shot glass.,...,None,None,None,None,None,None,None,None,No,2016-08-31 19:32:08
2,17225,Ace,None,None,None,Cocktail,None,Alcoholic,Martini Glass,Shake all the ingredients in a cocktail shaker...,...,None,None,None,None,None,None,None,None,No,2017-09-07 22:05:06
3,14610,ACID,None,None,None,Shot,None,Alcoholic,Shot glass,Poor in the 151 first followed by the 101 serv...,...,None,None,None,None,None,None,None,None,No,2016-11-15 11:28:37
4,13938,AT&T,None,None,None,Ordinary Drink,None,Alcoholic,Highball Glass,"Pour Vodka and Gin over ice, add Tonic and Stir",...,None,None,None,None,None,None,None,None,No,2017-04-24 22:00:19
5,17837,Adam,None,"Alcoholic,Holiday",None,Ordinary Drink,None,Alcoholic,Cocktail glass,"In a shaker half-filled with ice cubes, combin...",...,None,None,None,None,None,None,None,None,Yes,2016-09-02 11:29:29
6,17833,A. J.,None,None,None,Ordinary Drink,None,Alcoholic,Cocktail glass,"Shake ingredients with ice, strain into a cock...",...,None,None,None,None,None,None,None,None,Yes,2016-09-02 11:16:58
7,17839,Affair,None,None,None,Ordinary Drink,None,Alcoholic,Highball glass,"Pour schnapps, orange juice, and cranberry jui...",...,None,None,None,None,None,None,None,None,Yes,2016-09-01 10:05:34
8,15266,Avalon,None,None,None,Ordinary Drink,None,Alcoholic,Highball glass,Fill a tall glass with ice. Layer the Finlandi...,...,None,None,None,None,None,None,None,None,No,2017-04-24 22:22:11
10,11023,Almeria,None,None,None,Ordinary Drink,None,Alcoholic,Cocktail glass,"In a shaker half-filled with ice cubes, combin...",...,None,None,None,None,None,None,None,None,No,2017-01-02 20:16:21
11,17835,Abilene,None,None,None,Ordinary Drink,None,Alcoholic,Highball glass,Pour all of the ingredients into a highball gl...,...,None,None,None,None,None,None,None,None,Yes,2016-04-29 09:44:25
12,17228,Addison,None,None,None,Cocktail,None,Alcoholic,Martini Glass,Shake together all the ingredients and strain ...,...,None,None,None,None,None,None,None,None,No,2017-09-07 22:38:20
13,17180,Aviation,None,"IBA,Classic",https://www.youtube.com/watch?v=oOHH0GGglyM,Cocktail,Unforgettables,Alcoholic,Cocktail glass,Add all ingredients into cocktail shaker fille...,...,None,None,None,None,None,None,https://www.flickr.com/photos/mstyne/278593630...,Michael Styne https://www.flickr.com/photos/ms...,Yes,2016-11-04 09:55:28
14,11046,Applecar,None,None,None,Ordinary Drink,None,Alcoholic,Cocktail glass,"Shake all ingredients with ice, strain into a ...",...,None,None,None,None,None,None,None,None,No,2017-09-02 23:02:44
15,17840,Affinity,None,None,None,Ordinary Drink,None,Alcoholic,Cocktail glass,"In a mixing glass half-filled with ice cubes, ...",...,None,None,None,None,None,None,None,None,Yes,2017-09-07 21:44:05
16,17836,Acapulco,None,None,None,Ordinary Drink,None,Alcoholic,Old-fashioned glass,Combine and shake all ingredients (except mint...,...,None,None,None,None,None,None,None,None,Yes,2016-09-02 11:26:16
17,11014,Alexander,None,"IBA,Classic,Dairy",https://www.youtube.com/watch?v=qEhRK_v2w2g,Ordinary Drink,Unforgettables,Alcoholic,Cocktail glass,Shake all ingredients with ice and strain cont...,...,None,None,None,None,None,None,https://www.pxfuel.com/en/free-photo-expqp,pxfuel.com,Yes,2016-11-04 09:50:39
18,16419,Avalanche,None,None,None,Shake,None,Alcoholic,Highball glass,"Mix in highball glass over ice, shake well.",...,None,None,None,None,None,None,None,None,No,2016-09-01 09:56:05
19,11021,Allegheny,None,None,None,Ordinary Drink,None,Alcoholic,Cocktail glass,Shake all ingredients (except lemon peel) with...,...,None,None,None,None,None,None,None,None,No,2017-01-02 20:12:14
20,15941,Americano,None,"IBA,Classic",https://www.youtube.com/watch?v=TmeUJ2g3ogM,Ordinary Drink,Unforgettables,Alcoholic,Collins glass,Pour the Campari and vermouth over ice into gl...,...,None,None,None,None,None,None,https://commons.wikimedia.org/wiki/File:Martin...,Author - Cher37 https://commons.wikimedia.org/...,Yes,2016-11-04 09:52:06
21,11020,Algonquin,None,None,None,Ordinary Drink,None,Alcoholic,Cocktail glass,"Combine and shake all ingredients with ice, st...",...,None,None,None,None,None,None,None,None,No,2017-01-02 20:11:13
22,11055,Artillery,None,None,None,Ordinary Drink,None,Alcoholic,Cocktail glass,"Stir all ingredients with ice, strain into a c...",...,None,None,None,None,None,None,None,None,No,2017-04-24 22:02:27
24,17227,Addington,None,None,None,Cocktail,None,Alcoholic,Cocktail glass,Mix both the vermouth's in a shaker and strain...,...,None,None,None,None,None,None,None,None,No,2017-09-07 22:15:25

In [10]:
len(df)

23

#### 2.2. Utilizando el request y filtro anterior, es decir, bebidas alcoholicas que comiencen con la letra a, crea una lista con el nombre de los cócteles los cuales tengan la palabra `juice` en alguno de sus ingredientes.

In [11]:
df.columns

Index(['idDrink', 'strDrink', 'strDrinkAlternate', 'strTags', 'strVideo',
       'strCategory', 'strIBA', 'strAlcoholic', 'strGlass', 'strInstructions',
       'strInstructionsES', 'strInstructionsDE', 'strInstructionsFR',
       'strInstructionsIT', 'strInstructionsZH-HANS', 'strInstructionsZH-HANT',
       'strDrinkThumb', 'strIngredient1', 'strIngredient2', 'strIngredient3',
       'strIngredient4', 'strIngredient5', 'strIngredient6', 'strIngredient7',
       'strIngredient8', 'strIngredient9', 'strIngredient10',
       'strIngredient11', 'strIngredient12', 'strIngredient13',
       'strIngredient14', 'strIngredient15', 'strMeasure1', 'strMeasure2',
       'strMeasure3', 'strMeasure4', 'strMeasure5', 'strMeasure6',
       'strMeasure7', 'strMeasure8', 'strMeasure9', 'strMeasure10',
       'strMeasure11', 'strMeasure12', 'strMeasure13', 'strMeasure14',
       'strMeasure15', 'strImageSource', 'strImageAttribution',
       'strCreativeCommonsConfirmed', 'dateModified'],
      dtype='object')

In [16]:
# Con el DataFrame anterior, se filtra un listado de columnas donde están los ingredientes para aplicar una
# función que vaya por cada uno de los registros ("celdas") y compruebe si la palabra "juice" este en alguno
# de estos registros. Como resultado se obtiene una matriz booleana, que se convierte en vector con la función
# any().

lista_columnas = ['strIngredient1', 'strIngredient2', 'strIngredient3',
                  'strIngredient4', 'strIngredient5', 'strIngredient6',
                  'strIngredient7', 'strIngredient8', 'strIngredient9',
                  'strIngredient10', 'strIngredient11', 'strIngredient12',
                  'strIngredient13', 'strIngredient14', 'strIngredient15']

def funcion(x):
    if x is not None:
        if "juice" in x.lower():
            return True
        else:
            return False

# resultado = df[["strDrink"] + lista_columnas][df[lista_columnas].applymap(funcion).any(axis=1)]
resultado = df[["strDrink"] + lista_columnas][df[lista_columnas].map(funcion).any(axis=1)]
resultado

,strDrink,strIngredient1,strIngredient2,strIngredient3,strIngredient4,strIngredient5,strIngredient6,strIngredient7,strIngredient8,strIngredient9,strIngredient10,strIngredient11,strIngredient12,strIngredient13,strIngredient14,strIngredient15
0,A1,Gin,Grand Marnier,Lemon Juice,Grenadine,None,None,None,None,None,None,None,None,None,None,None
5,Adam,Dark rum,Lemon juice,Grenadine,None,None,None,None,None,None,None,None,None,None,None,None
6,A. J.,Applejack,Grapefruit juice,None,None,None,None,None,None,None,None,None,None,None,None,None
7,Affair,Strawberry schnapps,Orange juice,Cranberry juice,Club soda,None,None,None,None,None,None,None,None,None,None,None
8,Avalon,Vodka,Pisang Ambon,Apple juice,Lemon juice,Lemonade,None,None,None,None,None,None,None,None,None,None
11,Abilene,Dark rum,Peach nectar,Orange juice,None,None,None,None,None,None,None,None,None,None,None,None
13,Aviation,Gin,lemon juice,maraschino liqueur,None,None,None,None,None,None,None,None,None,None,None,None
14,Applecar,Applejack,Triple sec,Lemon juice,None,None,None,None,None,None,None,None,None,None,None,None
16,Acapulco,Light rum,Triple sec,Lime juice,Sugar,Egg white,Mint,None,None,None,None,None,None,None,None,None
19,Allegheny,Dry Vermouth,Bourbon,Blackberry brandy,Lemon juice,Lemon peel,None,None,None,None,None,None,None,None,None,None
21,Algonquin,Blended whiskey,Dry Vermouth,Pineapple juice,None,None,None,None,None,None,None,None,None,None,None,None

In [17]:
len(resultado.strDrink)

11

#### 2.3. Versión alternativa conteo resultados sin alcohol recorriendo dataframe

In [18]:
# Versión alternativa recorriendo el dataframe

df=df_original.copy()

lista = list()
for indice, row in df.iterrows():
  bebida = df.drinks[indice].get("strDrink")
  if df.drinks[indice].get("strAlcoholic")=="Alcoholic":
    lista.append(bebida)
  # print(df.drinks[indice].get("strAlcoholic"))
lista

['A1',
 'ABC',
 'Ace',
 'ACID',
 'AT&T',
 'Adam',
 'A. J.',
 'Affair',
 'Avalon',
 'Almeria',
 'Abilene',
 'Addison',
 'Aviation',
 'Applecar',
 'Affinity',
 'Acapulco',
 'Alexander',
 'Avalanche',
 'Allegheny',
 'Americano',
 'Algonquin',
 'Artillery',
 'Addington']

In [19]:
len(lista)

23

*****

## 3. Web Scraping

#### 3.1. Crea un scraper (sin usar selenium) para que capture las primeras 10 citas del siguiente sitio web: `https://quotes.toscrape.com/`.

In [20]:
import requests
from bs4 import BeautifulSoup

result = requests.get("https://quotes.toscrape.com/")

soup = BeautifulSoup(result.content, 'html.parser')

frases_html = soup.find_all('span', {'class': 'text'})
frases_texto = [frase.text for frase in frases_html]

for frase in frases_texto:
    print(frase)

“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”
“It is our choices, Harry, that show what we truly are, far more than our abilities.”
“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”
“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”
“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”
“Try not to become a man of success. Rather become a man of value.”
“It is better to be hated for what you are than to be loved for what you are not.”
“I have not failed. I've just found 10,000 ways that won't work.”
“A woman is like a tea bag; you never know how strong it is until it's in hot water.”
“A day without sunshine is like, you know, night.”

In [22]:
autores_html = soup.find_all('small', {'class': 'author'})
autores_html

[<small class="author" itemprop="author">Albert Einstein</small>,
 <small class="author" itemprop="author">J.K. Rowling</small>,
 <small class="author" itemprop="author">Albert Einstein</small>,
 <small class="author" itemprop="author">Jane Austen</small>,
 <small class="author" itemprop="author">Marilyn Monroe</small>,
 <small class="author" itemprop="author">Albert Einstein</small>,
 <small class="author" itemprop="author">André Gide</small>,
 <small class="author" itemprop="author">Thomas A. Edison</small>,
 <small class="author" itemprop="author">Eleanor Roosevelt</small>,
 <small class="author" itemprop="author">Steve Martin</small>]

In [23]:
autores_texto = [autor.text for autor in autores_html]
autores_texto

['Albert Einstein',
 'J.K. Rowling',
 'Albert Einstein',
 'Jane Austen',
 'Marilyn Monroe',
 'Albert Einstein',
 'André Gide',
 'Thomas A. Edison',
 'Eleanor Roosevelt',
 'Steve Martin']

In [24]:
# Listado de URLs que aparecen en la página https://medium.com/@diego.coder/las-mejores-apis-p%C3%BAblicas-para-practicar-programaci%C3%B3n-a7419ecc968e

import requests
from bs4 import BeautifulSoup

result = requests.get("https://medium.com/@diego.coder/las-mejores-apis-p%C3%BAblicas-para-practicar-programaci%C3%B3n-a7419ecc968e")

soup = BeautifulSoup(result.content, 'html.parser')

enlaces_html = soup.find_all('a', {'class': 'af mt'})
enlaces_html

[<a class="af mt" href="https://unsplash.com/@introspectivedsgn?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank">Erik Mclean</a>,
 <a class="af mt" href="https://unsplash.com/?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank">Unsplash</a>,
 <a class="af mt" href="https://api.chucknorris.io/" rel="noopener ugc nofollow" target="_blank">https://api.chucknorris.io/</a>,
 <a class="af mt" href="https://rickandmortyapi.com/" rel="noopener ugc nofollow" target="_blank">https://rickandmortyapi.com/</a>,
 <a class="af mt" href="https://pokeapi.co/" rel="noopener ugc nofollow" target="_blank">https://pokeapi.co/</a>,
 <a class="af mt" href="https://developer.marvel.com/" rel="noopener ugc nofollow" target="_blank">https://developer.marvel.com/</a>,
 <a class="af mt" href="https://api.nasa.gov/" rel="noopener ugc nofollow" target="_blank">https://api.nasa.gov/</a>,
 <a class="af mt" href="https://openweathermap.org/api" rel="noopener ugc nofollow" target="_blank">https://openweathermap.org/api</a>,
 <a class="af mt" href="https://jsonplaceholder.typicode.com/" rel="noopener ugc nofollow" target="_blank">https://jsonplaceholder.typicode.com/</a>,
 <a class="af mt" href="https://randomuser.me/" rel="noopener ugc nofollow" target="_blank">https://randomuser.me/</a>,
 <a class="af mt" href="https://restcountries.com/" rel="noopener ugc nofollow" target="_blank">https://restcountries.com/</a>,
 <a class="af mt" href="https://www.swapi.tech/" rel="noopener ugc nofollow" target="_blank">https://www.swapi.tech/</a>]

In [26]:
for enlace in enlaces_html[2:]:
  print(enlace.text)

https://api.chucknorris.io/
https://rickandmortyapi.com/
https://pokeapi.co/
https://developer.marvel.com/
https://api.nasa.gov/
https://openweathermap.org/api
https://jsonplaceholder.typicode.com/
https://randomuser.me/
https://restcountries.com/
https://www.swapi.tech/

In [27]:
lista = list()
for enlace in enlaces_html[2:]:
  lista.append(enlace.text)

lista

['https://api.chucknorris.io/',
 'https://rickandmortyapi.com/',
 'https://pokeapi.co/',
 'https://developer.marvel.com/',
 'https://api.nasa.gov/',
 'https://openweathermap.org/api',
 'https://jsonplaceholder.typicode.com/',
 'https://randomuser.me/',
 'https://restcountries.com/',
 'https://www.swapi.tech/']

In [31]:
df_enlaces = pd.DataFrame(lista, columns = ["url"])
df_enlaces

df_enlaces.to_csv("lista_enlaces_APIS.csv")