# Manipulación de datos (3) - Remodelado de datos

*****

Importar Pandas:

In [1]:
import pandas as pd

*****

## 1. Long format vs wide format

Un conjunto de datos puede escribirse en dos formatos diferentes:

- Un formato ancho (wide format) contiene valores que no se repiten en la primera columna.

- Un formato largo (long format) contiene valores que sí se repiten en la primera columna.

<img src="https://drive.google.com/uc?id=1TDBmEqe8J3q8slv5B03S-ZAd4Ua36YUO" width="70%">

Ambos conjuntos de datos contienen exactamente la misma información, pero simplemente se expresan en diferentes formatos.

*****

## 2. De ancho a largo

La función `.melt()` remodela o transforma un DataFrame existente. Cambia la orientación del DataFrame de un formato ancho a uno largo.

**Ejemplo 1**:

In [2]:
df = pd.DataFrame({'Nueva York': [25], 'Paris': [27], 'Londres': [30]})
df

   Nueva York  Paris  Londres
0          25     27       30

In [3]:
df.melt()

     variable  value
0  Nueva York     25
1       Paris     27
2     Londres     30

**Ejemplo 2**:

In [4]:
df = pd.DataFrame({
    'ciudad': ['Nueva York', 'Londres', 'Paris', 'Berlin', 'Amsterdam'],
    'dia_1': [23, 25, 27, 26, 24],
    'dia_2': [22, 21, 25, 26, 23],
    'dia_3': [26, 25, 24, 27, 23],
    'dia_4': [23, 21, 22, 26, 27],
    'dia_5': [27, 26, 27, 24, 28]
})

df

       ciudad  dia_1  dia_2  dia_3  dia_4  dia_5
0  Nueva York     23     22     26     23     27
1     Londres     25     21     25     21     26
2       Paris     27     25     24     22     27
3      Berlin     26     26     27     26     24
4   Amsterdam     24     23     23     27     28

In [5]:
df.melt()

   variable       value
0    ciudad  Nueva York
1    ciudad     Londres
2    ciudad       Paris
3    ciudad      Berlin
4    ciudad   Amsterdam
5     dia_1          23
6     dia_1          25
7     dia_1          27
8     dia_1          26
9     dia_1          24
10    dia_2          22
11    dia_2          21
12    dia_2          25
13    dia_2          26
14    dia_2          23
15    dia_3          26
16    dia_3          25
17    dia_3          24
18    dia_3          27
19    dia_3          23
20    dia_4          23
21    dia_4          21
22    dia_4          22
23    dia_4          26
24    dia_4          27
25    dia_5          27
26    dia_5          26
27    dia_5          27
28    dia_5          24
29    dia_5          28

No era lo que se buscaba, ¿verdad?. Veamos algunos parámetros de la función melt:

- **id_vars**: Permite usar una/s columna/s como identificadores.

In [6]:
df.melt(id_vars=['ciudad'])

        ciudad variable  value
0   Nueva York    dia_1     23
1      Londres    dia_1     25
2        Paris    dia_1     27
3       Berlin    dia_1     26
4    Amsterdam    dia_1     24
5   Nueva York    dia_2     22
6      Londres    dia_2     21
7        Paris    dia_2     25
8       Berlin    dia_2     26
9    Amsterdam    dia_2     23
10  Nueva York    dia_3     26
11     Londres    dia_3     25
12       Paris    dia_3     24
13      Berlin    dia_3     27
14   Amsterdam    dia_3     23
15  Nueva York    dia_4     23
16     Londres    dia_4     21
17       Paris    dia_4     22
18      Berlin    dia_4     26
19   Amsterdam    dia_4     27
20  Nueva York    dia_5     27
21     Londres    dia_5     26
22       Paris    dia_5     27
23      Berlin    dia_5     24
24   Amsterdam    dia_5     28

- **value_vars**: Permite escoger las columnas con las que queramos operar.

In [7]:
df.melt(id_vars=['ciudad'], value_vars=["dia_1", "dia_2"])

       ciudad variable  value
0  Nueva York    dia_1     23
1     Londres    dia_1     25
2       Paris    dia_1     27
3      Berlin    dia_1     26
4   Amsterdam    dia_1     24
5  Nueva York    dia_2     22
6     Londres    dia_2     21
7       Paris    dia_2     25
8      Berlin    dia_2     26
9   Amsterdam    dia_2     23

- **var_name** y **value_name**: Permiten poner un nombre nuestras nuevas columnas.

In [8]:
df.melt(id_vars=['ciudad'], value_vars=["dia_1", "dia_2"], var_name="dia", value_name="temperatura")

       ciudad    dia  temperatura
0  Nueva York  dia_1           23
1     Londres  dia_1           25
2       Paris  dia_1           27
3      Berlin  dia_1           26
4   Amsterdam  dia_1           24
5  Nueva York  dia_2           22
6     Londres  dia_2           21
7       Paris  dia_2           25
8      Berlin  dia_2           26
9   Amsterdam  dia_2           23

******

## 3. De largo a ancho.

La función `.pivot()` remodela o transforma un DataFrame existente. Cambia la orientación del DataFrame de un formato largo a ancho.

Ejemplo:

In [9]:
df = pd.read_csv("https://github.com/JorgeRincon-PY/datasets/raw/main/stock%20prices.csv")
df

       symbol        date      open      high       low     close    volume
0         AAL  2014-01-02   25.0700   25.8200   25.0600   25.3600   8998943
1        AAPL  2014-01-02   79.3828   79.5756   78.8601   79.0185  58791957
2         AAP  2014-01-02  110.3600  111.8800  109.2900  109.7400    542711
3        ABBV  2014-01-02   52.1200   52.3300   51.5200   51.9800   4569061
4         ABC  2014-01-02   70.1100   70.2300   69.4800   69.8900   1148391
...       ...         ...       ...       ...       ...       ...       ...
497467    XYL  2017-12-29   68.5300   68.8000   67.9200   68.2000   1046677
497468    YUM  2017-12-29   82.6400   82.7100   81.5900   81.6100   1347613
497469    ZBH  2017-12-29  121.7500  121.9500  120.6200  120.6700   1023624
497470   ZION  2017-12-29   51.2800   51.5500   50.8100   50.8300   1261916
497471    ZTS  2017-12-29   72.5500   72.7600   72.0400   72.0400   1704122

[497472 rows x 7 columns]

In [10]:
len(df)

497472

Parámetros:

- **index**: Variable que queremos utilizar para que sus valores únicos sean las filas.
- **columns**: Variable que queremos utilizar para que sus valores únicos sean las columnas.
- **values**: Variable que nos indica los valores del nuevo conjunto de datos.

In [11]:
df.pivot(index='symbol', columns='date', values='close')

date,2014-01-02,2014-01-03,2014-01-06,2014-01-07,2014-01-08,2014-01-09,2014-01-10,2014-01-13,2014-01-14,2014-01-15,...,2017-12-15,2017-12-18,2017-12-19,2017-12-20,2017-12-21,2017-12-22,2017-12-26,2017-12-27,2017-12-28,2017-12-29
symbol,,,,,,,,,,,,,,,,,,,,,
A,56.2100,56.9200,56.6400,57.4500,58.3900,58.4100,58.9300,58.9300,59.8800,60.3400,...,67.61,67.66,67.75,67.40,67.52,67.35,67.25,67.30,67.45,66.97
AAL,25.3600,26.5400,27.0300,26.9050,27.6300,29.4200,29.3500,28.6500,28.8700,28.8400,...,51.06,51.49,51.44,51.92,52.79,52.59,52.85,52.40,52.46,52.03
AAP,109.7400,112.8800,111.8000,113.1800,112.3000,113.5500,115.6400,114.2900,117.6000,117.4700,...,100.70,102.71,99.73,98.59,100.13,100.55,101.96,99.77,99.71,99.69
AAPL,79.0185,77.2828,77.7042,77.1481,77.6371,76.6455,76.1342,76.5328,78.0556,79.6228,...,173.97,176.42,174.54,174.35,175.01,175.01,170.57,170.60,171.08,169.23
ABBV,51.9800,52.3000,50.3900,50.4900,50.3600,51.2200,50.9000,49.8300,50.6000,50.1100,...,97.45,98.19,97.92,97.41,97.91,98.21,97.75,98.09,97.79,96.71
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
XYL,34.1600,34.4700,34.4100,34.5100,34.4900,34.6300,34.9100,35.0200,35.5800,36.3700,...,67.57,67.90,67.86,67.82,67.75,67.58,67.50,68.23,68.25,68.20
YUM,75.0900,75.5600,75.5000,76.5600,76.5300,75.0500,75.0200,73.4100,73.2300,73.1700,...,82.30,83.11,82.86,82.13,82.50,82.40,82.19,82.40,82.67,81.61
ZBH,92.2400,92.6400,93.2400,95.1000,97.4300,96.4700,96.6800,95.6500,96.8000,97.7100,...,115.24,114.43,121.38,121.18,119.95,120.12,119.96,120.14,121.75,120.67
ZION,29.6500,29.8600,29.6500,29.7400,30.0000,30.2200,30.0600,29.6500,29.6700,30.1800,...,50.01,50.98,50.89,50.73,51.46,51.33,50.86,50.71,51.34,50.83
ZTS,32.3600,32.0500,31.9800,32.1000,31.7400,31.9600,32.5400,31.7800,31.8500,31.8100,...,71.96,72.63,72.80,72.71,72.28,71.99,72.34,72.45,72.39,72.04

No es `.pivot_table()`.

****