# Manipulación de datos (1) - Ajuste de tipos de variables

*****

Importar NumPy y Pandas:

In [1]:
import pandas as pd
import numpy as np

Configurar opciones de Pandas:

In [2]:
pd.options.display.max_columns = None #Para no tener limites de visualización
pd.options.display.precision = 5 #Para no tener notación cientifica

******

####  Conjunto de datos:

Crímenes en LA en 2022. Se puede encontrar más información [aquí](https://data.lacity.org/Public-Safety/Crime-Data-from-2020-to-Present/2nrs-mtv8). Yo he filtrado un segmento del conjunto de datos (solo 2022) para que sea posible subir el conjunto de datos a Github:

In [3]:
df = pd.read_csv("https://github.com/JorgeRincon-PY/datasets/raw/main/Crime_LA_2022-Present.csv.zip") #Hey! Es un zip!
df.head(5)

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,Mocodes,Vict Age,Vict Sex,Vict Descent,Premis Cd,Premis Desc,Weapon Used Cd,Weapon Desc,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,220216262,09/08/2022 12:00:00 AM,2022-09-08,1445,2,Rampart,275,2,624,BATTERY - SIMPLE ASSAULT,1202 0913 0361 0416,66,F,H,121.0,YARD (RESIDENTIAL/BUSINESS),500.0,UNKNOWN WEAPON/OTHER WEAPON,AO,Adult Other,624.0,NaN,NaN,NaN,1000 S BURLINGTON AV,NaN,34.0502,-118.2765
1,221809626,04/23/2022 12:00:00 AM,2022-04-22,2100,18,Southeast,1862,1,510,VEHICLE - STOLEN,NaN,0,NaN,NaN,101.0,STREET,NaN,NaN,IC,Invest Cont,510.0,NaN,NaN,NaN,SAN PEDRO ST,120TH ST,33.9237,-118.2696
2,221711121,07/10/2022 12:00:00 AM,2022-07-10,200,17,Devonshire,1781,1,230,"ASSAULT WITH DEADLY WEAPON, AGGRAVATED ASSAULT",1206 1822 0416 0408 0400,36,F,H,121.0,YARD (RESIDENTIAL/BUSINESS),400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",IC,Invest Cont,230.0,NaN,NaN,NaN,8800 OSO AV,NaN,34.2299,-118.5754
3,220805283,01/24/2022 12:00:00 AM,2022-01-22,1445,8,West LA,855,1,341,"THEFT-GRAND ($950.01 & OVER)EXCPT,GUNS,FOWL,LI...",0344 0377,31,F,K,101.0,STREET,NaN,NaN,IC,Invest Cont,341.0,NaN,NaN,NaN,1600 CAMDEN AV,NaN,34.0501,-118.4439
4,221821212,11/27/2022 12:00:00 AM,2022-11-27,1635,18,Southeast,1826,1,210,ROBBERY,0337 0342 0344 1822,36,M,H,102.0,SIDEWALK,400.0,"STRONG-ARM (HANDS, FIST, FEET OR BODILY FORCE)",IC,Invest Cont,210.0,NaN,NaN,NaN,91ST,COMPTON,33.9543,-118.2475

*****

####  Duplicados:

Una buena práctica es observar si el conjunto de datos tiene duplicados:

In [4]:
print("Duplicados en el conjunto de datos: ", df.duplicated().sum())

Duplicados en el conjunto de datos:  0

Si el conjunto de datos tuviera duplicados se puede aplicar la función `.drop_duplicates()`.

*****

####  Columnas redundantes, renombre y nulos:

También es una buena practica eliminar las columnas redundantes, como una columna que es siempre constante o columnas que significan lo mismo. Así podemos reducir el uso de la memoria para poder trabajar más rápido con el conjunto de datos:

In [5]:
df.info(memory_usage=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 189252 entries, 0 to 189251
Data columns (total 28 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   DR_NO           189252 non-null  int64
 1   Date Rptd       189252 non-null  object
 2   DATE OCC        189252 non-null  object
 3   TIME OCC        189252 non-null  int64
 4   AREA            189252 non-null  int64
 5   AREA NAME       189252 non-null  object
 6   Rpt Dist No     189252 non-null  int64
 7   Part 1-2        189252 non-null  int64
 8   Crm Cd          189252 non-null  int64
 9   Crm Cd Desc     189252 non-null  object
 10  Mocodes         163394 non-null  object
 11  Vict Age        189252 non-null  int64
 12  Vict Sex        164834 non-null  object
 13  Vict Descent    164836 non-null  object
 14  Premis Cd       189249 non-null  float64
 15  Premis Desc     189132 non-null  object
 16  Weapon Used Cd  62866 non-null   float64
 17  Weapon Desc     62866 non-null   object
 18  Status          189252 non-null  object
 19  Status Desc     189252 non-null  object
 20  Crm Cd 1        189249 non-null  float64
 21  Crm Cd 2        12764 non-null   float64
 22  Crm Cd 3        429 non-null     float64
 23  Crm Cd 4        11 non-null      float64
 24  LOCATION        189252 non-null  object
 25  Cross Street    28003 non-null   object
 26  LAT             189252 non-null  float64
 27  LON             189252 non-null  float64
dtypes: float64(8), int64(7), object(13)
memory usage: 40.4+ MB

Finalmente se decide que estas son las columnas que interesan. Observar el uso de la memoria:

In [6]:
cols = ["DR_NO", "Date Rptd", "DATE OCC", "TIME OCC", "AREA",
        "Crm Cd", "Vict Age", "Vict Sex", "Vict Descent", "Premis Cd"]

df[cols].info(memory_usage=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 189252 entries, 0 to 189251
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   DR_NO         189252 non-null  int64
 1   Date Rptd     189252 non-null  object
 2   DATE OCC      189252 non-null  object
 3   TIME OCC      189252 non-null  int64
 4   AREA          189252 non-null  int64
 5   Crm Cd        189252 non-null  int64
 6   Vict Age      189252 non-null  int64
 7   Vict Sex      164834 non-null  object
 8   Vict Descent  164836 non-null  object
 9   Premis Cd     189249 non-null  float64
dtypes: float64(1), int64(5), object(4)
memory usage: 14.4+ MB

Nuevo conjunto de datos:

In [7]:
df = df[cols].copy()
df

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,Crm Cd,Vict Age,Vict Sex,Vict Descent,Premis Cd
0,220216262,09/08/2022 12:00:00 AM,2022-09-08,1445,2,624,66,F,H,121.0
1,221809626,04/23/2022 12:00:00 AM,2022-04-22,2100,18,510,0,NaN,NaN,101.0
2,221711121,07/10/2022 12:00:00 AM,2022-07-10,200,17,230,36,F,H,121.0
3,220805283,01/24/2022 12:00:00 AM,2022-01-22,1445,8,341,31,F,K,101.0
4,221821212,11/27/2022 12:00:00 AM,2022-11-27,1635,18,210,36,M,H,102.0
...,...,...,...,...,...,...,...,...,...,...
189247,220606765,02/28/2022 12:00:00 AM,2022-02-26,200,6,341,48,F,L,735.0
189248,221701259,12/13/2022 12:00:00 AM,2022-12-13,800,17,331,30,F,W,101.0
189249,221218212,08/23/2022 12:00:00 AM,2022-08-22,700,12,510,0,NaN,NaN,101.0
189250,220110720,04/20/2022 12:00:00 AM,2022-04-20,1645,1,330,37,F,H,101.0
189251,220121575,09/27/2022 12:00:00 AM,2022-09-24,1001,1,331,51,F,O,108.0

****

####  Nulos:

Es necesario buscar nulos para tener una idea de lo que ocurre y poder tratar a esas columnas más adelante:

In [8]:
df.isnull().sum()

DR_NO               0
Date Rptd           0
DATE OCC            0
TIME OCC            0
AREA                0
Crm Cd              0
Vict Age            0
Vict Sex        24418
Vict Descent    24416
Premis Cd           3
dtype: int64

****

#### Personalización del nombre:

Personalizar el nombre de las variables puede hacer más comodo la manipulación, sobretodo si las columnas originales tenian espacios:

In [9]:
df.columns = ["id", "fecha_informe", "fecha_crimen",
              "hora_crimen", "area", "codigo_delito",
              "edad_vict", "genero_vict",
              "desc_vict", "tipo_lugar"]

***

***

## 1. Cambiar tipos de variables

Ya podemos empezar a observar los tipos de variables:

- La lectura por defecto del conjunto de datos es erronea, debemos modificar los campos:

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 189252 entries, 0 to 189251
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   id             189252 non-null  int64
 1   fecha_informe  189252 non-null  object
 2   fecha_crimen   189252 non-null  object
 3   hora_crimen    189252 non-null  int64
 4   area           189252 non-null  int64
 5   codigo_delito  189252 non-null  int64
 6   edad_vict      189252 non-null  int64
 7   genero_vict    164834 non-null  object
 8   desc_vict      164836 non-null  object
 9   tipo_lugar     189249 non-null  float64
dtypes: float64(1), int64(5), object(4)
memory usage: 14.4+ MB

*****

### 1.1. Observar los campos que son fecha:

- [Cheatsheet para los formatos de fecha](https://strftime.org/)

Pandas reconoce por defecto que son objetos/int, tendremos que indicarle que se equivoca:

In [10]:
df["fecha_informe"] = pd.to_datetime(df["fecha_informe"], format='%m/%d/%Y %I:%M:%S %p')

df["fecha_crimen"] = pd.to_datetime(df["fecha_crimen"], format='%Y-%m-%d')

In [11]:
bdf

,id,fecha_informe,fecha_crimen,hora_crimen,area,codigo_delito,edad_vict,genero_vict,desc_vict,tipo_lugar
0,220216262,2022-09-08,2022-09-08,1445,2,624,66,F,H,121.0
1,221809626,2022-04-23,2022-04-22,2100,18,510,0,NaN,NaN,101.0
2,221711121,2022-07-10,2022-07-10,200,17,230,36,F,H,121.0
3,220805283,2022-01-24,2022-01-22,1445,8,341,31,F,K,101.0
4,221821212,2022-11-27,2022-11-27,1635,18,210,36,M,H,102.0
...,...,...,...,...,...,...,...,...,...,...
189247,220606765,2022-02-28,2022-02-26,200,6,341,48,F,L,735.0
189248,221701259,2022-12-13,2022-12-13,800,17,331,30,F,W,101.0
189249,221218212,2022-08-23,2022-08-22,700,12,510,0,NaN,NaN,101.0
189250,220110720,2022-04-20,2022-04-20,1645,1,330,37,F,H,101.0
189251,220121575,2022-09-27,2022-09-24,1001,1,331,51,F,O,108.0

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 189252 entries, 0 to 189251
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   id             189252 non-null  int64
 1   fecha_informe  189252 non-null  datetime64[ns]
 2   fecha_crimen   189252 non-null  datetime64[ns]
 3   hora_crimen    189252 non-null  int64
 4   area           189252 non-null  int64
 5   codigo_delito  189252 non-null  int64
 6   edad_vict      189252 non-null  int64
 7   genero_vict    164834 non-null  object
 8   desc_vict      164836 non-null  object
 9   tipo_lugar     189249 non-null  float64
dtypes: datetime64[ns](2), float64(1), int64(5), object(2)
memory usage: 14.4+ MB

In [13]:
# Rellena con ceros a la izquierda los valores que tienen menos de 4 dígitos
df["hora_crimen"] = df["hora_crimen"].astype(str).str.zfill(4)

df["hora_crimen"] = pd.to_datetime(df["hora_crimen"], format='%H%M')

df["hora_crimen"] = df["hora_crimen"] - pd.Timestamp("1900-01-01")

df

,id,fecha_informe,fecha_crimen,hora_crimen,area,codigo_delito,edad_vict,genero_vict,desc_vict,tipo_lugar
0,220216262,2022-09-08,2022-09-08,0 days 14:45:00,2,624,66,F,H,121.0
1,221809626,2022-04-23,2022-04-22,0 days 21:00:00,18,510,0,NaN,NaN,101.0
2,221711121,2022-07-10,2022-07-10,0 days 02:00:00,17,230,36,F,H,121.0
3,220805283,2022-01-24,2022-01-22,0 days 14:45:00,8,341,31,F,K,101.0
4,221821212,2022-11-27,2022-11-27,0 days 16:35:00,18,210,36,M,H,102.0
...,...,...,...,...,...,...,...,...,...,...
189247,220606765,2022-02-28,2022-02-26,0 days 02:00:00,6,341,48,F,L,735.0
189248,221701259,2022-12-13,2022-12-13,0 days 08:00:00,17,331,30,F,W,101.0
189249,221218212,2022-08-23,2022-08-22,0 days 07:00:00,12,510,0,NaN,NaN,101.0
189250,220110720,2022-04-20,2022-04-20,0 days 16:45:00,1,330,37,F,H,101.0
189251,220121575,2022-09-27,2022-09-24,0 days 10:01:00,1,331,51,F,O,108.0

In [14]:
df["fecha_hora_crimen"] = df["fecha_crimen"] + df["hora_crimen"]

df.drop(columns=["fecha_crimen", "hora_crimen"], inplace=True)

In [15]:
df

,id,fecha_informe,area,codigo_delito,edad_vict,genero_vict,desc_vict,tipo_lugar,fecha_hora_crimen
0,220216262,2022-09-08,2,624,66,F,H,121.0,2022-09-08 14:45:00
1,221809626,2022-04-23,18,510,0,NaN,NaN,101.0,2022-04-22 21:00:00
2,221711121,2022-07-10,17,230,36,F,H,121.0,2022-07-10 02:00:00
3,220805283,2022-01-24,8,341,31,F,K,101.0,2022-01-22 14:45:00
4,221821212,2022-11-27,18,210,36,M,H,102.0,2022-11-27 16:35:00
...,...,...,...,...,...,...,...,...,...
189247,220606765,2022-02-28,6,341,48,F,L,735.0,2022-02-26 02:00:00
189248,221701259,2022-12-13,17,331,30,F,W,101.0,2022-12-13 08:00:00
189249,221218212,2022-08-23,12,510,0,NaN,NaN,101.0,2022-08-22 07:00:00
189250,220110720,2022-04-20,1,330,37,F,H,101.0,2022-04-20 16:45:00
189251,220121575,2022-09-27,1,331,51,F,O,108.0,2022-09-24 10:01:00

Se puede ver que la conversión ha tenido éxito:

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 189252 entries, 0 to 189251
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 189252 non-null  int64
 1   fecha_informe      189252 non-null  datetime64[ns]
 2   area               189252 non-null  int64
 3   codigo_delito      189252 non-null  int64
 4   edad_vict          189252 non-null  int64
 5   genero_vict        164834 non-null  object
 6   desc_vict          164836 non-null  object
 7   tipo_lugar         189249 non-null  float64
 8   fecha_hora_crimen  189252 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int64(4), object(2)
memory usage: 13.0+ MB

*****

### 1.2. Observar los campos que son enteros:

No es necesario que Pandas use int.64, se puede cambiar:

In [ ]:
df.select_dtypes(int).describe()

                id          area  codigo_delito     edad_vict
count  1.89252e+05  189252.00000   189252.00000  189252.00000
mean   2.21260e+08      10.60172      491.96170      29.96156
std    1.58135e+06       6.14905      204.82133      21.58996
min    2.20300e+03       1.00000      110.00000      -1.00000
25%    2.20517e+08       5.00000      331.00000      13.00000
50%    2.21111e+08      11.00000      440.00000      31.00000
75%    2.21611e+08      16.00000      626.00000      45.00000
max    2.32107e+08      21.00000      956.00000      99.00000

Elegir el int que más interese:

In [17]:
print(np.iinfo(np.int8))
print(np.iinfo(np.int16))
print(np.iinfo(np.int32))
print(np.iinfo(np.int64))

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

Realizar la modificación con `astype()`:

In [18]:
df = df.astype({"id": np.int32,
                "area": np.int16,
                "codigo_delito": np.int16,
                "edad_vict": np.int8})

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 189252 entries, 0 to 189251
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 189252 non-null  int32
 1   fecha_informe      189252 non-null  datetime64[ns]
 2   area               189252 non-null  int16
 3   codigo_delito      189252 non-null  int16
 4   edad_vict          189252 non-null  int8
 5   genero_vict        164834 non-null  object
 6   desc_vict          164836 non-null  object
 7   tipo_lugar         189249 non-null  float64
 8   fecha_hora_crimen  189252 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(1), int16(2), int32(1), int8(1), object(2)
memory usage: 8.8+ MB

*****

### 1.3. Observar los campos que son decimales:

Es un falso decimal, realmente se trata de un entero. Pandas ha realizado esto debido a que tiene nulos (`np.nan`).

In [20]:
df.select_dtypes(float).describe()

         tipo_lugar
count  189249.00000
mean      313.55324
std       218.71622
min       101.00000
25%       102.00000
50%       210.00000
75%       501.00000
max       971.00000

Elegir el float que más nos interese:

In [ ]:
print(np.finfo(np.float16))
print(np.finfo(np.float32))
print(np.finfo(np.float64))

Machine parameters for float16
---------------------------------------------------------------
precision =   3   resolution = 1.00040e-03
machep =    -10   eps =        9.76562e-04
negep =     -11   epsneg =     4.88281e-04
minexp =    -14   tiny =       6.10352e-05
maxexp =     16   max =        6.55040e+04
nexp =        5   min =        -max
smallest_normal = 6.10352e-05   smallest_subnormal = 5.96046e-08
---------------------------------------------------------------

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
smallest_normal = 1.1754944e-38   smallest_subnormal = 1.4012985e-45
---------------------------------------------------------------

Machine parameters for float64
---------------------------------------------------------------
precision =  15   resolution = 1.0000000000000001e-15
machep =    -52   eps =        2.2204460492503131e-16
negep =     -53   epsneg =     1.1102230246251565e-16
minexp =  -1022   tiny =       2.2250738585072014e-308
maxexp =   1024   max =        1.7976931348623157e+308
nexp =       11   min =        -max
smallest_normal = 2.2250738585072014e-308   smallest_subnormal = 4.9406564584124654e-324
---------------------------------------------------------------

Una de las opciones es rellenar con un 0 los nulos y convertir la variable a un int:

In [21]:
df["tipo_lugar"] = df["tipo_lugar"].fillna(0).astype(np.int16)

*****

### 1.4. Observar los campos que son objectos:

Hay que prestar mucha atención a estos campos:

In [23]:
df.select_dtypes(object).describe()

       genero_vict desc_vict
count       164834    164836
unique           4        19
top              M         H
freq         77152     58867

Parece bastante raro que haya 4 categorías en el genero por lo que podemos echar un vistazo:

In [24]:
df["genero_vict"].value_counts()

genero_vict
M    77152
F    71753
X    15907
H       22
Name: count, dtype: int64

"X" representa "Desconocido" y "H" representa "M" (me lo he inventado, esto se tiene que discutir con la parte de negocio siempre) por lo que aplicamos los cambios:

In [25]:
df["genero_vict"] = df["genero_vict"].fillna("X").str.replace("H", "M")

Se puede echar un vistazo a la variable`desc_vict`:

In [26]:
df.desc_vict.value_counts(dropna=False, normalize=True).nsmallest() #nlargest()

desc_vict
G    0.00006
S    0.00006
L    0.00007
D    0.00011
U    0.00022
Name: proportion, dtype: float64

Una vez hecho esto, se toma ventaja de una funcionalidad que tiene Pandas llamada "categories":

In [ ]:
df = df.astype({"desc_vict": 'category',
                "genero_vict": 'category'})

*****

#### Finalmente -> 40 MB a 5 MB

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 189252 entries, 0 to 189251
Data columns (total 10 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   id             189252 non-null  int32
 1   fecha_informe  189252 non-null  datetime64[ns]
 2   fecha_crimen   189252 non-null  datetime64[ns]
 3   hora_crimen    189252 non-null  object
 4   area           189252 non-null  int16
 5   codigo_delito  189252 non-null  int16
 6   edad_vict      189252 non-null  int8
 7   genero_vict    189252 non-null  category
 8   desc_vict      164836 non-null  category
 9   tipo_lugar     189252 non-null  int16
dtypes: category(2), datetime64[ns](2), int16(3), int32(1), int8(1), object(1)
memory usage: 6.7+ MB

In [27]:
df.head(10)

,id,fecha_informe,area,codigo_delito,edad_vict,genero_vict,desc_vict,tipo_lugar,fecha_hora_crimen
0,220216262,2022-09-08,2,624,66,F,H,121,2022-09-08 14:45:00
1,221809626,2022-04-23,18,510,0,X,NaN,101,2022-04-22 21:00:00
2,221711121,2022-07-10,17,230,36,F,H,121,2022-07-10 02:00:00
3,220805283,2022-01-24,8,341,31,F,K,101,2022-01-22 14:45:00
4,221821212,2022-11-27,18,210,36,M,H,102,2022-11-27 16:35:00
5,220816350,2022-11-02,8,624,61,F,O,502,2022-11-02 11:30:00
6,220414197,2022-10-11,4,310,0,X,X,203,2022-10-11 21:00:00
7,221114943,2022-10-10,11,740,24,F,O,101,2022-10-08 20:35:00
8,221508072,2022-04-10,15,740,41,M,W,101,2022-04-10 06:50:00
9,222016907,2022-11-03,20,331,50,F,H,101,2022-11-02 18:00:00

*****

*****

## 2. Importante al guardar

Esto es una demonstración de lo que ocurre cuando se guarda un archivo CSV vs Parquet para su posterior análisis:

*Parquet*:

In [ ]:
df = pd.read_parquet("https://github.com/JorgeRincon-PY/datasets/raw/main/Crime_LA_2022.parquet")
df.info() #En parquet se guardan los tipos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 189252 entries, 0 to 189251
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 189252 non-null  int32
 1   fecha_informe      189252 non-null  datetime64[ns]
 2   area               189252 non-null  int16
 3   codigo_delito      189252 non-null  int16
 4   edad_vict          189252 non-null  int8
 5   genero_vict        189252 non-null  category
 6   desc_vict          164836 non-null  category
 7   tipo_lugar         189252 non-null  int16
 8   fecha_hora_crimen  189252 non-null  datetime64[ns]
dtypes: category(2), datetime64[ns](2), int16(3), int32(1), int8(1)
memory usage: 5.2 MB

*CSV*:

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/JorgeRincon-PY/datasets/main/Crime_LA_2022.csv")
df.info() #En CSV no se guardan los tipos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 189252 entries, 0 to 189251
Data columns (total 10 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         189252 non-null  int64
 1   id                 189252 non-null  int64
 2   fecha_informe      189252 non-null  object
 3   area               189252 non-null  int64
 4   codigo_delito      189252 non-null  int64
 5   edad_vict          189252 non-null  int64
 6   genero_vict        189252 non-null  object
 7   desc_vict          164836 non-null  object
 8   tipo_lugar         189252 non-null  int64
 9   fecha_hora_crimen  189252 non-null  object
dtypes: int64(6), object(4)
memory usage: 14.4+ MB

Cabe destacar que se pueden convertir los tipos automaticamente, sin embargo, Pandas no lo hace bien:

In [ ]:
df.convert_dtypes().dtypes

Unnamed: 0            Int64
id                    Int64
fecha_informe        string
area                  Int64
codigo_delito         Int64
edad_vict             Int64
genero_vict          string
desc_vict            string
tipo_lugar            Int64
fecha_hora_crimen    string
dtype: object

****

****