In [22]:
!pip install selenium
!apt-get update # to update ubuntu to correctly run apt install
!apt install chromium-chromedriver

Requirement already satisfied: selenium in /usr/local/lib/python3.10/dist-packages (4.24.0)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.10/dist-packages (from urllib3[socks]<3,>=1.26->selenium) (2.0.7)
Requirement already satisfied: trio~=0.17 in /usr/local/lib/python3.10/dist-packages (from selenium) (0.26.2)
Requirement already satisfied: trio-websocket~=0.9 in /usr/local/lib/python3.10/dist-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in /usr/local/lib/python3.10/dist-packages (from selenium) (2024.8.30)
Requirement already satisfied: typing_extensions~=4.9 in /usr/local/lib/python3.10/dist-packages (from selenium) (4.12.2)
Requirement already satisfied: websocket-client~=1.8 in /usr/local/lib/python3.10/dist-packages (from selenium) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (24.2.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (3.8)
Requirement already satisfied: outcome in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (1.3.1)
Requirement already satisfied: exceptiongroup in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (1.2.2)
Requirement already satisfied: wsproto>=0.14 in /usr/local/lib/python3.10/dist-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.10/dist-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in /usr/local/lib/python3.10/dist-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:3 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,626 B]
Hit:4 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Get:6 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Ign:7 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:8 https://r2u.stat.illinois.edu/ubuntu jammy Release
Hit:10 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:12 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Fetched 261 kB in 2s (128 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
chromium-chromedriver is already the newest version (1:85.0.4183.83-0ubuntu2.22.04.1).
0 upgraded, 0 newly installed, 0 to remove and 55 not upgraded.

In [23]:
import sys
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')

In [24]:
from selenium import webdriver
# from selenium.webdriver.chrome.service import Service

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--window-size=2050,2050")
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')

# service = Service(executable_path=r'/usr/bin/chromedriver')

driver = webdriver.Chrome(options=chrome_options)

In [25]:
# wd.get("https://stackoverflow.com/questions/51046454/how-can-we-use-selenium-webdriver-in-colab-research-google-com")

driver.get("https://books.toscrape.com/")
driver.page_source

'<html lang="en-us" class="no-js"><!--<![endif]--><head>\n        <title>\n    All products | Books to Scrape - Sandbox\n</title>\n\n        <meta http-equiv="content-type" content="text/html; charset=UTF-8">\n        <meta name="created" content="24th Jun 2016 09:29">\n        <meta name="description" content="">\n        <meta name="viewport" content="width=device-width">\n        <meta name="robots" content="NOARCHIVE,NOCACHE">\n\n        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->\n        <!--[if lt IE 9]>\n        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>\n        <![endif]-->\n\n        \n            <link rel="shortcut icon" href="static/oscar/favicon.ico">\n        \n\n        \n        \n    \n    \n        <link rel="stylesheet" type="text/css" href="static/oscar/css/styles.css">\n    \n    <link rel="stylesheet" href="static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css">\n    <link rel="stylesheet" type="text/css" href="static/oscar/css/datetimepicker.css">\n\n\n        \n        \n\n        \n\n        \n            \n            \n\n        \n    </head>\n\n    <body id="default" class="default">\n        \n        \n    \n    \n    <header class="header container-fluid">\n        <div class="page_inner">\n            <div class="row">\n                <div class="col-sm-8 h1"><a href="index.html">Books to Scrape</a><small> We love being scraped!</small>\n</div>\n\n                \n            </div>\n        </div>\n    </header>\n\n    \n    \n<div class="container-fluid page">\n    <div class="page_inner">\n        \n    <ul class="breadcrumb">\n        <li>\n            <a href="index.html">Home</a>\n        </li>\n        <li class="active">All products</li>\n    </ul>\n\n        <div class="row">\n\n            <aside class="sidebar col-sm-4 col-md-3">\n                \n                <div id="promotions_left">\n                    \n                </div>\n                \n    \n    \n        \n        <div class="side_categories">\n            <ul class="nav nav-list">\n                \n                    <li>\n                        <a href="catalogue/category/books_1/index.html">\n                            \n                                Books\n                            \n                        </a>\n\n                        <ul>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/travel_2/index.html">\n                            \n                                Travel\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/mystery_3/index.html">\n                            \n                                Mystery\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/historical-fiction_4/index.html">\n                            \n                                Historical Fiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/sequential-art_5/index.html">\n                            \n                                Sequential Art\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/classics_6/index.html">\n                            \n                                Classics\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/philosophy_7/index.html">\n                            \n                                Philosophy\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/romance_8/index.html">\n                            \n                                Romance\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/womens-fiction_9/index.html">\n                            \n                                Womens Fiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/fiction_10/index.html">\n                            \n                                Fiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/childrens_11/index.html">\n                            \n                                Childrens\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/religion_12/index.html">\n                            \n                                Religion\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/nonfiction_13/index.html">\n                            \n                                Nonfiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/music_14/index.html">\n                            \n                                Music\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/default_15/index.html">\n                            \n                                Default\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/science-fiction_16/index.html">\n                            \n                                Science Fiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/sports-and-games_17/index.html">\n                            \n                                Sports and Games\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/add-a-comment_18/index.html">\n                            \n                                Add a comment\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/fantasy_19/index.html">\n                            \n                                Fantasy\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/new-adult_20/index.html">\n                            \n                                New Adult\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/young-adult_21/index.html">\n                            \n                                Young Adult\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/science_22/index.html">\n                            \n                                Science\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/poetry_23/index.html">\n                            \n                                Poetry\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/paranormal_24/index.html">\n                            \n                                Paranormal\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/art_25/index.html">\n                            \n                                Art\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/psychology_26/index.html">\n                            \n                                Psychology\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/autobiography_27/index.html">\n                            \n                                Autobiography\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/parenting_28/index.html">\n                            \n                                Parenting\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/adult-fiction_29/index.html">\n                            \n                                Adult Fiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/humor_30/index.html">\n                            \n                                Humor\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/horror_31/index.html">\n                            \n                                Horror\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/history_32/index.html">\n                            \n                                History\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/food-and-drink_33/index.html">\n                            \n                                Food and Drink\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/christian-fiction_34/index.html">\n                            \n                                Christian Fiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/business_35/index.html">\n                            \n                                Business\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/biography_36/index.html">\n                            \n                                Biography\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/thriller_37/index.html">\n                            \n                                Thriller\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/contemporary_38/index.html">\n                            \n                                Contemporary\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/spirituality_39/index.html">\n                            \n                                Spirituality\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/academic_40/index.html">\n                            \n                                Academic\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/self-help_41/index.html">\n                            \n                                Self Help\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/historical_42/index.html">\n                            \n                                Historical\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/christian_43/index.html">\n                            \n                                Christian\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/suspense_44/index.html">\n                            \n                                Suspense\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/short-stories_45/index.html">\n                            \n                                Short Stories\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/novels_46/index.html">\n                            \n                                Novels\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/health_47/index.html">\n                            \n                                Health\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/politics_48/index.html">\n                            \n                                Politics\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/cultural_49/index.html">\n                            \n                                Cultural\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/erotica_50/index.html">\n                            \n                                Erotica\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/crime_51/index.html">\n                            \n                                Crime\n                            \n                        </a>\n\n                        </li>\n                        \n                            </ul></li>\n                        \n                \n            </ul>\n        </div>\n    \n    \n\n            </aside>\n\n            <div class="col-sm-8 col-md-9">\n                \n                <div class="page-header action">\n                    <h1>All products</h1>\n                </div>\n                \n\n                \n\n\n\n<div id="messages">\n\n</div>\n\n\n                <div id="promotions">\n                    \n                </div>\n\n                \n    <form method="get" class="form-horizontal">\n        \n        <div style="display:none">\n            \n            \n        </div>\n\n        \n            \n                \n                    <strong>1000</strong> results - showing <strong>1</strong> to <strong>20</strong>.\n                \n            \n            \n        \n    </form>\n    \n        <section>\n            <div class="alert alert-warning" role="alert"><strong>Warning!</strong> This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.</div>\n\n            <div>\n                <ol class="row">\n                    \n                        <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">\n\n\n\n\n\n\n    <article class="product_pod">\n        \n            <div class="image_container">\n                \n                    \n                    <a href="catalogue/a-light-in-the-attic_1000/index.html"><img src="media/cache/2c/da/2cdad67c44b002e

In [26]:
items = driver.find_element("xpath","/html/body/div[1]/div/div/div/form/strong[1]")
items.text

'1000'

In [27]:
n_paginas = int(items.text)/20
n_paginas

50.0

In [29]:
n_paginas

50.0

In [30]:
for i in range(int(n_paginas)):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49

In [31]:
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
import time
from bs4 import BeautifulSoup

base_url = "http://books.toscrape.com/"

driver.get(base_url)

items = driver.find_element("xpath", "/html/body/div[1]/div/div/div/form/strong[1]")
n_paginas = int(items.text)/20

lista_links_completa = list()

for i in range(int(n_paginas)):

    soup = BeautifulSoup(driver.page_source, 'html.parser')

    print("Página número ", i+1)

    container = soup.find('ol')
    links = container.find_all('a')
    lista_links = list(set([link.get('href') for link in links]))
    lista_links_casi_completa = ["http://books.toscrape.com/catalogue/" + link.replace("catalogue/", "") for link in lista_links]
    lista_links_completa.append(lista_links_casi_completa)

    if i == 0:
        wait = WebDriverWait(driver, 5).until(EC.presence_of_element_located((By.XPATH, '//*[@id="default"]/div[1]/div/div/div/section/div[2]/div/ul/li[2]/a')))
        boton = driver.find_element(By.XPATH, '//*[@id="default"]/div[1]/div/div/div/section/div[2]/div/ul/li[2]/a')
        boton.click()

    elif i == 49:
        pass

    else:
        wait = WebDriverWait(driver, 5).until(EC.presence_of_element_located((By.XPATH, '//*[@id="default"]/div[1]/div/div/div/section/div[2]/div/ul/li[3]/a')))
        boton = driver.find_element(By.XPATH, '//*[@id="default"]/div[1]/div/div/div/section/div[2]/div/ul/li[3]/a')
        boton.click()

Página número  1
Página número  2
Página número  3
Página número  4
Página número  5
Página número  6
Página número  7
Página número  8
Página número  9
Página número  10
Página número  11
Página número  12
Página número  13
Página número  14
Página número  15
Página número  16
Página número  17
Página número  18
Página número  19
Página número  20
Página número  21
Página número  22
Página número  23
Página número  24
Página número  25
Página número  26
Página número  27
Página número  28
Página número  29
Página número  30
Página número  31
Página número  32
Página número  33
Página número  34
Página número  35
Página número  36
Página número  37
Página número  38
Página número  39
Página número  40
Página número  41
Página número  42
Página número  43
Página número  44
Página número  45
Página número  46
Página número  47
Página número  48
Página número  49
Página número  50

In [37]:
lista_links_completa[49]

['http://books.toscrape.com/catalogue/paper-girls-vol-1-paper-girls-1-5_44/index.html',
 'http://books.toscrape.com/catalogue/rat-queens-vol-1-sass-sorcery-rat-queens-collected-editions-1-5_46/index.html',
 'http://books.toscrape.com/catalogue/taking-shots-assassins-1_57/index.html',
 'http://books.toscrape.com/catalogue/sense-and-sensibility_49/index.html',
 'http://books.toscrape.com/catalogue/saga-volume-1-saga-collected-editions-1_48/index.html',
 'http://books.toscrape.com/catalogue/skip-beat-vol-01-skip-beat-1_55/index.html',
 'http://books.toscrape.com/catalogue/the-bette-davis-club_59/index.html',
 'http://books.toscrape.com/catalogue/shadow-rites-jane-yellowrock-10_51/index.html',
 'http://books.toscrape.com/catalogue/shatter-me-shatter-me-1_53/index.html',
 'http://books.toscrape.com/catalogue/the-bhagavad-gita_60/index.html',
 'http://books.toscrape.com/catalogue/paradise-lost-paradise-1_45/index.html',
 'http://books.toscrape.com/catalogue/rhythm-chord-malykhin_47/index.html',
 'http://books.toscrape.com/catalogue/origins-alphas-05_42/index.html',
 'http://books.toscrape.com/catalogue/one-second-seven-7_41/index.html',
 'http://books.toscrape.com/catalogue/ouran-high-school-host-club-vol-1-ouran-high-school-host-club-1_43/index.html',
 'http://books.toscrape.com/catalogue/settling-the-score-the-summer-games-1_50/index.html',
 'http://books.toscrape.com/catalogue/the-art-of-not-breathing_58/index.html',
 'http://books.toscrape.com/catalogue/starlark_56/index.html',
 'http://books.toscrape.com/catalogue/shameless_52/index.html',
 'http://books.toscrape.com/catalogue/sister-sable-the-mad-queen-1_54/index.html']

In [40]:
lista_links_completa_version2 = [item for sublista in lista_links_completa for item in sublista] #Aplanamos
lista_links_completa_version2 = lista_links_completa_version2[:25] #Consideramos únicamente 25 items
lista_links_completa_version2

['http://books.toscrape.com/catalogue/the-black-maria_991/index.html',
 'http://books.toscrape.com/catalogue/its-only-the-himalayas_981/index.html',
 'http://books.toscrape.com/catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html',
 'http://books.toscrape.com/catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html',
 'http://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html',
 'http://books.toscrape.com/catalogue/rip-it-up-and-start-again_986/index.html',
 'http://books.toscrape.com/catalogue/olio_984/index.html',
 'http://books.toscrape.com/catalogue/sharp-objects_997/index.html',
 'http://books.toscrape.com/catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html',
 'http://books.toscrape.com/catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html',
 'http://books.toscrape.com/catalogue/set-me-free_988/index.html',
 'http://books.toscrape.com/catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html',
 'http://books.toscrape.com/catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html',
 'http://books.toscrape.com/catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html',
 'http://books.toscrape.com/catalogue/shakespeares-sonnets_989/index.html',
 'http://books.toscrape.com/catalogue/the-requiem-red_995/index.html',
 'http://books.toscrape.com/catalogue/sapiens-a-brief-history-of-humankind_996/index.html',
 'http://books.toscrape.com/catalogue/libertarianism-for-beginners_982/index.html',
 'http://books.toscrape.com/catalogue/soumission_998/index.html',
 'http://books.toscrape.com/catalogue/tipping-the-velvet_999/index.html',
 'http://books.toscrape.com/catalogue/wall-and-piece_971/index.html',
 'http://books.toscrape.com/catalogue/chase-me-paris-nights-2_977/index.html',
 'http://books.toscrape.com/catalogue/birdsong-a-story-in-pictures_975/index.html',
 'http://books.toscrape.com/catalogue/the-five-love-languages-how-to-express-heartfelt-commitment-to-your-mate_969/index.html',
 'http://books.toscrape.com/catalogue/the-bear-and-the-piano_967/index.html']

In [41]:
import requests

lista_toda_informacion = list()

for item in lista_links_completa_version2:

    print(item)
    result = requests.get(item)

    if result.status_code == requests.codes.ok:

        soup = BeautifulSoup(result.content, 'html.parser')


        nombre = soup.find("h1")
        descripcion = soup.find_all("p")
        atributos_tabla = soup.find_all('tr')

        diccionario = dict()

        diccionario["Nombre"] = nombre.text
        diccionario["Description"] = descripcion[3].text

        for atributo in atributos_tabla:
            diccionario[atributo.select("th")[0].text] = atributo.select("td")[0].text

        lista_toda_informacion.append(diccionario)

    else:
        pass

http://books.toscrape.com/catalogue/the-black-maria_991/index.html
http://books.toscrape.com/catalogue/its-only-the-himalayas_981/index.html
http://books.toscrape.com/catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html
http://books.toscrape.com/catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html
http://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html
http://books.toscrape.com/catalogue/rip-it-up-and-start-again_986/index.html
http://books.toscrape.com/catalogue/olio_984/index.html
http://books.toscrape.com/catalogue/sharp-objects_997/index.html
http://books.toscrape.com/catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html
http://books.toscrape.com/catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html
http://books.toscrape.com/catalogue/set-me-free_988/index.html
http://books.toscrape.com/catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html
http://books.toscrape.com/catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html
http://books.toscrape.com/catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html
http://books.toscrape.com/catalogue/shakespeares-sonnets_989/index.html
http://books.toscrape.com/catalogue/the-requiem-red_995/index.html
http://books.toscrape.com/catalogue/sapiens-a-brief-history-of-humankind_996/index.html
http://books.toscrape.com/catalogue/libertarianism-for-beginners_982/index.html
http://books.toscrape.com/catalogue/soumission_998/index.html
http://books.toscrape.com/catalogue/tipping-the-velvet_999/index.html
http://books.toscrape.com/catalogue/wall-and-piece_971/index.html
http://books.toscrape.com/catalogue/chase-me-paris-nights-2_977/index.html
http://books.toscrape.com/catalogue/birdsong-a-story-in-pictures_975/index.html
http://books.toscrape.com/catalogue/the-five-love-languages-how-to-express-heartfelt-commitment-to-your-mate_969/index.html
http://books.toscrape.com/catalogue/the-bear-and-the-piano_967/index.html

In [42]:
lista_toda_informacion

[{'Nombre': 'The Black Maria',
  'Description': 'Praise for Aracelis Girmay:"[Girmay\'s] every loss—she calls them estrangements—is a yearning for connection across time and place; her every fragment is a bulwark against ruin." — O, The Oprah Magazine "In Aracelis Girmay we have a poet who collects, polishes, and shares stories with such brilliant invention, tenderness, and intellectual liveliness that it is understandabl Praise for Aracelis Girmay:"[Girmay\'s] every loss—she calls them estrangements—is a yearning for connection across time and place; her every fragment is a bulwark against ruin." — O, The Oprah Magazine "In Aracelis Girmay we have a poet who collects, polishes, and shares stories with such brilliant invention, tenderness, and intellectual liveliness that it is understandable that we think of her as the blessed curator of our collective histories. There is in her art the vulnerability of one who lives inside of the stories that she gathers in this remarkable collection. Her poems set off alarms even as they transform the world she inhabits, showing us, in the process, exactly what she asks of Romare Bearden’s art: ‘…how not to // assign all blackness near the sea / a captivity.’ This is one of the many sweet contradictions in the black maria, which ‘is a black flag / wounding the pastoral.’ I am deeply thankful that we have a poet of her unique and singular talent writing today." —Kwame DawesTaking its name from the moon\'s dark plains, misidentified as seas by early astronomers, the black maria investigates African diasporic histories, the consequences of racism within American culture, and the question of human identity. Central to this project is a desire to recognize the lives of Eritrean refugees who have been made invisible by years of immigration crisis, refugee status, exile, and resulting statelessness. The recipient of a 2015 Whiting Award for Poetry, Girmay\'s newest collection elegizes and celebrates life, while wrestling with the humanistic notion of seeing beyond: seeing violence, seeing grace, and seeing each other better."to the sea"great storage house, historyon which we rode, we touchedthe brief pulse of your flutteringpages, spelled with salt & life,your rage, your indifferenceyour gentleness washing our feet,all of you going onwhether or not we live,to you we bring our carnationsyellow & pink, how they floatlike bright sentences atopyour memory\'s dark hairAracelis Girmay is the author of three poetry collections, the black maria; Kingdom Animalia, which won the Isabella Gardner Award and was a finalist for the NBCC Award; and Teeth. The recipient of a 2015 Whiting Award, she has received grants and fellowships from the Jerome, Cave Canem, and Watson foundations, as well as Civitella Ranieri and the NEA. She currently teaches at Hampshire College\'s School for Interdisciplinary Arts and in Drew University\'s low residency MFA program. Originally from Santa Ana, California, she splits her time between New York and Amherst, Massachusetts. ...more',
  'UPC': '1dfe412b8ac00530',
  'Product Type': 'Books',
  'Price (excl. tax)': '£52.15',
  'Price (incl. tax)': '£52.15',
  'Tax': '£0.00',
  'Availability': 'In stock (19 available)',
  'Number of reviews': '0'},
 {'Nombre': "It's Only the Himalayas",
  'Description': '“Wherever you go, whatever you do, just . . . don’t do anything stupid.” —My MotherDuring her yearlong adventure backpacking from South Africa to Singapore, S. Bedford definitely did a few things her mother might classify as "stupid." She swam with great white sharks in South Africa, ran from lions in Zimbabwe, climbed a Himalayan mountain without training in Nepal, and wa “Wherever you go, whatever you do, just . . . don’t do anything stupid.” —My MotherDuring her yearlong adventure backpacking from South Africa to Singapore, S. Bedford definitely did a few things her mother might classify as "stupid." She swam with great white sharks in South Africa, ran from lions in Zimbabwe, climbed a Himalayan mountain without training in Nepal, and watched as her friend was attacked by a monkey in Indonesia.But interspersed in those slightly more crazy moments, Sue Bedfored and her friend "Sara the Stoic" experienced the sights, sounds, life, and culture of fifteen countries. Joined along the way by a few friends and their aging fathers here and there, Sue and Sara experience the trip of a lifetime. They fall in love with the world, cultivate an appreciation for home, and discover who, or what, they want to become.It\'s Only the Himalayas is the incredibly funny, sometimes outlandish, always entertaining confession of a young backpacker that will inspire you to take your own adventure. ...more',
  'UPC': 'a22124811bfa8350',
  'Product Type': 'Books',
  'Price (excl. tax)': '£45.17',
  'Price (incl. tax)': '£45.17',
  'Tax': '£0.00',
  'Availability': 'In stock (19 available)',
  'Number of reviews': '0'},
 {'Nombre': 'Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991',
  'Description': "This is the never-before-told story of the musical revolution that happened right under the nose of the Reagan Eighties--when a small but sprawling network of bands, labels, fanzines, radio stations, and other subversives reenergized American rock with punk rock's do-it-yourself credo and created music that was deeply personal, often brilliant, always challenging, and imme This is the never-before-told story of the musical revolution that happened right under the nose of the Reagan Eighties--when a small but sprawling network of bands, labels, fanzines, radio stations, and other subversives reenergized American rock with punk rock's do-it-yourself credo and created music that was deeply personal, often brilliant, always challenging, and immensely influential. This sweeping chronicle of music, politics, drugs, fear, loathing, and faith has been recognized as an indie rock classic in its own right. Among the bands profiled: Mission of Burma, Butthole Surfers, The Minutemen, Sonic Youth, Black Flag, Big Black, Hüsker Dü, Fugazi, Minor Threat, Mudhoney, The Replacements, Beat Happening, and Dinosaur Jr. ...more",
  'UPC': 'deda3e61b9514b83',
  'Product Type': 'Books',
  'Price (excl. tax)': '£57.25',
  'Price (incl. tax)': '£57.25',
  'Tax': '£0.00',
  'Availability': 'In stock (19 available)',
  'Number of reviews': '0'},
 {'Nombre': 'Mesaerion: The Best Science Fiction Stories 1800-1849',
  'Description': 'Andrew Barger, award-winning author and engineer, has extensively researched forgotten journals and magazines of the early 19th century to locate groundbreaking science fiction short stories in the English language. In doing so, he found what is possibly the first science fiction story by a female (and it is not from Mary Shelley). Andrew located the first steampunk short Andrew Barger, award-winning author and engineer, has extensively researched forgotten journals and magazines of the early 19th century to locate groundbreaking science fiction short stories in the English language. In doing so, he found what is possibly the first science fiction story by a female (and it is not from Mary Shelley). Andrew located the first steampunk short story, which has not been republished since 1844. There is the first voyage to the moon in a balloon, republished for the first time since 1820 that further tells of a darkness machine and a lunarian named Zuloc. Other sci-stories include the first robotic insect and an electricity gun. Once again, Andrew has searched old texts to find the very best science fiction stories from the period when the genre automated to life, some of the stories are published for the first time in nearly 200 years. Read these fantastic stories today!OUR OWN COUNTRY So mechanical has the age become, that men seriously talk of flying machines, to go by steam, --not your air-balloons, but real Daedalian wings, made of wood and joints, nailed to your shoulder, --not wings of feathers and wax like the wings of Icarus, who fell into the Cretan sea, but real, solid, substantial, rock-maple wings with wrought-iron hinges, and huge concavities, to propel us through the air. Knickerbocker Magazine, May 18 ...more',
  'UPC': 'e30f54cea9b38190',
  'Product Type': 'Books',
  'Price (excl. tax)': '£37.59',
  'Price (incl. tax)': '£37.59',
  'Tax': '£0.00',
  'Availability': 'In stock (19 available)',
  'Number of reviews': '0'},
 {'Nombre': 'A Light in the Attic',
  'Description': "It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love th It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love that Silverstein. Need proof of his genius? RockabyeRockabye baby, in the treetopDon't you know a treetopIs no safe place to rock?And who put you up there,And your cradle, too?Baby, I think someone down here'sGot it in for you. Shel, you never sounded so good. ...more",
  'UPC': 'a897fe39b1053632',
  'Product Type': 'Books',
  'Price (excl. tax)': '£51.77',
  'Price (incl. tax)': '£51.77',
  'Tax': '£0.00',
  'Availability': 'In stock (22 available)',
  'Number of reviews': '0'},
 {'Nombre': 'Rip it Up and Start Again',
  'Description': "Punk's raw power rejuvenated rock, but by the summer of 1977 the movement had become a parody of itself. RIP IT UP AND START AGAIN is a celebration of what happened next.Post-punk bands like PiL, Joy Division, Talking Heads, The Fall and The Human League dedicated themselves to fulfilling punk's unfinished musical revolution. The post-punk groups were fervent modernists; w Punk's raw power rejuvenated rock, but by the summer of 1977 the movement had become a parody of itself. RIP IT UP AND START AGAIN is a celebration of what happened next.Post-punk bands like PiL, Joy Division, Talking Heads, The Fall and The Human League dedicated themselves to fulfilling punk's unfinished musical revolution. The post-punk groups were fervent modernists; whether experimenting with electronics and machine rhythm or adapting ideas from dub reggae and disco, they were totally confident they could invent a whole new future for music. ...more",
  'UPC': 'a34ba96d4081e6a4',
  'Product Type': 'Books',
  'Price (excl. tax)': '£35.02',
  'Price (incl. tax)': '£35.02',
  'Tax': '£0.00',
  'Availability': 'In stock (19 available)',
  'Number of reviews': '0'},
 {'Nombre': 'Olio',
  'Description': "Part fact, part fiction, Tyehimba Jess's much anticipated second book weaves sonnet, song, and narrative to examine the lives of mostly unrecorded African American performers directly before and after the Civil War up to World War I. Olio is an effort to understand how they met, resisted, complicated, co-opted, and sometimes defeated attempts to minstrelize them.So, while Part fact, part fiction, Tyehimba Jess's much anticipated second book weaves sonnet, song, and narrative to examine the lives of mostly unrecorded African American performers directly before and after the Civil War up to World War I. Olio is an effort to understand how they met, resisted, complicated, co-opted, and sometimes defeated attempts to minstrelize them.So, while I lead this choir, I still find thatI'm being led…I'm a missionarymending my faith in the midst of this flock…I toil in their fields of praise. When folks seethese freedmen stand and sing, they hear their Godspeak in tongues. These nine dark mouths sing shelter;they echo a hymn's haven from slavery's weather.Detroit native Tyehimba Jess' first book of poetry, leadbelly, was a winner of the 2004 National Poetry Series. Jess, a Cave Canem and NYU Alumni, has received fellowships from the Whiting Foundation, National Endowment for the Arts, Illinois Arts Council, and the Provincetown Fine Arts Work Center. Jess is also a veteran of the 2000 and 2001 Green Mill Poetry Slam Team. He exhibited his poetry at the 2011 TEDxNashville Conference. Jess is an Associate Professor of English at College of Staten Island. ...more",
  'UPC': 'feb7cc7701ecf901',
  'Product Type': 'Books',
  'Price (excl. tax)': '£23.88',
  'Price (incl. tax)': '£23.88',
  'Tax': '£0.00',
  'Availability': 'In stock (19 available)',
  'Number of reviews': '0'},
 {'Nombre': 'Sharp Objects',
  'Description': 'WICKED above her hipbone, GIRL across her heart Words are like a road map to reporter Camille Preaker’s troubled past. Fresh from a brief stay at a psych hospital, Camille’s first assignment from the second-rate daily paper where she works brings her reluctantly back to her hometown to cover the murders of two preteen girls. NASTY on her kneecap, BABYDOLL on her leg Since WICKED above her hipbone, GIRL across her heart Words are like a road map to reporter Camille Preaker’s troubled past. Fresh from a brief stay at a psych hospital, Camille’s first assignment from the second-rate daily paper where she works brings her reluctantly back to her hometown to cover the murders of two preteen girls. NASTY on her kneecap, BABYDOLL on her leg Since she left town eight years ago, Camille has hardly spoken to her neurotic, hypochondriac mother or to the half-sister she barely knows: a beautiful thirteen-year-old with an eerie grip on the town. Now, installed again in her family’s Victorian mansion, Camille is haunted by the childhood tragedy she has spent her whole life trying to cut from her memory. HARMFUL on her wrist, WHORE on her ankle As Camille works to uncover the truth about these violent crimes, she finds herself identifying with the young victims—a bit too strongly. Clues keep leading to dead ends, forcing Camille to unravel the psychological puzzle of her own past to get at the story. Dogged by her own demons, Camille will have to confront what happened to her years before if she wants to survive this homecoming.With its taut, crafted writing, Sharp Objects is addictive, haunting, and unforgettable. ...more',
  'UPC': 'e00eb4fd7b871a48',
  'Product Type': 'Books',
  'Price (excl. tax)': '£47.82',
  'Price (incl. tax)': '£47.82',
  'Tax': '£0.00',
  'Availability': 'In stock (20 available)',
  'Number of reviews': '0'},
 {'Nombre': 'The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics',
  'Description': "For readers of Laura Hillenbrand's Seabiscuit and Unbroken, the dramatic story of the American rowing team that stunned the world at Hitler's 1936 Berlin Olympics Daniel James Brown’s robust book tells the story of the University of Washington’s 1936 eight-oar crew and their epic quest for an Olympic gold medal, a team that transformed the sport and grabbed the attention o For readers of Laura Hillenbrand's Seabiscuit and Unbroken, the dramatic story of the American rowing team that stunned the world at Hitler's 1936 Berlin Olympics Daniel James Brown’s robust book tells the story of the University of Washington’s 1936 eight-oar crew and their epic quest for an Olympic gold medal, a team that transformed the sport and grabbed the attention of millions of Americans. The sons of loggers, shipyard workers, and farmers, the boys defeated elite rivals first from eastern and British universities and finally the German crew rowing for Adolf Hitler in the Olympic games in Berlin, 1936. The emotional heart of the story lies with one rower, Joe Rantz, a teenager without family or prospects, who rows not for glory, but to regain his shattered self-regard and to find a place he can call home. The crew is assembled\xa0 by an enigmatic coach and mentored by a visionary, eccentric British boat builder, but it is their trust in each other that makes them a victorious team. They remind the country of what can be done when everyone quite literally pulls together—a perfect melding of commitment, determination, and optimism. Drawing on the boys’ own diaries and journals, their photos and memories of a once-in-a-lifetime shared dream, The Boys in the Boat is an irresistible story about beating the odds and finding hope in the most desperate of times—the improbable, intimate story of nine working-class boys from the American west who, in the depths of the Great Depression, showed the world what true grit really meant. It will appeal to readers of Erik Larson, Timothy Egan, James Bradley, and David Halberstam's The Amateurs. ...more",
  'UPC': 'e10e1e165dc8be4a',
  'Product Type': 'Books',
  'Price (excl. tax)': '£22.60',
  'Price (incl. tax)': '£22.60',
  'Tax': '£0.00',
  'Availability': 'In stock (19 available)',
  'Number of reviews': '0'},
 {'Nombre': 'The Dirty Little Secrets of Getting Your Dream Job',
  'Description': "Drawing on his extensive experience evaluating applicants for his marketing agency, and featuring stories based on real-life situations, sample cover letters, resumes, and straightforward advice, Don Raskin’s The Dirty Little Secrets of Getting Your Dream Job offers all the necessary tools for navigating the tough job market and securing your dream job.Don Raskin owns and Drawing on his extensive experience evaluating applicants for his marketing agency, and featuring stories based on real-life situations, sample cover letters, resumes, and straightforward advice, Don Raskin’s The Dirty Little Secrets of Getting Your Dream Job offers all the necessary tools for navigating the tough job market and securing your dream job.Don Raskin owns and operates MME, an advertising and marketing agency in New York City. During his twenty-five years at the agency he has interviewed hundreds of new college graduates for positions within his agency and has placed a strong emphasis on entry-level recruitment for positions in creative, account management, traffic, and production. Raskin has also mentored countless students and their parents on best practices for the job search. Over the years, Raskin has kept exceptionally detailed notes on the interviews he has conducted, observing the good, the bad, the ridiculous, the irreverent. He also has a treasure trove of over-the-top cover letters, resumes, interviews, and post interview follow-ups he has conducted and received. Now, he wants to share all the wisdom and insider secrets he has gathered to help students and first-time job seekers find a job in this economy.Based on his remarkable expertise, Raskin's book provides exclusive insight into the job search process and lets readers in on all of the dirty little secrets to landing their first job—or a new one—and finding career success. ...more",
  'UPC': '2597b5a345f45e1b',
  'Product Type': 'Books',
  'Price (excl. tax)': '£33.34',
  'Price (incl. tax)': '£33.34',
  'Tax': '£0.00',
  'Availability': 'In stock (19 available)',
  'Number of reviews': '0'},
 {'Nombre': 'Set Me Free',

In [43]:
import pandas as pd

In [44]:
resultado = pd.DataFrame(lista_toda_informacion)

In [19]:
resultado.describe()

,Nombre,Description,UPC,Product Type,Price (excl. tax),Price (incl. tax),Tax,Availability,Number of reviews
count,25,25,25,25,25,25,25,25,25
unique,25,25,25,1,25,25,1,4,1
top,The Black Maria,"Praise for Aracelis Girmay:""[Girmay's] every l...",1dfe412b8ac00530,Books,£52.15,£52.15,£0.00,In stock (19 available),0
freq,1,1,1,25,1,1,25,17,25

In [45]:
resultado.head()

,Nombre,Description,UPC,Product Type,Price (excl. tax),Price (incl. tax),Tax,Availability,Number of reviews
0,The Black Maria,"Praise for Aracelis Girmay:""[Girmay's] every l...",1dfe412b8ac00530,Books,£52.15,£52.15,£0.00,In stock (19 available),0
1,It's Only the Himalayas,"“Wherever you go, whatever you do, just . . . ...",a22124811bfa8350,Books,£45.17,£45.17,£0.00,In stock (19 available),0
2,Our Band Could Be Your Life: Scenes from the A...,This is the never-before-told story of the mus...,deda3e61b9514b83,Books,£57.25,£57.25,£0.00,In stock (19 available),0
3,Mesaerion: The Best Science Fiction Stories 18...,"Andrew Barger, award-winning author and engine...",e30f54cea9b38190,Books,£37.59,£37.59,£0.00,In stock (19 available),0
4,A Light in the Attic,It's hard to imagine a world without A Light i...,a897fe39b1053632,Books,£51.77,£51.77,£0.00,In stock (22 available),0

In [21]:
resultado

,Nombre,Description,UPC,Product Type,Price (excl. tax),Price (incl. tax),Tax,Availability,Number of reviews
0,The Black Maria,"Praise for Aracelis Girmay:""[Girmay's] every l...",1dfe412b8ac00530,Books,£52.15,£52.15,£0.00,In stock (19 available),0
1,It's Only the Himalayas,"“Wherever you go, whatever you do, just . . . ...",a22124811bfa8350,Books,£45.17,£45.17,£0.00,In stock (19 available),0
2,Our Band Could Be Your Life: Scenes from the A...,This is the never-before-told story of the mus...,deda3e61b9514b83,Books,£57.25,£57.25,£0.00,In stock (19 available),0
3,Mesaerion: The Best Science Fiction Stories 18...,"Andrew Barger, award-winning author and engine...",e30f54cea9b38190,Books,£37.59,£37.59,£0.00,In stock (19 available),0
4,A Light in the Attic,It's hard to imagine a world without A Light i...,a897fe39b1053632,Books,£51.77,£51.77,£0.00,In stock (22 available),0
5,Rip it Up and Start Again,"Punk's raw power rejuvenated rock, but by the ...",a34ba96d4081e6a4,Books,£35.02,£35.02,£0.00,In stock (19 available),0
6,Olio,"Part fact, part fiction, Tyehimba Jess's much ...",feb7cc7701ecf901,Books,£23.88,£23.88,£0.00,In stock (19 available),0
7,Sharp Objects,"WICKED above her hipbone, GIRL across her hear...",e00eb4fd7b871a48,Books,£47.82,£47.82,£0.00,In stock (20 available),0
8,The Boys in the Boat: Nine Americans and Their...,For readers of Laura Hillenbrand's Seabiscuit ...,e10e1e165dc8be4a,Books,£22.60,£22.60,£0.00,In stock (19 available),0
9,The Dirty Little Secrets of Getting Your Dream...,Drawing on his extensive experience evaluating...,2597b5a345f45e1b,Books,£33.34,£33.34,£0.00,In stock (19 available),0
10,Set Me Free,Aaron Ledbetter’s future had been planned out ...,ce6396b0f23f6ecc,Books,£17.46,£17.46,£0.00,In stock (19 available),0
11,The Coming Woman: A Novel Based on the Life of...,"""If you have a heart, if you have a soul, Kare...",e72a5dfc7e9267b2,Books,£17.93,£17.93,£0.00,In stock (19 available),0
12,"Starving Hearts (Triangular Trade Trilogy, #1)","Since her assault, Miss Annette Chetwynd has b...",0312262ecafa5a40,Books,£13.99,£13.99,£0.00,In stock (19 available),0
13,Scott Pilgrim's Precious Little Life (Scott Pi...,Scott Pilgrim's life is totally sweet. He's 23...,3b1c02bac2a429e6,Books,£52.29,£52.29,£0.00,In stock (19 available),0
14,Shakespeare's Sonnets,This book is an important and complete collect...,30a7f60cd76ca58c,Books,£20.66,£20.66,£0.00,In stock (19 available),0
15,The Requiem Red,Patient Twenty-nine.A monster roams the halls ...,f77dbf2323deb740,Books,£22.65,£22.65,£0.00,In stock (19 available),0
16,Sapiens: A Brief History of Humankind,From a renowned historian comes a groundbreaki...,4165285e1663650f,Books,£54.23,£54.23,£0.00,In stock (20 available),0
17,Libertarianism for Beginners,Libertarianism isn't about winning elections; ...,a18a4f574854aced,Books,£51.33,£51.33,£0.00,In stock (19 available),0
18,Soumission,"Dans une France assez proche de la nôtre, un h...",6957f44c3847a760,Books,£50.10,£50.10,£0.00,In stock (20 available),0
19,Tipping the Velvet,"""Erotic and absorbing...Written with starling ...",90fa61229261140a,Books,£53.74,£53.74,£0.00,In stock (20 available),0
20,Wall and Piece,"Banksy, Britain's now-legendary ""guerilla"" str...",ccd9ffa25efabdea,Books,£44.18,£44.18,£0.00,In stock (18 available),0
21,Chase Me (Paris Nights #2),"A Michelin two-star chef at twenty-eight, Viol...",c2e46a2ee3b4a322,Books,£25.27,£25.27,£0.00,In stock (19 available),0
22,Birdsong: A Story in Pictures,Bring the thrilling story of one red bird to l...,9528d0948525bf5f,Books,£54.64,£54.64,£0.00,In stock (19 available),0
23,The Five Love Languages: How to Express Heartf...,Are you and your spouse speaking the same lang...,3c039985229453bf,Books,£31.05,£31.05,£0.00,In stock (18 available),0
24,The Bear and the Piano,"One day, a young bear stumbles upon something ...",9f6568e9c95f60b0,Books,£36.89,£36.89,£0.00,In stock (18 available),0