# Introducción a la manipulación de datos: Principales librerías (1) - Pandas

****

****

## 1. Primeros pasos con Pandas

Pandas es una librería de Python de código abierto que se encarga de la manipulación de datos de alto nivel y está construida sobre NumPy. Tiene varias estructuras de datos para manipular y tratar la información. Una de las principales estructuras guarda la información tabulada en un objeto llamado DataFrame.

****

### 1.1. Instalar e importar Pandas

Para instalar pandas necesitamos escribir en nuestra consola ```pip install pandas```. En Google Colab la librería Pandas ya viene previamente instalada. Recuerda que si quisieras instalar en Google Colab una librería, deberás utilizar "!". El símbolo "!" indica a la celda del cuaderno que esta línea no es un código de Python, si no que se trata de un comando de Bash. Siguiendo con la librería pandas, si en Google Colab esta librería no estuviera instalada por defecto, deberíamos ejecutar una celda independiente el siguiente comando ```!pip install pandas```

pip es el administrador de librerías por defecto de python, podeís encontrar gran cantidad de librerías aquí:
- https://pypi.org/

Una vez que el paquete pandas este instalado, podemos importar la libreria de la siguiente forma:

In [1]:
import pandas as pd  # pd es el alias que habitualmente se utiliza

****

### 1.2. Estructuras de datos en Pandas

- **Series**. Array unidimensional etiquetado capaz de almacenar cualquier tipo de dato.
- **DataFrame**. Estructura bidimensional con columnas que pueden ser también de cualquier tipo. Estas columnas son a su vez Series.

Dado que las un DataFrame es un conjunto de Series, la principal estructura que vamos a trabajar va a ser el DataFrame.

****

### 1.3.  Crear DataFrame

Un DataFrame es la estructura de datos con la que Pandas almacena y manipula datos tabulados (no es la única estructura de datos, pero es la más común). En palabras más sencillas, es como una hoja de cálculo de Excel. Tiene filas y columnas, acepta distintos tipos de datos y permite interactuar entre ellos. La diferencia con una hoja de cálculo es que es extremadamente más rápida y potente, por lo que podrás trabajar con cantidades muy grandes de datos.

Dado que MS Excel solo puede tratar con aproximadamente 1M filas por 16m columnas, la librería pandas se convierte en la ofimática del futuro.

Hay un varias formas de crear un DataFrame con Python desde 0, las más habituales son:

- 1. Diccionario de listas:

In [2]:
data = {"country": ["España", "Australia"],
        "M_population": [47.6, 25.7],
        "M_km2": [0.5, 7.7]}

df = pd.DataFrame(data)
df

     country  M_population  M_km2
0     España          47.6    0.5
1  Australia          25.7    7.7

- 2. Lista de diccionarios:

In [3]:
data = [{"country": "España", "M_population": 47.6, "M_km2": 0.5},
        {"country": "Australia", "M_population": 25.7, "M_km2": 7.7}]

df = pd.DataFrame(data)
df

     country  M_population  M_km2
0     España          47.6    0.5
1  Australia          25.7    7.7

- 3. Lista de listas :

In [4]:
data = [["España", 47.6, 0.5], ["Australia", 25.7, 7.7]]

df = pd.DataFrame(data, columns=["country", "M_population", "M_km2"])
df

     country  M_population  M_km2
0     España          47.6    0.5
1  Australia          25.7    7.7

****

### 1.4. Leer archivos con Pandas

Sin embargo, lo más habitual es manipular datos importando los datos de otros archivos (CSV, JSON, etc) y BBDDs. Pandas tiene varias formas de leer un archivo, el código base suele ser: pd.read_{file_type}('path')

Por ejemplo, para cargar un CSV (Comma Separated Values), la función sería: pd.read_csv('path/file.csv'). Esto convertirá el contenido del CSV en un DataFrame, el cual por convención se lo nombra como df. Para comenzar vamos a importar, desde github, un archivo CSV que contiene información sobre las 1000 películas más famosas de IMDB en el periodo 2006-2016.

In [5]:
df = pd.read_csv("https://raw.githubusercontent.com/JorgeRincon-PY/datasets/main/IMDB-Movie-Data.csv")
df

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

La visualización del DataFrame se puede configurar de la siguiente manera:

In [6]:
pd.set_option("display.max_columns", 6)
pd.set_option("display.max_rows", 20)

Podemos ver que ahora nuestro DataFrame solo muestra 6 columnas y 20 filas. Recordar que esto es solo para visualizar el DataFrame, no se modifican los datos.

In [ ]:
df

,Rank,Title,Genre,...,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",...,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi",...,485820,126.46,65.0
2,3,Split,"Horror,Thriller",...,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family",...,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",...,393727,325.02,40.0
...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery",...,27585,NaN,45.0
996,997,Hostel: Part II,Horror,...,73152,17.54,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",...,70699,58.01,50.0
998,999,Search Party,"Adventure,Comedy",...,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",...,12435,19.64,11.0

Vamos a volver a configurar la visualización del DataFrame para que nos muestre todas las columnas (12), pero solo 10 filas.

In [7]:
pd.set_option("display.max_columns", 12)
pd.set_option("display.max_rows", 10)

****

****

## 2. Inspeccionar DataFrame

Ya tienes todo lo que necesitas para importar un DataFrame. Pero cuando empiezas a hacer un análisis de datos es muy importante que primero inspecciones todo: una pequeña muestra de los datos, cuántas filas hay, qué columnas existen, qué tipos de datos hay, si faltan datos, una ligera vista de sus estadísticas descriptivas, etc.

Algunas funciones de pandas para hacer esto son las siguientes:

- ```df.head()``` → Retorna las 5 primeras filas. También le puedes pasar un entero como parámetro y te devolverá esa cantidad de primeras filas.
- ```df.tail()``` → Retorna las últimas 5 filas del dataset.
- ```df.sample()``` → Es parecido a los 2 anteriores, pero este tomará muestras al azar del DataFrame. Aquí es obligatorio especificar la cantidad.
- ```df.shape``` → Retorna las filas y columnas que tiene el DataFrame.
- ```df.size``` → Multiplica las filas y columnas y te da el total de datos del DataFrame.
- ```df.info()``` → Te da la cuenta de valores no nulos, el tipo de dato de cada columna (recuerda que solo puede haber un único tipo de dato por columna) y el uso de memoria. Cuando estés preprocesando los datos, será un gran aliado.
- ```df.describe()``` → Te ayudará mucho con las primeras impresiones de los datos. Calcula algunas estadísticas descriptivas para cada columna.

In [8]:
df.head(2)

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0

In [9]:
df.tail(2)

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [10]:
df.sample(2)

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
252,253,Straight Outta Compton,"Biography,Drama,History",The group NWA emerges from the mean streets of...,F. Gary Gray,"O'Shea Jackson Jr., Corey Hawkins, Jason Mitch...",2015,147,7.9,139831,161.03,72.0
433,434,Mission: Impossible - Ghost Protocol,"Action,Adventure,Thriller",The IMF is shut down when it's implicated in t...,Brad Bird,"Tom Cruise, Jeremy Renner, Simon Pegg, Paula P...",2011,132,7.4,382459,209.36,73.0

In [11]:
df.shape

(1000, 12)

In [12]:
df.size

12000

In [ ]:
df.info() # Faltaría un Dtype, que es datetime para las fechas

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Title               1000 non-null   object
 2   Genre               1000 non-null   object
 3   Description         1000 non-null   object
 4   Director            1000 non-null   object
 5   Actors              1000 non-null   object
 6   Year                1000 non-null   int64
 7   Runtime (Minutes)   1000 non-null   int64
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64
 10  Revenue (Millions)  872 non-null    float64
 11  Metascore           936 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 93.9+ KB

In [13]:
df.describe()

,Rank,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
count,1000.000000,1000.000000,1000.000000,1000.000000,1.000000e+03,872.000000,936.000000
mean,500.500000,2012.783000,113.172000,6.723200,1.698083e+05,82.956376,58.985043
std,288.819436,3.205962,18.810908,0.945429,1.887626e+05,103.253540,17.194757
min,1.000000,2006.000000,66.000000,1.900000,6.100000e+01,0.000000,11.000000
25%,250.750000,2010.000000,100.000000,6.200000,3.630900e+04,13.270000,47.000000
50%,500.500000,2014.000000,111.000000,6.800000,1.107990e+05,47.985000,59.500000
75%,750.250000,2016.000000,123.000000,7.400000,2.399098e+05,113.715000,72.000000
max,1000.000000,2016.000000,191.000000,9.000000,1.791916e+06,936.630000,100.000000

También podemos ver el nombre de las columnas y del indice realizando lo siguiente:

In [14]:
df.columns

Index(['Rank', 'Title', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

In [15]:
df.index

RangeIndex(start=0, stop=1000, step=1)

****

****

## 3. Ordenar DataFrame

Imaginaros que no tenemos muy en claro qué orden está siguiendo el conjunto de datos, para eso podemos utilizar ```df.sort_values()```, esta función de Pandas nos permite darle el orden que queramos a nuestro conjunto de datos.

Esta función tiene 2 parámetros importantes: by y ascending. El primero recibe el nombre de la columna que quieras ordenar y el segundo un booleano que indica si la quieres ordenar ascendentemente o no. Puedes introducir varios campos para ordenar.

In [16]:
df.sort_values(["Year", "Votes"], ascending=[False, True])

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
478,479,Paint It Black,Drama,A young woman attempts to deal with the death ...,Amber Tamblyn,"Alia Shawkat, Nancy Kwan, Annabelle Attanasio,...",2016,96,8.3,61,NaN,71.0
293,294,The Exception,Drama,A German soldier tries to determine if the Dut...,David Leveaux,"Lily James, Jai Courtney, Christopher Plummer,...",2016,107,7.7,96,NaN,NaN
393,394,Whisky Galore,"Comedy,Romance",Scottish islanders try to plunder cases of whi...,Gillies MacKinnon,"Tim Pigott-Smith, Naomi Battrick, Ellie Kendri...",2016,98,5.0,102,NaN,43.0
337,338,Tracktown,"Drama,Sport","A young, talented, and lonely long-distance ru...",Alexi Pappas,"Alexi Pappas, Chase Offerle, Rachel Dratch, An...",2016,88,5.9,115,NaN,64.0
416,417,The Headhunter's Calling,Drama,A headhunter whose life revolves around closin...,Mark Williams,"Alison Brie, Gerard Butler, Willem Dafoe, Gret...",2016,108,6.9,164,NaN,85.0
...,...,...,...,...,...,...,...,...,...,...,...,...
230,231,Pan's Labyrinth,"Drama,Fantasy,War","In the falangist Spain of 1944, the bookish yo...",Guillermo del Toro,"Ivana Baquero, Ariadna Gil, Sergi López,Maribe...",2006,118,8.2,498879,37.62,98.0
78,79,Pirates of the Caribbean: Dead Man's Chest,"Action,Adventure,Fantasy",Jack Sparrow races to recover the heart of Dav...,Gore Verbinski,"Johnny Depp, Orlando Bloom, Keira Knightley, J...",2006,151,7.3,552027,423.03,53.0
113,114,300,"Action,Fantasy,War",King Leonidas of Sparta and a force of 300 men...,Zack Snyder,"Gerard Butler, Lena Headey, David Wenham, Domi...",2006,117,7.7,637104,210.59,52.0
64,65,The Prestige,"Drama,Mystery,Sci-Fi",Two stage magicians engage in competitive one-...,Christopher Nolan,"Christian Bale, Hugh Jackman, Scarlett Johanss...",2006,130,8.5,913152,53.08,66.0
99,100,The Departed,"Crime,Drama,Thriller",An undercover cop and a mole in the police att...,Martin Scorsese,"Leonardo DiCaprio, Matt Damon, Jack Nicholson,...",2006,151,8.5,937414,132.37,85.0

****

****

## 4.  Filtrar DataFrame

No siempre vas a necesitar todo el DataFrame para hacer tus análisis, muchas veces será más cómodo solo tener una parte de él. Para ello podemos hacer subsetting (crear subconjuntos).

En su forma más básica puedes seleccionar las columnas que deseas y filtrar las filas de esta manera:

- ```df['col_name']``` → Selecciona una columna.
- ```df[['col1_name', 'col2_name']]``` → Selecciona 2 o más columnas. Nota que puse una lista dentro de los corchetes.
- ```df[df.col_name == 'value']``` → Filtra los datos.
- ```df[df['col_name'] == 'value']``` → También filtra los datos, pero con distinta notación.
- ```df[df.col_name.isin(list)]``` → Puedes añadir una lista con varios datos a filtrar.
- ```df.query('player_name == value')``` → Otra forma de filtrar datos.

In [17]:
df["Director"]

0                James Gunn
1              Ridley Scott
2        M. Night Shyamalan
3      Christophe Lourdelet
4                David Ayer
               ...
995               Billy Ray
996                Eli Roth
997              Jon M. Chu
998          Scot Armstrong
999        Barry Sonnenfeld
Name: Director, Length: 1000, dtype: object

In [18]:
df[["Director", "Title"]]

                 Director                    Title
0              James Gunn  Guardians of the Galaxy
1            Ridley Scott               Prometheus
2      M. Night Shyamalan                    Split
3    Christophe Lourdelet                     Sing
4              David Ayer            Suicide Squad
..                    ...                      ...
995             Billy Ray     Secret in Their Eyes
996              Eli Roth          Hostel: Part II
997            Jon M. Chu   Step Up 2: The Streets
998        Scot Armstrong             Search Party
999      Barry Sonnenfeld               Nine Lives

[1000 rows x 2 columns]

Podemos ver que siempre y cuando nuestra columna no tenga espacios, Pandas permite seleccionar la misma con "." o "[]". Si el nombre de cualquier columna tuviera espacios, es recomendable eliminarlos, sin embargo siempre nos quedaría usar "[]".

In [19]:
df[df.Director == "James Gunn"]

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
908,909,Slither,"Comedy,Horror,Sci-Fi","A small town is taken over by an alien plague,...",James Gunn,"Nathan Fillion, Elizabeth Banks, Michael Rooke...",2006,95,6.5,64351,7.77,69.0
937,938,Super,"Comedy,Drama",After his wife falls under the influence of a ...,James Gunn,"Rainn Wilson, Ellen Page, Liv Tyler, Kevin Bacon",2010,96,6.8,64535,0.32,50.0

In [20]:
df[df["Director"] == "James Gunn"]

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
908,909,Slither,"Comedy,Horror,Sci-Fi","A small town is taken over by an alien plague,...",James Gunn,"Nathan Fillion, Elizabeth Banks, Michael Rooke...",2006,95,6.5,64351,7.77,69.0
937,938,Super,"Comedy,Drama",After his wife falls under the influence of a ...,James Gunn,"Rainn Wilson, Ellen Page, Liv Tyler, Kevin Bacon",2010,96,6.8,64535,0.32,50.0

In [21]:
df[df.Director.isin(["James Gunn", "Billy Ray"])]

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
908,909,Slither,"Comedy,Horror,Sci-Fi","A small town is taken over by an alien plague,...",James Gunn,"Nathan Fillion, Elizabeth Banks, Michael Rooke...",2006,95,6.5,64351,7.77,69.0
937,938,Super,"Comedy,Drama",After his wife falls under the influence of a ...,James Gunn,"Rainn Wilson, Ellen Page, Liv Tyler, Kevin Bacon",2010,96,6.8,64535,0.32,50.0
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0

```df.query()``` es una función que contiene aspectos más avanzados, por lo que la veremos con detenimiento en el módulo 2.

In [22]:
df.query("Director in ('James Gunn', 'Billy Ray')")

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
908,909,Slither,"Comedy,Horror,Sci-Fi","A small town is taken over by an alien plague,...",James Gunn,"Nathan Fillion, Elizabeth Banks, Michael Rooke...",2006,95,6.5,64351,7.77,69.0
937,938,Super,"Comedy,Drama",After his wife falls under the influence of a ...,James Gunn,"Rainn Wilson, Ellen Page, Liv Tyler, Kevin Bacon",2010,96,6.8,64535,0.32,50.0
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0

También puedes usar operadores como "&" o "|" para poner varias condiciones y colocar cada una de ellas entre paréntesis.

In [23]:
df[(df.Director == "James Gunn") & (df.Year == 2014)]

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0

In [24]:
df[(df.Director == "James Gunn") | (df.Year == 2014)]

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
36,37,Interstellar,"Adventure,Drama,Sci-Fi",A team of explorers travel through a wormhole ...,Christopher Nolan,"Matthew McConaughey, Anne Hathaway, Jessica Ch...",2014,169,8.6,1047747,187.99,74.0
53,54,John Wick,"Action,Crime,Thriller",An ex-hitman comes out of retirement to track ...,Chad Stahelski,"Keanu Reeves, Michael Nyqvist, Alfie Allen, Wi...",2014,101,7.2,321933,43.00,68.0
65,66,Kingsman: The Secret Service,"Action,Adventure,Comedy","A spy organization recruits an unrefined, but ...",Matthew Vaughn,"Colin Firth, Taron Egerton, Samuel L. Jackson,...",2014,129,7.7,440209,128.25,58.0
83,84,Gone Girl,"Crime,Drama,Mystery",With his wife's disappearance having become th...,David Fincher,"Ben Affleck, Rosamund Pike, Neil Patrick Harri...",2014,149,8.1,636243,167.74,79.0
...,...,...,...,...,...,...,...,...,...,...,...,...
981,982,Annie,"Comedy,Drama,Family","A foster kid, who lives with her mean foster m...",Will Gluck,"Quvenzhané Wallis, Cameron Diaz, Jamie Foxx, R...",2014,118,5.3,27312,85.91,33.0
983,984,Let's Be Cops,Comedy,Two struggling pals dress as police officers f...,Luke Greenfield,"Jake Johnson, Damon Wayans Jr., Rob Riggle, Ni...",2014,104,6.5,112729,82.39,30.0
987,988,Endless Love,"Drama,Romance",The story of a privileged girl and a charismat...,Shana Feste,"Gabriella Wilde, Alex Pettyfer, Bruce Greenwoo...",2014,104,6.3,33688,23.39,30.0
989,990,Selma,"Biography,Drama,History",A chronicle of Martin Luther King's campaign t...,Ava DuVernay,"David Oyelowo, Carmen Ejogo, Tim Roth, Lorrain...",2014,128,7.5,67637,52.07,NaN
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0

Para mejorar el filtrado de strings dentro de una columna se puede utilizar ```df["col_name"].str.lower().str.contains()``` o también ```df["col_name"].str.lower().str.startswith()```. Hay muchas funciones que pueden ser de utilidad, y muchas de ellas las veremos en el módulo 2.

In [25]:
filt = df["Director"].str.lower().str.contains("james")
df[filt]

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
8,9,The Lost City of Z,"Action,Adventure,Biography","A true-life drama, centering on British explor...",James Gray,"Charlie Hunnam, Robert Pattinson, Sienna Mille...",2016,141,7.1,7188,8.01,78.0
84,85,Furious Seven,"Action,Crime,Thriller",Deckard Shaw seeks revenge against Dominic Tor...,James Wan,"Vin Diesel, Paul Walker, Dwayne Johnson, Jason...",2015,137,7.2,301249,350.03,67.0
87,88,Avatar,"Action,Adventure,Fantasy",A paraplegic marine dispatched to the moon Pan...,James Cameron,"Sam Worthington, Zoe Saldana, Sigourney Weaver...",2009,162,7.8,935408,760.51,83.0
178,179,The Conjuring 2,"Horror,Mystery,Thriller",Lorraine and Ed Warren travel to north London ...,James Wan,"Vera Farmiga, Patrick Wilson, Madison Wolfe, F...",2016,134,7.4,137203,102.46,65.0
...,...,...,...,...,...,...,...,...,...,...,...,...
905,906,In Dubious Battle,Drama,An activist gets caught up in the labor moveme...,James Franco,"Nat Wolff, James Franco, Vincent D'Onofrio, Se...",2016,110,6.2,1455,NaN,43.0
908,909,Slither,"Comedy,Horror,Sci-Fi","A small town is taken over by an alien plague,...",James Gunn,"Nathan Fillion, Elizabeth Banks, Michael Rooke...",2006,95,6.5,64351,7.77,69.0
913,914,Coherence,"Mystery,Sci-Fi,Thriller",Strange things begin to happen when a group of...,James Ward Byrkit,"Emily Baldoni, Maury Sterling, Nicholas Brendo...",2013,89,7.2,66265,0.07,65.0
937,938,Super,"Comedy,Drama",After his wife falls under the influence of a ...,James Gunn,"Rainn Wilson, Ellen Page, Liv Tyler, Kevin Bacon",2010,96,6.8,64535,0.32,50.0
964,965,Custody,Drama,The lives of three women are unexpectedly chan...,James Lapine,"Viola Davis, Hayden Panettiere, Catalina Sandi...",2016,104,6.9,280,NaN,72.0

Podemos realizar el contrario del filtro añadiendo ```~``` al principio.

In [ ]:
filt = df["Director"].str.lower().str.contains("james")
df[~filt]

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
5,6,The Great Wall,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,Secret in Their Eyes,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
997,998,Step Up 2: The Streets,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

****

### 4.1. Vistas vs copias en subconjuntos

Es muy importante que si quereis trabajar con varios subconjuntos creeis copias, debido a que si no lo haceís, cuando cambie cualquier subconjunto, cambiará todo.

In [26]:
x = df["Director"]
id(x) == id(df["Director"])

True

In [27]:
x = df["Director"].copy()
id(x) == id(df["Director"])

False

****

****

## 5. Índice del DataFrame

Pandas crea un indice cuando importamos nuestro conjunto de datos, pero es posible poner una columna como indice y así poder desbloquear otras funcionalidades que ofrece Pandas.

Para trabajar con indices es importante mencionar las siguientes funciones:

- ```df.set_index('col_name')``` → Pone una columna como índice.
- ```df.reset_index()``` → Elimina el índice.
- ```df.sort_index(ascending=True)``` → Ordena el índice.

In [28]:
df.set_index("Title", inplace=True)
df

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
Suicide Squad,5,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...
Secret in Their Eyes,996,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
Hostel: Part II,997,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
Step Up 2: The Streets,998,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
Search Party,999,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
Nine Lives,1000,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [29]:
df.sort_index(ascending=False)

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Zootopia,75,"Animation,Adventure,Comedy","In a city of anthropomorphic animals, a rookie...",Byron Howard,"Ginnifer Goodwin, Jason Bateman, Idris Elba, J...",2016,108,8.1,296853,341.26,78.0
Zoolander 2,432,Comedy,Derek and Hansel are lured into modeling again...,Ben Stiller,"Ben Stiller, Owen Wilson, Penélope Cruz, Will ...",2016,102,4.7,48297,28.84,34.0
Zombieland,364,"Adventure,Comedy,Horror",A shy student trying to reach his family in Oh...,Ruben Fleischer,"Jesse Eisenberg, Emma Stone, Woody Harrelson,A...",2009,88,7.7,409403,75.59,73.0
Zodiac,278,"Crime,Drama,History","In the late 1960s/early 1970s, a San Francisco...",David Fincher,"Jake Gyllenhaal, Robert Downey Jr., Mark Ruffa...",2007,157,7.7,329683,33.05,78.0
Zipper,545,"Drama,Thriller",A successful family man with a blossoming poli...,Mora Stephens,"Patrick Wilson, Lena Headey, Ray Winstone,Rich...",2015,103,5.7,4912,NaN,39.0
...,...,...,...,...,...,...,...,...,...,...,...
127 Hours,818,"Adventure,Biography,Drama",An adventurous mountain climber becomes trappe...,Danny Boyle,"James Franco, Amber Tamblyn, Kate Mara, Sean Bott",2010,94,7.6,294010,18.33,82.0
12 Years a Slave,112,"Biography,Drama,History","In the antebellum United States, Solomon North...",Steve McQueen,"Chiwetel Ejiofor, Michael Kenneth Williams, Mi...",2013,134,8.1,486338,56.67,96.0
10 Years,697,"Comedy,Drama,Romance","The night before their high school reunion, a ...",Jamie Linden,"Channing Tatum, Rosario Dawson, Chris Pratt, J...",2011,100,6.1,19636,0.20,NaN
10 Cloverfield Lane,119,"Drama,Horror,Mystery","After getting in a car accident, a woman is he...",Dan Trachtenberg,"John Goodman, Mary Elizabeth Winstead, John Ga...",2016,104,7.2,192968,71.90,76.0
(500) Days of Summer,508,"Comedy,Drama,Romance",An offbeat romantic comedy about a woman who d...,Marc Webb,"Zooey Deschanel, Joseph Gordon-Levitt, Geoffre...",2009,95,7.7,398972,32.39,76.0

****

### 5.1. Método .loc

Ahora que hemos desbloqueado otra funcionalidad de filtrado, podemos usar ```df.loc```:
- ```df.loc[:, ['col_name', 'another_col']]``` → accede a todas las filas y columnas específicas.
- ```df.loc[['row_index', 'another_row']]``` → accede a todas las columnas y filas específicas.
- ```df.loc[['row_index', 'another_row'], ['col_name', 'another_col']]``` → filas y columnas específicas.

Primero consultamos nuestro índice

In [30]:
df.index

Index(['Guardians of the Galaxy', 'Prometheus', 'Split', 'Sing',
       'Suicide Squad', 'The Great Wall', 'La La Land', 'Mindhorn',
       'The Lost City of Z', 'Passengers',
       ...
       'Underworld: Rise of the Lycans', 'Taare Zameen Par',
       'Take Me Home Tonight', 'Resident Evil: Afterlife', 'Project X',
       'Secret in Their Eyes', 'Hostel: Part II', 'Step Up 2: The Streets',
       'Search Party', 'Nine Lives'],
      dtype='object', name='Title', length=1000)

Fijaros que el primer argumento deben de ser las filas y el siguiente argumento deben de ser las columnas.

In [31]:
df.loc[:, ["Rank", "Director"]]

                         Rank              Director
Title
Guardians of the Galaxy     1            James Gunn
Prometheus                  2          Ridley Scott
Split                       3    M. Night Shyamalan
Sing                        4  Christophe Lourdelet
Suicide Squad               5            David Ayer
...                       ...                   ...
Secret in Their Eyes      996             Billy Ray
Hostel: Part II           997              Eli Roth
Step Up 2: The Streets    998            Jon M. Chu
Search Party              999        Scot Armstrong
Nine Lives               1000      Barry Sonnenfeld

[1000 rows x 2 columns]

In [32]:
df.loc[["Guardians of the Galaxy", "Sing"]]

,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
Title,,,,,,,,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0

In [33]:
df.loc[["Guardians of the Galaxy", "Sing"], ["Rank", "Director"]]

                         Rank              Director
Title
Guardians of the Galaxy     1            James Gunn
Sing                        4  Christophe Lourdelet

Podemos eliminar los "[]" y añadir ":" para poder consultar los datos que van desde un rango hasta otro, tanto en columnas como en índices.

In [ ]:
df.loc["Guardians of the Galaxy": "Sing", "Rank":"Director"]

,Rank,Genre,Description,Director
Title,,,,
Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn
Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott
Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan
Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet

Utilizando df.loc podemos filtrar de la misma manera que lo hemos hecho anteriormente:

In [34]:
filt = (df.Director == "James Gunn") # Antes
df["Year"][filt]

Title
Guardians of the Galaxy    2014
Slither                    2006
Super                      2010
Name: Year, dtype: int64

In [35]:
filt = (df.Director == "James Gunn") # Ahora
df.loc[filt, "Year"]

Title
Guardians of the Galaxy    2014
Slither                    2006
Super                      2010
Name: Year, dtype: int64

Cabe la pena mencionar que no debeís confundir ```df.loc``` con ```df.iloc```. En loc se usan las etiquetas (los nombres asignados tanto a las filas como a las columnas) mientras que en iloc se usan los índices de los elementos (la posición en la fila o la columna, comenzado a contar en 0). Algo que se puede usar para recordar cual se debe usar, al trabajar con índices se debe emplear el que comienza por i.

In [36]:
df.iloc[0:2, 0:2]

                         Rank                     Genre
Title
Guardians of the Galaxy     1   Action,Adventure,Sci-Fi
Prometheus                  2  Adventure,Mystery,Sci-Fi

Para volver al indice original debemos de aplicar:

In [37]:
df.reset_index(inplace = True)
df.head(3)

,Title,Rank,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0

****

****

## 6. Actualizar columnas y filas

****

### 6.1. Actualizar columnas

Recordar que podemos consultar el nombre de nuestras columnas de la siguiente forma:

In [38]:
df.columns

Index(['Title', 'Rank', 'Genre', 'Description', 'Director', 'Actors', 'Year',
       'Runtime (Minutes)', 'Rating', 'Votes', 'Revenue (Millions)',
       'Metascore'],
      dtype='object')

Si queremos renombrar a las columnas, tenemos varias maneras para hacerlo:
- Pasar una lista de nombres. La longitud de la lista debe de ser igual al número de columnas.

In [39]:
df.columns = ["Title", "Rank", "Genre", "Description", "Director",
              "Actors", "Year", "Runtime_Minutes", "Rating",
              "Votes", "Revenue_Millions", "Metascore"]

df.head(1)

,Title,Rank,Genre,Description,Director,Actors,Year,Runtime_Minutes,Rating,Votes,Revenue_Millions,Metascore
0,Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0

- Renombrar las columnas que deseamos pasando un diccionario.

In [40]:
df.rename(columns={"Revenue_Millions": "Revenue_Mill", "Runtime_Minutes": "Runtime_Min"}, inplace = True)
df.head(1)

,Title,Rank,Genre,Description,Director,Actors,Year,Runtime_Min,Rating,Votes,Revenue_Mill,Metascore
0,Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0

Si quisieramos realizar una misma operación para todos los nombres de las columnas, como por ejemplo, poner todos los nombres de las columnas en minúsculas, entonces esto es lo que deberiamos de realizar:

In [41]:
df.columns = [x.lower() for x in df.columns]
df.head(1)

,title,rank,genre,description,director,actors,year,runtime_min,rating,votes,revenue_mill,metascore
0,Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0

****

### 6.2. Actualizar filas (datos dentro del DataFrame)

Imaginaros que queremos cambiar alguna de las filas que hay en este nuevo DataFrame.

Como por ejemplo que "Slither" no la ha realizado "James Gunn", si no "Salvador Fernández":

In [43]:
filt = df["director"] == "James Gunn"
df1 = df[filt].copy()
df1

,title,rank,genre,description,director,actors,year,runtime_min,rating,votes,revenue_mill,metascore
0,Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
908,Slither,909,"Comedy,Horror,Sci-Fi","A small town is taken over by an alien plague,...",James Gunn,"Nathan Fillion, Elizabeth Banks, Michael Rooke...",2006,95,6.5,64351,7.77,69.0
937,Super,938,"Comedy,Drama",After his wife falls under the influence of a ...,James Gunn,"Rainn Wilson, Ellen Page, Liv Tyler, Kevin Bacon",2010,96,6.8,64535,0.32,50.0

Esto se puede realizar con .loc o .at:

In [44]:
df1.loc[908, "director"] = "Salvador Fernández"
df1

,title,rank,genre,description,director,actors,year,runtime_min,rating,votes,revenue_mill,metascore
0,Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
908,Slither,909,"Comedy,Horror,Sci-Fi","A small town is taken over by an alien plague,...",Salvador Fernández,"Nathan Fillion, Elizabeth Banks, Michael Rooke...",2006,95,6.5,64351,7.77,69.0
937,Super,938,"Comedy,Drama",After his wife falls under the influence of a ...,James Gunn,"Rainn Wilson, Ellen Page, Liv Tyler, Kevin Bacon",2010,96,6.8,64535,0.32,50.0

In [45]:
df1.at[908, "director"] = "Otro director"
df1

,title,rank,genre,description,director,actors,year,runtime_min,rating,votes,revenue_mill,metascore
0,Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
908,Slither,909,"Comedy,Horror,Sci-Fi","A small town is taken over by an alien plague,...",Otro director,"Nathan Fillion, Elizabeth Banks, Michael Rooke...",2006,95,6.5,64351,7.77,69.0
937,Super,938,"Comedy,Drama",After his wife falls under the influence of a ...,James Gunn,"Rainn Wilson, Ellen Page, Liv Tyler, Kevin Bacon",2010,96,6.8,64535,0.32,50.0

Lo que nunca se prodría hacer es modificar ese valor usando un filtro, es decir:

In [46]:
df1[df1["director"] == "Otro director"]["director"]

908    Otro director
Name: director, dtype: object

In [47]:
df1[df1["director"] == "Otro director"]["director"] = "José Novo"

<ipython-input-47-5b0d4b48298c>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[df1["director"] == "Otro director"]["director"] = "José Novo"

In [48]:
df1

,title,rank,genre,description,director,actors,year,runtime_min,rating,votes,revenue_mill,metascore
0,Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
908,Slither,909,"Comedy,Horror,Sci-Fi","A small town is taken over by an alien plague,...",Otro director,"Nathan Fillion, Elizabeth Banks, Michael Rooke...",2006,95,6.5,64351,7.77,69.0
937,Super,938,"Comedy,Drama",After his wife falls under the influence of a ...,James Gunn,"Rainn Wilson, Ellen Page, Liv Tyler, Kevin Bacon",2010,96,6.8,64535,0.32,50.0

****

#### 6.2.1 Modificar múltiples filas a la vez

Este cometido lo podemos realizar de múltiples formas:
- Podemos aplicar funciones de texto.
- Podemos aplicar operadores.
- Podemos aplicar o crear nuevas funciones ya existentes y usar apply().
- Podemos usar funciones lambda.
- Podemos usar applymap().
- Podemos usar replace() o map().

Veremos con más con más detalle esta forma de manipulación en el módulo 2.

In [51]:
df1.description = df1.description.str.lower() # Hacer que todas las palabras de la columna description sean minúsculas
df1

,title,rank,genre,description,director,actors,year,runtime_min,rating,votes,revenue_mill,metascore
0,Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",a group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
908,Slither,909,"Comedy,Horror,Sci-Fi","a small town is taken over by an alien plague,...",Otro director,"Nathan Fillion, Elizabeth Banks, Michael Rooke...",2006,95,6.5,64351,7.77,69.0
937,Super,938,"Comedy,Drama",after his wife falls under the influence of a ...,James Gunn,"Rainn Wilson, Ellen Page, Liv Tyler, Kevin Bacon",2010,96,6.8,64535,0.32,50.0

In [52]:
df1["description_len"] = df1.description.apply(len) # Crear una nueva columna para calcular la longitud del texto
df1

,title,rank,genre,description,director,actors,...,runtime_min,rating,votes,revenue_mill,metascore,description_len
0,Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",a group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",...,121,8.1,757074,333.13,76.0,127
908,Slither,909,"Comedy,Horror,Sci-Fi","a small town is taken over by an alien plague,...",Otro director,"Nathan Fillion, Elizabeth Banks, Michael Rooke...",...,95,6.5,64351,7.77,69.0,111
937,Super,938,"Comedy,Drama",after his wife falls under the influence of a ...,James Gunn,"Rainn Wilson, Ellen Page, Liv Tyler, Kevin Bacon",...,96,6.8,64535,0.32,50.0,180

In [53]:
def calcular_n_generos(genero):
    genero = genero.split(",")
    genero = len(genero)
    return genero

df1.genre = df1.genre.apply(calcular_n_generos) # Crear una función para contar el número de generos y utilizar .apply
df1

,title,rank,genre,description,director,actors,...,runtime_min,rating,votes,revenue_mill,metascore,description_len
0,Guardians of the Galaxy,1,3,a group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",...,121,8.1,757074,333.13,76.0,127
908,Slither,909,3,"a small town is taken over by an alien plague,...",Otro director,"Nathan Fillion, Elizabeth Banks, Michael Rooke...",...,95,6.5,64351,7.77,69.0,111
937,Super,938,2,after his wife falls under the influence of a ...,James Gunn,"Rainn Wilson, Ellen Page, Liv Tyler, Kevin Bacon",...,96,6.8,64535,0.32,50.0,180

In [54]:
df1.runtime_min = df1.runtime_min.apply(lambda x: x/60) # Dividir runtime_min entre 60 para obtener las horas
df1

,title,rank,genre,description,director,actors,...,runtime_min,rating,votes,revenue_mill,metascore,description_len
0,Guardians of the Galaxy,1,3,a group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",...,2.016667,8.1,757074,333.13,76.0,127
908,Slither,909,3,"a small town is taken over by an alien plague,...",Otro director,"Nathan Fillion, Elizabeth Banks, Michael Rooke...",...,1.583333,6.5,64351,7.77,69.0,111
937,Super,938,2,after his wife falls under the influence of a ...,James Gunn,"Rainn Wilson, Ellen Page, Liv Tyler, Kevin Bacon",...,1.600000,6.8,64535,0.32,50.0,180

In [55]:
df2 = df1.applymap(lambda x: str(x) + '_X') # Aplicar a todo un dataset una función deseada
df2

<ipython-input-55-d52419db6555>:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df2 = df1.applymap(lambda x: str(x) + '_X') # Aplicar a todo un dataset una función deseada

,title,rank,genre,description,director,actors,...,runtime_min,rating,votes,revenue_mill,metascore,description_len
0,Guardians of the Galaxy_X,1_X,3_X,a group of intergalactic criminals are forced ...,James Gunn_X,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",...,2.0166666666666666_X,8.1_X,757074_X,333.13_X,76.0_X,127_X
908,Slither_X,909_X,3_X,"a small town is taken over by an alien plague,...",Otro director_X,"Nathan Fillion, Elizabeth Banks, Michael Rooke...",...,1.5833333333333333_X,6.5_X,64351_X,7.77_X,69.0_X,111_X
937,Super_X,938_X,2_X,after his wife falls under the influence of a ...,James Gunn_X,"Rainn Wilson, Ellen Page, Liv Tyler, Kevin Bac...",...,1.6_X,6.8_X,64535_X,0.32_X,50.0_X,180_X

In [56]:
df1.genre = df1.genre.replace(3, 4) # Remplazamos un elemento tantas veces se repita por otro
df1

,title,rank,genre,description,director,actors,...,runtime_min,rating,votes,revenue_mill,metascore,description_len
0,Guardians of the Galaxy,1,4,a group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",...,2.016667,8.1,757074,333.13,76.0,127
908,Slither,909,4,"a small town is taken over by an alien plague,...",Otro director,"Nathan Fillion, Elizabeth Banks, Michael Rooke...",...,1.583333,6.5,64351,7.77,69.0,111
937,Super,938,2,after his wife falls under the influence of a ...,James Gunn,"Rainn Wilson, Ellen Page, Liv Tyler, Kevin Bacon",...,1.600000,6.8,64535,0.32,50.0,180

In [57]:
dict_map = {'James Gunn': 'J. G.',
            'Jorge Rincón': 'J. R.'}

df1.director = df1.director.map(dict_map) # Al igual que replace, reemplazamos los elementos
df1

,title,rank,genre,description,director,actors,...,runtime_min,rating,votes,revenue_mill,metascore,description_len
0,Guardians of the Galaxy,1,4,a group of intergalactic criminals are forced ...,J. G.,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",...,2.016667,8.1,757074,333.13,76.0,127
908,Slither,909,4,"a small town is taken over by an alien plague,...",NaN,"Nathan Fillion, Elizabeth Banks, Michael Rooke...",...,1.583333,6.5,64351,7.77,69.0,111
937,Super,938,2,after his wife falls under the influence of a ...,J. G.,"Rainn Wilson, Ellen Page, Liv Tyler, Kevin Bacon",...,1.600000,6.8,64535,0.32,50.0,180

In [ ]:
dict_map = {'J. G.': 'James Gunn'}

df1.director = df1.director.map(dict_map) # Tener encuenta la limitación (ver NaN)
df1

,title,rank,genre,description,director,actors,...,runtime_min,rating,votes,revenue_mill,metascore,description_len
0,Guardians of the Galaxy,1,4,a group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",...,2.016667,8.1,757074,333.13,76.0,127
908,Slither,909,4,"a small town is taken over by an alien plague,...",NaN,"Nathan Fillion, Elizabeth Banks, Michael Rooke...",...,1.583333,6.5,64351,7.77,69.0,111
937,Super,938,2,after his wife falls under the influence of a ...,James Gunn,"Rainn Wilson, Ellen Page, Liv Tyler, Kevin Bacon",...,1.600000,6.8,64535,0.32,50.0,180

****

****

## 7. Limpiar DataFrame

****

### 7.1. Eliminar filas o/y columnas

Podemos eliminar filar o/y columnas usando `df.drop()`.

In [58]:
df.drop(index=4).head(5)

,title,rank,genre,description,director,actors,year,runtime_min,rating,votes,revenue_mill,metascore
0,Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
5,The Great Wall,6,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42.0

In [59]:
df.drop(columns="rank").head(6)

,title,genre,description,director,actors,year,runtime_min,rating,votes,revenue_mill,metascore
0,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
5,The Great Wall,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42.0

******

### 7.2. Eliminar nulos del DataFrame

También podemos eliminar nulos de nuestro DataFrame. Primero vamos a echarle un vistazo a nuestro df:

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         1000 non-null   object
 1   rank          1000 non-null   int64
 2   genre         1000 non-null   object
 3   description   1000 non-null   object
 4   director      1000 non-null   object
 5   actors        1000 non-null   object
 6   year          1000 non-null   int64
 7   runtime_min   1000 non-null   int64
 8   rating        1000 non-null   float64
 9   votes         1000 non-null   int64
 10  revenue_mill  872 non-null    float64
 11  metascore     936 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 93.9+ KB

Vemos que las columnas "revenue_mill" y "metascore" tienen valores nulos.

In [61]:
df.dropna(axis="index" , how="any") # Podemos eliminar nulos de forma horizontal (filas)

,title,rank,genre,description,director,actors,year,runtime_min,rating,votes,revenue_mill,metascore
0,Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,Suicide Squad,5,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...
993,Resident Evil: Afterlife,994,"Action,Adventure,Horror",While still out to destroy the evil Umbrella C...,Paul W.S. Anderson,"Milla Jovovich, Ali Larter, Wentworth Miller,K...",2010,97,5.9,140900,60.13,37.0
994,Project X,995,Comedy,3 high school seniors throw a birthday party t...,Nima Nourizadeh,"Thomas Mann, Oliver Cooper, Jonathan Daniel Br...",2012,88,6.7,164088,54.72,48.0
996,Hostel: Part II,997,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0
997,Step Up 2: The Streets,998,"Drama,Music,Romance",Romantic sparks occur between two dance studen...,Jon M. Chu,"Robert Hoffman, Briana Evigan, Cassie Ventura,...",2008,98,6.2,70699,58.01,50.0
999,Nine Lives,1000,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [62]:
df.dropna(axis="columns" , how="any").head(3) # O de forma vertical

,title,rank,genre,description,director,actors,year,runtime_min,rating,votes
0,Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074
1,Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820
2,Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606

In [63]:
df.dropna(axis="index" , how="any", subset=["revenue_mill", "metascore"]).head(10) # También podemos hacerlo
                                                                                  # seleccionando un subset

,title,rank,genre,description,director,actors,year,runtime_min,rating,votes,revenue_mill,metascore
0,Guardians of the Galaxy,1,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,Prometheus,2,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,Split,3,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,Sing,4,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,Suicide Squad,5,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0
5,The Great Wall,6,"Action,Adventure,Fantasy",European mercenaries searching for black powde...,Yimou Zhang,"Matt Damon, Tian Jing, Willem Dafoe, Andy Lau",2016,103,6.1,56036,45.13,42.0
6,La La Land,7,"Comedy,Drama,Music",A jazz pianist falls for an aspiring actress i...,Damien Chazelle,"Ryan Gosling, Emma Stone, Rosemarie DeWitt, J....",2016,128,8.3,258682,151.06,93.0
8,The Lost City of Z,9,"Action,Adventure,Biography","A true-life drama, centering on British explor...",James Gray,"Charlie Hunnam, Robert Pattinson, Sienna Mille...",2016,141,7.1,7188,8.01,78.0
9,Passengers,10,"Adventure,Drama,Romance",A spacecraft traveling to a distant colony pla...,Morten Tyldum,"Jennifer Lawrence, Chris Pratt, Michael Sheen,...",2016,116,7.0,192177,100.01,41.0
10,Fantastic Beasts and Where to Find Them,11,"Adventure,Family,Fantasy",The adventures of writer Newt Scamander in New...,David Yates,"Eddie Redmayne, Katherine Waterston, Alison Su...",2016,133,7.5,232072,234.02,66.0

Si queremos ver que filas contienen nuestros valores nulos, podemos hacerlo de la siguiente forma:

In [64]:
df[df["revenue_mill"].isnull()]

,title,rank,genre,description,director,actors,year,runtime_min,rating,votes,revenue_mill,metascore
7,Mindhorn,8,Comedy,A has-been actor best known for playing the ti...,Sean Foley,"Essie Davis, Andrea Riseborough, Julian Barrat...",2016,89,6.4,2490,NaN,71.0
22,Hounds of Love,23,"Crime,Drama,Horror",A cold-blooded predatory couple while cruising...,Ben Young,"Emma Booth, Ashleigh Cummings, Stephen Curry,S...",2016,108,6.7,1115,NaN,72.0
25,Paris pieds nus,26,Comedy,Fiona visits Paris for the first time to assis...,Dominique Abel,"Fiona Gordon, Dominique Abel,Emmanuelle Riva, ...",2016,83,6.8,222,NaN,NaN
39,5- 25- 77,40,"Comedy,Drama","Alienated, hopeful-filmmaker Pat Johnson's epi...",Patrick Read Johnson,"John Francis Daley, Austin Pendleton, Colleen ...",2007,113,7.1,241,NaN,NaN
42,Don't Fuck in the Woods,43,Horror,A group of friends are going on a camping trip...,Shawn Burkett,"Brittany Blanton, Ayse Howard, Roman Jossart,N...",2016,73,2.7,496,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
977,Amateur Night,978,Comedy,Guy Carter is an award-winning graduate studen...,Lisa Addario,"Jason Biggs, Janet Montgomery,Ashley Tisdale, ...",2016,92,5.0,2229,NaN,38.0
978,It's Only the End of the World,979,Drama,"Louis (Gaspard Ulliel), a terminally ill write...",Xavier Dolan,"Nathalie Baye, Vincent Cassel, Marion Cotillar...",2016,97,7.0,10658,NaN,48.0
988,Martyrs,989,Horror,A young woman's quest for revenge against the ...,Pascal Laugier,"Morjana Alaoui, Mylène Jampanoï, Catherine Bég...",2008,99,7.1,63785,NaN,89.0
995,Secret in Their Eyes,996,"Crime,Drama,Mystery","A tight-knit team of rising investigators, alo...",Billy Ray,"Chiwetel Ejiofor, Nicole Kidman, Julia Roberts...",2015,111,6.2,27585,NaN,45.0
998,Search Party,999,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0

*******

### 7.3. Imputar datos en un DataFrame

También podríamos querer imputar los datos que son nulos en un DataFrame, para ello es interesante usar `.fillna()`, esta función nos permite sustituir todos los nulos de un dataframe o en una columna específica.

In [65]:
df.fillna(0).info() # En todo el DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         1000 non-null   object
 1   rank          1000 non-null   int64
 2   genre         1000 non-null   object
 3   description   1000 non-null   object
 4   director      1000 non-null   object
 5   actors        1000 non-null   object
 6   year          1000 non-null   int64
 7   runtime_min   1000 non-null   int64
 8   rating        1000 non-null   float64
 9   votes         1000 non-null   int64
 10  revenue_mill  1000 non-null   float64
 11  metascore     1000 non-null   float64
dtypes: float64(3), int64(4), object(5)
memory usage: 93.9+ KB

In [66]:
df.revenue_mill.fillna(0).isna().sum() # En una columna específica

0

****

****

## 8.  Analizar Series de un DataFrame

Pandas tiene muchas funciones de utilidad para extraer información de las columnas, entre ellas destacan:

- ```.sum()``` → Suma todos los valores de una columna.
- ```.mean()``` → Promedio de los valores de una columna.
- ```.max()``` → Valor máximo de una columna.
- ```.min()``` → Valor mínimo de una columna.
- ```.cumsum()``` → En cada fila va poniendo la suma acumulada de una columna.
- ```.cummax()``` → En cada fila va poniendo el valor máximo encontrado en orden de una columna.
- ```.value_counts(sort=True)``` → Cuenta los distintos valores que existen en una columna (muy útil para contar categorías) y los ordena descendientemente. También puedes utilizar normalize para que te de el peso relativo.
- ```.unique()``` → Devuelve los valores unicos que existen en una columna.
- ```.nunique()``` → Devuelve el número de valores unicos que existen en una columna.

In [ ]:
df["runtime_min"].sum() # Suma del tiempo en minutos

113172

In [ ]:
df["revenue_mill"].mean() # Media del ingreso en millones

82.95637614678898

In [ ]:
df["rating"].max() # Máximo del rating de todas las peliculas

9.0

In [ ]:
df["rating"].min() # Mínimo del rating de todas las peliculas

1.9

In [ ]:
df["runtime_min"].cumsum() # Suma acumulada de del tiempo de visualización que supondría ver todas las películas

0         121
1         245
2         362
3         470
4         593
        ...
995    112800
996    112894
997    112992
998    113085
999    113172
Name: runtime_min, Length: 1000, dtype: int64

In [69]:
df["director"].value_counts(sort=True) # Conteo por valores únicos de los directores

director
Ridley Scott          8
David Yates           6
M. Night Shyamalan    6
Paul W.S. Anderson    6
Michael Bay           6
                     ..
Lee Toland Krieger    1
Gillies MacKinnon     1
Peter Atencio         1
James Mangold         1
Scot Armstrong        1
Name: count, Length: 644, dtype: int64

In [ ]:
df["director"].value_counts(normalize=True) # Peso relativo del número de peliculas que ha hecho un director

Ridley Scott          0.008
David Yates           0.006
M. Night Shyamalan    0.006
Paul W.S. Anderson    0.006
Michael Bay           0.006
                      ...
Lee Toland Krieger    0.001
Gillies MacKinnon     0.001
Peter Atencio         0.001
James Mangold         0.001
Scot Armstrong        0.001
Name: director, Length: 644, dtype: float64

In [73]:
df["year"].unique() # Valores únicos dentro de una columna

array([2014, 2012, 2016, 2015, 2007, 2011, 2008, 2006, 2009, 2010, 2013])

In [71]:
df["year"].nunique() # Número de valores únicos dentro de una columna

11

****

****

## 9. Agrupar datos

Cuando se quiere obtener conclusiones de un dataset, muchas veces es muy interesante poder agrupar la información, esto lo podemos hacer siguiendo las siguientes funciones:

- ```df.groupby('col_name_to_group')['col_name_to_aggregate'].mean()``` → Agrupa los datos de la columna que está entre (paréntesis) y obtiene la media de la columna que está entre [corchetes].
- ```df.groupby('col_name')['col_name'].agg([min, max, sum])``` → Obtiene múltiples estadísticas.
- ```df.groupby(['col_name', 'another_col'])['col_name'].mean()``` → Agrupa varias columnas.
- ```df.groupby(['col_name', 'another_col'])[['col_name', 'another_col']].mean()``` → Obtiene la media de múltiples columnas.

In [74]:
df.groupby("director").mean() # Calcular la media de todas las columnas númericas según los valores únicos de director

TypeError: agg function failed [how->mean,dtype->object]

In [75]:
df.groupby("director")["rating"].mean() # Calcular la media del rating según los valores únicos de director #Siempre teneis la opcion de poner as_index=False como argumento

director
Aamir Khan             8.50
Abdellatif Kechiche    7.80
Adam Leon              6.50
Adam McKay             7.00
Adam Shankman          6.30
                       ...
Xavier Dolan           7.55
Yimou Zhang            6.10
Yorgos Lanthimos       7.20
Zack Snyder            7.04
Zackary Adler          5.10
Name: rating, Length: 644, dtype: float64

In [76]:
df.groupby("director")["rating"].agg(["min", "max", "mean"]) # Calcular el max, min y media del rating para director

                     min  max  mean
director
Aamir Khan           8.5  8.5  8.50
Abdellatif Kechiche  7.8  7.8  7.80
Adam Leon            6.5  6.5  6.50
Adam McKay           6.6  7.8  7.00
Adam Shankman        5.9  6.7  6.30
...                  ...  ...   ...
Xavier Dolan         7.0  8.1  7.55
Yimou Zhang          6.1  6.1  6.10
Yorgos Lanthimos     7.1  7.3  7.20
Zack Snyder          6.1  7.7  7.04
Zackary Adler        5.1  5.1  5.10

[644 rows x 3 columns]

In [77]:
df.groupby("director")[["rating", "votes"]].agg({"rating":"min", "votes":"max"}) # Calcular diferentes métricas

                     rating   votes
director
Aamir Khan              8.5  102697
Abdellatif Kechiche     7.8  103150
Adam Leon               6.5    1031
Adam McKay              6.6  246360
Adam Shankman           5.9  102954
...                     ...     ...
Xavier Dolan            7.0   33560
Yimou Zhang             6.1   56036
Yorgos Lanthimos        7.1  121313
Zack Snyder             6.1  637104
Zackary Adler           5.1    1630

[644 rows x 2 columns]

In [ ]:
df.groupby("director", as_index=False)[["rating", "votes"]].agg({"rating":"min", "votes":"max"}) # Sin índices

                director  rating   votes
0             Aamir Khan     8.5  102697
1    Abdellatif Kechiche     7.8  103150
2              Adam Leon     6.5    1031
3             Adam McKay     6.6  246360
4          Adam Shankman     5.9  102954
..                   ...     ...     ...
639         Xavier Dolan     7.0   33560
640          Yimou Zhang     6.1   56036
641     Yorgos Lanthimos     7.1  121313
642          Zack Snyder     6.1  637104
643        Zackary Adler     5.1    1630

[644 rows x 3 columns]

In [79]:
df.groupby("director")["title"].count().loc["Adam McKay"] # Podemos consultar de una "celda" con .loc

4

****

****

## 10. Exportar datos

Has terminado todo tu análisis y resulta que ahora tienes una tabla completamente diferente a la inicial, así que necesitas exportar tus datos.

Pandas tiene una serie de funciones que te permiten exportar tus datos al formato que quieras. Su estructura es ```df.to_{file_type}('path/file_name')```. Tiene un argumento interesante que, en caso de tener la lista de índices por defecto, podrías no exportarla usando index=False. Para exportar nuestro DataFrame podríamos usar:

In [ ]:
df.to_csv('IMDB_analisis.csv', index=False)

****

****

# Ejercicios - Pandas

1. Importa Pandas en un nuevo cuaderno de Google Colab y lee el archivo CSV que esta en el siguiente link: https://raw.githubusercontent.com/JorgeRincon-PY/datasets/main/Titanic.csv
2. Usa `df.head()` para echar un vistazo al dataset. Podeis encontrar más información sobre las columnas aquí: https://www.kaggle.com/competitions/titanic/data
3. Usa `df.describe()` y `df.info()` cuenta que insights podemos ver a simple vista.
4. Elimina las columnas "Ticket", "Cabin", "Name", "SibSp" y "Parch".
5. Elimina las filas donde haya un NaN en la columna "Age" y en la columna "Embarked".
6. Filtra los pasajeros que sobrevivieron y calcula la edad media de los supervivientes.
7. Filtra los pasajeros que son mujeres y que tenían billete de 1º clase. Después calcula su tasa de supervivencia. ¿Qué ocurre con las mujeres que tenían billetes en 3º clase?
8. Sin utilizar los filtros anteriores, agrupa por tipo de clase de ticket ("Pclass") y calcula la tasa de supervivencia por grupo. Reagrupa y calcula la tasa de supervivencia por tipo de clase de ticket y por genero.
9. Sin utilizar los filtros anteriores, agrupa por puerta de embarcación y calcula su tasa de supervivencia.
10. De los supervivientes, ¿quién pago una tasa más cara por su billete? Calcula la media del precio y desglosa por tipo de clase de billete.
11. ¿Cómo podríamos crear un dataset final con solo variables numéricas?

## 1. Importa Pandas en un nuevo cuaderno de Google Colab y lee el archivo CSV que esta en el siguiente link: https://raw.githubusercontent.com/JorgeRincon-PY/datasets/main/Titanic.csv

In [ ]:
import pandas as pd

In [ ]:
titanic = pd.read_csv("https://raw.githubusercontent.com/JorgeRincon-PY/datasets/main/Titanic.csv")

## 2. Usa `df.head()` para echar un vistazo al dataset. Podeis encontrar más información sobre las columnas aquí: https://www.kaggle.com/competitions/titanic/data

In [ ]:
titanic.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

## 3. Usa `df.describe()` y `df.info()` cuenta que insights podemos ver a simple vista.

In [ ]:
titanic.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
titanic.info() #Observar los valores nulos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

## 4. Elimina las columnas "Ticket", "Cabin", "Name", "SibSp" y "Parch".

In [ ]:
titanic.drop(columns=["Ticket", "Cabin", "Name", "SibSp", "Parch"], inplace=True)
titanic

     PassengerId  Survived  Pclass     Sex   Age     Fare Embarked
0              1         0       3    male  22.0   7.2500        S
1              2         1       1  female  38.0  71.2833        C
2              3         1       3  female  26.0   7.9250        S
3              4         1       1  female  35.0  53.1000        S
4              5         0       3    male  35.0   8.0500        S
..           ...       ...     ...     ...   ...      ...      ...
886          887         0       2    male  27.0  13.0000        S
887          888         1       1  female  19.0  30.0000        S
888          889         0       3  female   NaN  23.4500        S
889          890         1       1    male  26.0  30.0000        C
890          891         0       3    male  32.0   7.7500        Q

[891 rows x 7 columns]

## 5. Elimina las filas donde haya un NaN en la columna "Age" y en la columna "Embarked".

In [ ]:
titanic.dropna(axis="index", how="all", subset=["Age", "Embarked"], inplace = True)
titanic

     PassengerId  Survived  Pclass     Sex   Age     Fare Embarked
0              1         0       3    male  22.0   7.2500        S
1              2         1       1  female  38.0  71.2833        C
2              3         1       3  female  26.0   7.9250        S
3              4         1       1  female  35.0  53.1000        S
4              5         0       3    male  35.0   8.0500        S
..           ...       ...     ...     ...   ...      ...      ...
886          887         0       2    male  27.0  13.0000        S
887          888         1       1  female  19.0  30.0000        S
888          889         0       3  female   NaN  23.4500        S
889          890         1       1    male  26.0  30.0000        C
890          891         0       3    male  32.0   7.7500        Q

[891 rows x 7 columns]

## 6. Filtra los pasajeros que sobrevivieron y calcula la edad media de los supervivientes.

In [ ]:
filtro = titanic["Survived"] == 1
titanic[filtro]["Age"].mean()

28.343689655172415

## 7. Filtra los pasajeros que son mujeres y que tenían billete de 1º clase. Después calcula su tasa de supervivencia. ¿Qué ocurre con las mujeres que tenían billetes en 3º clase?

In [ ]:
titanic[(titanic.Sex=='female') & (titanic.Pclass==1)]['Survived'].sum()/titanic[(titanic.Sex=='female') & (titanic.Pclass==1)]['Survived'].count()

0.9680851063829787

In [ ]:
titanic[(titanic.Sex=='female') & (titanic.Pclass==3)]['Survived'].sum()/titanic[(titanic.Sex=='female') & (titanic.Pclass==3)]['Survived'].count()

0.5

## 8. Sin utilizar los filtros anteriores, agrupa por tipo de clase de ticket ("Pclass") y calcula la tasa de supervivencia por grupo. Reagrupa y calcula la tasa de supervivencia por tipo de clase de ticket y por genero.

[Explicación](https://drive.google.com/file/d/1OQeOozlxJqYLLZzR-xKdFIugkL5HZ4Jd/view?usp=sharing)

In [ ]:
titanic.groupby(["Pclass"], as_index=False)["Survived"].agg(["count", "sum"])

        count  sum
Pclass
1         216  136
2         184   87
3         491  119

In [ ]:
titanic.groupby(["Pclass"], as_index=False)["Survived"].agg(["mean"])

            mean
Pclass
1       0.629630
2       0.472826
3       0.242363

In [ ]:
titanic.groupby(["Pclass", "Sex"], as_index=False)["Survived"].mean()

   Pclass     Sex  Survived
0       1  female  0.968085
1       1    male  0.368852
2       2  female  0.921053
3       2    male  0.157407
4       3  female  0.500000
5       3    male  0.135447

## 9. Sin utilizar los filtros anteriores, agrupa por puerta de embarcación y calcula su tasa de supervivencia.

In [ ]:
titanic.groupby(["Embarked"], as_index=False)["Survived"].mean()

  Embarked  Survived
0        C  0.553571
1        Q  0.389610
2        S  0.336957

## 10. De los supervivientes, ¿quién pago una tasa más cara por su billete? Calcula la media del precio y desglosa por tipo de clase de billete.

In [ ]:
titanic[titanic["Survived"] == 1].groupby(["Pclass"], as_index=False)["Fare"].mean()

   Pclass       Fare
0       1  95.608029
1       2  22.055700
2       3  13.694887

## 11. ¿Cómo podríamos crear un dataset final con solo variables numéricas?

In [ ]:
titanic.info() #Observamos que variales no son númericas

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Sex          891 non-null    object
 4   Age          714 non-null    float64
 5   Fare         891 non-null    float64
 6   Embarked     889 non-null    object
dtypes: float64(2), int64(3), object(2)
memory usage: 48.9+ KB

In [ ]:
print(titanic["Sex"].unique()) #Obtenemos los valores únicos
print(titanic["Embarked"].unique())

['male' 'female']
['S' 'C' 'Q' nan]

In [ ]:
valores_map1 = {"male": "1", "female": "2"} #Mapeamos los valores
valores_map2 = {"S": "1", "C": "2", "Q": "3"}

titanic["Sex"] = titanic["Sex"].map(valores_map1)
titanic["Embarked"] = titanic["Embarked"].map(valores_map2)

In [ ]:
titanic

     PassengerId  Survived  Pclass Sex   Age     Fare Embarked
0              1         0       3   1  22.0   7.2500        1
1              2         1       1   2  38.0  71.2833        2
2              3         1       3   2  26.0   7.9250        1
3              4         1       1   2  35.0  53.1000        1
4              5         0       3   1  35.0   8.0500        1
..           ...       ...     ...  ..   ...      ...      ...
886          887         0       2   1  27.0  13.0000        1
887          888         1       1   2  19.0  30.0000        1
888          889         0       3   2   NaN  23.4500        1
889          890         1       1   1  26.0  30.0000        2
890          891         0       3   1  32.0   7.7500        3

[891 rows x 7 columns]

In [ ]:
titanic.to_csv("analisis-titanic.csv")