# Manipulación de datos (2) - Fusionar conjuntos de datos

*****

Importar Pandas:

In [1]:
import pandas as pd

*****

## 1. Seleccionar la función / Entender el contexto

Hay cuatro funciones de Pandas que pueden ser utilizadas para fusionar conjuntos de datos. La sintaxis de estas funciones es la siguiente:

******

Siendo dos conjuntos de datos df1y df2:

`df1.append(df2)` :
- Apilado vertical.

`pd.concat([df1, df2])` :
1. Apilado vertical y horizontal.
2. Inner/outer joins en indices.

`df1.join(df2)` :
- inner/outer/left/right joins en indices.

`pd.merge(df1, df2)` :
- Todos los joins en multiples columnas.

*****

#### En la mayoría de los casos siempre se usan `pd.concat()` para apilar y `pd.merge()` para unir.

*****

### 1.1. Apilar

<img src="https://drive.google.com/uc?id=1p8J4xnTYWYYVOuFL-MorquK3y8vf_9Ru" width="60%">

A continuación, se crean dos DataFrames para entender mejor el funcionamiento de la función `.concat()`:

In [2]:
d1 = {"Nombre": ["Jose", "Salva"], "ID": [1, 2]}
d2 = {"Nombre": ["Jorge", "Rubén"], "ID": [3, 4]}

df1 = pd.DataFrame(d1)
df2 = pd.DataFrame(d2)

In [3]:
df1

  Nombre  ID
0   Jose   1
1  Salva   2

In [4]:
df2

  Nombre  ID
0  Jorge   3
1  Rubén   4

*****

#### Apilar verticalmente:

In [5]:
pd.concat([df1, df2])

  Nombre  ID
0   Jose   1
1  Salva   2
0  Jorge   3
1  Rubén   4

Para borrar el indice se puede introducir `ignore_index = True`

In [6]:
pd.concat([df1, df2], ignore_index = True)

  Nombre  ID
0   Jose   1
1  Salva   2
2  Jorge   3
3  Rubén   4

También se puede crear un nuevo indice para indicar de donde proviene mi conjunto de datos

In [7]:
pd.concat([df1, df2], keys=["A", "B"])

    Nombre  ID
A 0   Jose   1
  1  Salva   2
B 0  Jorge   3
  1  Rubén   4

*****

#### Apilar horizontalmente:

In [ ]:
pd.concat([df1, df2], axis = 1)

  Nombre  ID Nombre  ID
0   Jose   1  Jorge   3
1  Salva   2  Rubén   4

*****

### 1.2. Unir

<img src="https://drive.google.com/uc?id=1mrnsXv1wjPpBA-cljB2Nc9sX716gqAfK" width="40%">

Hay cuatro tipos de uniones que nos permite realizar la función `.merge()` de Pandas.

- **Inner Join**. Usa la intersección de las claves de ambos conjuntos de datos, similar a un Inner Join de SQL; preserva el orden de las claves de la izquierda.
- **Outer Join**. Usa la unión de las claves de ambos conjuntos de datos, similar a un Full Outer Join de SQL.
- **Left Join**. Utiliza sólo las claves del conjunto de datos izquierdo, similar a una Left Outer Join SQL; conserva el orden de las claves del conjunto izquierdo.
- **Right Join**. Utiliza sólo las claves del marco derecho, de forma similar a una Right Outer Join de SQL; conserva el orden de las claves del conjunto derecho.

El valor por defecto en esta función es el "inner join".

Parametros de la función:

`
pd.merge(
    left,
    right,
    how="inner",
    on=None,
    left_on=None,
    right_on=None,
    left_index=False,
    right_index=False,
    sort=True,
    suffixes=("_x", "_y"),
    copy=True,
    indicator=False,
    validate=None
)
`

Es más sencillo entender los distintos tipos viendo algunos ejemplos:

In [8]:
A = pd.DataFrame({'Nombre': ['Jairo', 'Belen', 'Elena'], 'Pais': ['Spain', 'USA', 'Germany'], 'Puesto': ['CEO', 'CTO', 'CTO']})
A

  Nombre     Pais Puesto
0  Jairo    Spain    CEO
1  Belen      USA    CTO
2  Elena  Germany    CTO

In [9]:
B = pd.DataFrame({'ID': [1, 2, 3], 'Nombre': ['Sheila', 'Rosario', 'Jairo']})
B

   ID   Nombre
0   1   Sheila
1   2  Rosario
2   3    Jairo

*****

#### 1.2.1. Inner join

Incluir sólo las observaciones encontradas tanto en A como en B:

In [10]:
pd.merge(A, B, how='inner', on=["Nombre"])

  Nombre   Pais Puesto  ID
0  Jairo  Spain    CEO   3

*****

#### 1.2.2. Outer join

Incluir las observaciones encontradas en A o B:

In [11]:
pd.merge(A, B, how='outer', on=["Nombre"])

    Nombre     Pais Puesto   ID
0    Jairo    Spain    CEO  3.0
1    Belen      USA    CTO  NaN
2    Elena  Germany    CTO  NaN
3   Sheila      NaN    NaN  1.0
4  Rosario      NaN    NaN  2.0

*****

####  1.2.3. Left join

Incluir todas las observaciones encontradas en A:

In [12]:
pd.merge(A, B, how='left', on=["Nombre"])

  Nombre     Pais Puesto   ID
0  Jairo    Spain    CEO  3.0
1  Belen      USA    CTO  NaN
2  Elena  Germany    CTO  NaN

*****

#### 1.2.4. Right join

Incluir todas las observaciones encontradas en B:

In [13]:
pd.merge(A, B, how='right', on=["Nombre"])

    Nombre   Pais Puesto  ID
0   Sheila    NaN    NaN   1
1  Rosario    NaN    NaN   2
2    Jairo  Spain    CEO   3

*****

#### 1.2.5. Todo junto

`indicator = True` nos da la funcionalidad de observar que ocurre:

In [14]:
pd.merge(A, B, how="outer", on=["Nombre"], indicator=True)

    Nombre     Pais Puesto   ID      _merge
0    Jairo    Spain    CEO  3.0        both
1    Belen      USA    CTO  NaN   left_only
2    Elena  Germany    CTO  NaN   left_only
3   Sheila      NaN    NaN  1.0  right_only
4  Rosario      NaN    NaN  2.0  right_only

*****